// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package oms_cart_worker_di

import (
	"context"
	"github.com/google/wire"
	"github.com/shortlink-org/go-sdk/config"
	"github.com/shortlink-org/go-sdk/context"
	"github.com/shortlink-org/go-sdk/flags"
	"github.com/shortlink-org/go-sdk/logger"
	"github.com/shortlink-org/go-sdk/observability/metrics"
	"github.com/shortlink-org/go-sdk/observability/profiling"
	"github.com/shortlink-org/go-sdk/observability/tracing"
	"github.com/shortlink-org/shop/oms/internal/loggeradapter"
	"github.com/shortlink-org/shop/oms/internal/workers/cart/cart_worker"
	"github.com/shortlink-org/shortlink/pkg/di/pkg/temporal"
	logger2 "github.com/shortlink-org/shortlink/pkg/logger"
	"github.com/shortlink-org/shortlink/pkg/observability/monitoring"
	"go.opentelemetry.io/otel/trace"
	"go.temporal.io/sdk/client"
	"go.temporal.io/sdk/worker"
)

// Injectors from wire.go:

func InitializeOMSCartWorkerService() (*OMSCartWorkerService, func(), error) {
	context, cleanup, err := ctx.New()
	if err != nil {
		return nil, nil, err
	}
	config, err := newGoSDKConfig()
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	logger, cleanup2, err := newGoSDKLogger(context, config)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	tracerProvider, cleanup3, err := newGoSDKTracer(context, logger, config)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	monitoring, cleanup4, err := newGoSDKMonitoring(context, logger, tracerProvider, config)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	pprofEndpoint, err := newGoSDKProfiling(context, logger, tracerProvider, config)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	loggerLogger, cleanup5, err := legacyLoggerAdapter(logger)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	monitoringMonitoring := legacyMonitoringFromGoSDK(monitoring)
	client, err := temporal.New(loggerLogger, monitoringMonitoring)
	if err != nil {
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	worker, err := cart_worker.New(context, client, logger)
	if err != nil {
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	omsCartWorkerService, err := NewOMSCartWorkerService(logger, config, monitoring, tracerProvider, pprofEndpoint, client, worker)
	if err != nil {
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	return omsCartWorkerService, func() {
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}

// wire.go:

type OMSCartWorkerService struct {
	// Common
	Log    logger.Logger
	Config *config.Config

	// Observability
	Tracer        trace.TracerProvider
	Monitoring    *metrics.Monitoring
	PprofEndpoint profiling.PprofEndpoint

	// Temporal
	temporalClient client.Client
	cartWorker     worker.Worker
}

// OMSCartWorkerService ================================================================================================
var CustomDefaultSet = wire.NewSet(ctx.New, flags.New, legacyLoggerAdapter)

var OMSCartWorkerSet = wire.NewSet(
	CustomDefaultSet,

	newGoSDKConfig,
	newGoSDKLogger,
	newGoSDKTracer,
	newGoSDKProfiling,
	newGoSDKMonitoring,
	legacyMonitoringFromGoSDK, temporal.New, cart_worker.New, NewOMSCartWorkerService,
)

// newGoSDKConfig creates a go-sdk config instance
func newGoSDKConfig() (*config.Config, error) {
	return config.New()
}

func newGoSDKProfiling(ctx2 context.Context, log logger.Logger, tracer trace.TracerProvider, cfg *config.Config) (profiling.PprofEndpoint, error) {
	return profiling.New(ctx2, log, tracer, cfg)
}

func newGoSDKLogger(ctx2 context.Context, cfg *config.Config) (logger.Logger, func(), error) {
	return logger.NewDefault(ctx2, cfg)
}

func newGoSDKTracer(ctx2 context.Context, log logger.Logger, cfg *config.Config) (trace.TracerProvider, func(), error) {
	return tracing.New(ctx2, log, cfg)
}

func newGoSDKMonitoring(ctx2 context.Context, log logger.Logger, tracer trace.TracerProvider, cfg *config.Config) (*metrics.Monitoring, func(), error) {
	return metrics.New(ctx2, log, tracer, cfg)
}

func NewOMSCartWorkerService(

	log logger.Logger, config2 *config.Config,

	monitoring *metrics.Monitoring,
	tracer trace.TracerProvider,
	pprofHTTP profiling.PprofEndpoint,

	temporalClient client.Client,
	cartWorker worker.Worker,
) (*OMSCartWorkerService, error) {
	return &OMSCartWorkerService{

		Log:    log,
		Config: config2,

		Tracer:        tracer,
		Monitoring:    monitoring,
		PprofEndpoint: pprofHTTP,

		temporalClient: temporalClient,
		cartWorker:     cartWorker,
	}, nil
}

func legacyLoggerAdapter(log logger.Logger) (logger2.Logger, func(), error) {
	return loggeradapter.New(log), func() {}, nil
}

func legacyMonitoringFromGoSDK(modern *metrics.Monitoring) *monitoring.Monitoring {
	if modern == nil {
		return nil
	}

	return &monitoring.Monitoring{
		Handler:    modern.Handler,
		Prometheus: modern.Prometheus,
		Metrics:    modern.Metrics,
	}
}
