// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package crud

import (
	"github.com/jackc/pgx/v5/pgtype"
)

// Shopping carts by customer
type OmsCart struct {
	CustomerID pgtype.UUID
	// Optimistic concurrency control version
	Version   int32
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

// Items in shopping carts
type OmsCartItem struct {
	CartID   pgtype.UUID
	GoodID   pgtype.UUID
	Quantity int32
	Price    pgtype.Numeric
	Discount pgtype.Numeric
}
