// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package crud

import (
	"context"

	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	DeleteCartItems(ctx context.Context, cartID pgtype.UUID) error
	GetCart(ctx context.Context, customerID pgtype.UUID) (OmsCart, error)
	GetCartItems(ctx context.Context, cartID pgtype.UUID) ([]GetCartItemsRow, error)
	InsertCart(ctx context.Context, customerID pgtype.UUID) error
	InsertCartItem(ctx context.Context, arg InsertCartItemParams) error
	UpsertCart(ctx context.Context, arg UpsertCartParams) (pgconn.CommandTag, error)
}

var _ Querier = (*Queries)(nil)
