include:
  - local: .gitlab/ci/workflows/matrix_build_docker.yml
  - local: .gitlab/ci/workflows/matrix_build_helm.yml

# DOCKER ===============================================================================================================
docker:
  extends:
    - .matrix_build_docker
  stage: build
  trigger:
    include:
      - local: '.gitlab/ci/pipelines/docker.yml'
    strategy: depend

# HELM =================================================================================================================
helm:
  extends:
    - .matrix_build_helm
  stage: build
  trigger:
    include:
      - component: $CI_SERVER_FQDN/shortlink-org/gitlab-templates/helm_publish@main
    strategy: depend
