// This file is @generated by prost-build.
/// GetPackagePoolQuery - Query to get package pool with filters
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetPackagePoolQuery {
    /// Status filters
    #[prost(
        enumeration = "super::super::common::v1::PackageStatus",
        repeated,
        tag = "1"
    )]
    pub status_filter: ::prost::alloc::vec::Vec<i32>,
    /// Priority filters
    #[prost(enumeration = "super::super::common::v1::Priority", repeated, tag = "2")]
    pub priority_filter: ::prost::alloc::vec::Vec<i32>,
    /// Region filter
    #[prost(string, tag = "3")]
    pub region_filter: ::prost::alloc::string::String,
    /// Created from timestamp
    #[prost(message, optional, tag = "4")]
    pub created_from: ::core::option::Option<::pbjson_types::Timestamp>,
    /// Created to timestamp
    #[prost(message, optional, tag = "5")]
    pub created_to: ::core::option::Option<::pbjson_types::Timestamp>,
    /// Filter by assigned courier
    #[prost(string, tag = "6")]
    pub courier_id: ::prost::alloc::string::String,
    /// Pagination
    #[prost(message, optional, tag = "7")]
    pub pagination: ::core::option::Option<Pagination>,
    /// Sort by
    #[prost(enumeration = "SortBy", tag = "8")]
    pub sort_by: i32,
}
/// GetCourierPoolQuery - Query to get courier pool with filters
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetCourierPoolQuery {
    /// Status filters
    #[prost(
        enumeration = "super::super::common::v1::CourierStatus",
        repeated,
        tag = "1"
    )]
    pub status_filter: ::prost::alloc::vec::Vec<i32>,
    /// Transport type filters
    #[prost(
        enumeration = "super::super::common::v1::TransportType",
        repeated,
        tag = "2"
    )]
    pub transport_type_filter: ::prost::alloc::vec::Vec<i32>,
    /// Zone filter
    #[prost(string, tag = "3")]
    pub zone_filter: ::prost::alloc::string::String,
    /// Only available couriers (FREE status)
    #[prost(bool, tag = "4")]
    pub available_only: bool,
    /// Include current location
    #[prost(bool, tag = "5")]
    pub include_location: bool,
    /// Pagination
    #[prost(message, optional, tag = "6")]
    pub pagination: ::core::option::Option<Pagination>,
    /// Sort by
    #[prost(enumeration = "SortBy", tag = "7")]
    pub sort_by: i32,
}
/// Pagination
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Pagination {
    /// Page number
    #[prost(int32, tag = "1")]
    pub page: i32,
    /// Page size (max 100)
    #[prost(int32, tag = "2")]
    pub page_size: i32,
}
/// GetPackagePoolResponse - Response for GetPackagePoolQuery
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetPackagePoolResponse {
    /// Packages
    #[prost(message, repeated, tag = "1")]
    pub packages: ::prost::alloc::vec::Vec<Package>,
    /// Total count
    #[prost(int32, tag = "2")]
    pub total_count: i32,
    /// Pagination info
    #[prost(message, optional, tag = "3")]
    pub pagination: ::core::option::Option<PaginationInfo>,
}
/// GetCourierPoolResponse - Response for GetCourierPoolQuery
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetCourierPoolResponse {
    /// Couriers
    #[prost(message, repeated, tag = "1")]
    pub couriers: ::prost::alloc::vec::Vec<Courier>,
    /// Total count
    #[prost(int32, tag = "2")]
    pub total_count: i32,
    /// Pagination info
    #[prost(message, optional, tag = "3")]
    pub pagination: ::core::option::Option<PaginationInfo>,
}
/// PaginationInfo
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PaginationInfo {
    /// Current page
    #[prost(int32, tag = "1")]
    pub current_page: i32,
    /// Page size
    #[prost(int32, tag = "2")]
    pub page_size: i32,
    /// Total pages
    #[prost(int32, tag = "3")]
    pub total_pages: i32,
    /// Total items
    #[prost(int32, tag = "4")]
    pub total_items: i32,
}
/// Package represents a package in the system
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Package {
    /// Package ID
    #[prost(string, tag = "1")]
    pub package_id: ::prost::alloc::string::String,
    /// Order ID
    #[prost(string, tag = "2")]
    pub order_id: ::prost::alloc::string::String,
    /// Customer ID
    #[prost(string, tag = "3")]
    pub customer_id: ::prost::alloc::string::String,
    /// Pickup address
    #[prost(message, optional, tag = "4")]
    pub pickup_address: ::core::option::Option<super::super::common::v1::Address>,
    /// Delivery address
    #[prost(message, optional, tag = "5")]
    pub delivery_address: ::core::option::Option<super::super::common::v1::Address>,
    /// Delivery period
    #[prost(message, optional, tag = "6")]
    pub delivery_period: ::core::option::Option<
        super::super::common::v1::DeliveryPeriod,
    >,
    /// Package info
    #[prost(message, optional, tag = "7")]
    pub package_info: ::core::option::Option<super::super::common::v1::PackageInfo>,
    /// Priority
    #[prost(enumeration = "super::super::common::v1::Priority", tag = "8")]
    pub priority: i32,
    /// Package status
    #[prost(enumeration = "super::super::common::v1::PackageStatus", tag = "9")]
    pub status: i32,
    /// Courier ID
    #[prost(string, tag = "10")]
    pub courier_id: ::prost::alloc::string::String,
    /// Created at timestamp
    #[prost(message, optional, tag = "11")]
    pub created_at: ::core::option::Option<::pbjson_types::Timestamp>,
    /// Assigned at timestamp
    #[prost(message, optional, tag = "12")]
    pub assigned_at: ::core::option::Option<::pbjson_types::Timestamp>,
    /// Delivered at timestamp
    #[prost(message, optional, tag = "13")]
    pub delivered_at: ::core::option::Option<::pbjson_types::Timestamp>,
    /// Not delivered reason
    #[prost(string, tag = "14")]
    pub not_delivered_reason: ::prost::alloc::string::String,
}
/// Courier represents a courier in the system
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Courier {
    /// Courier ID
    #[prost(string, tag = "1")]
    pub courier_id: ::prost::alloc::string::String,
    /// Courier name
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    /// Courier phone
    #[prost(string, tag = "3")]
    pub phone: ::prost::alloc::string::String,
    /// Courier email
    #[prost(string, tag = "4")]
    pub email: ::prost::alloc::string::String,
    /// Transport type
    #[prost(enumeration = "super::super::common::v1::TransportType", tag = "5")]
    pub transport_type: i32,
    /// Max distance in km
    #[prost(double, tag = "6")]
    pub max_distance_km: f64,
    /// Courier status
    #[prost(enumeration = "super::super::common::v1::CourierStatus", tag = "7")]
    pub status: i32,
    /// Current load
    #[prost(int32, tag = "8")]
    pub current_load: i32,
    /// Max load
    #[prost(int32, tag = "9")]
    pub max_load: i32,
    /// Rating
    #[prost(double, tag = "10")]
    pub rating: f64,
    /// Work hours
    #[prost(message, optional, tag = "11")]
    pub work_hours: ::core::option::Option<super::super::common::v1::WorkHours>,
    /// Work zone
    #[prost(string, tag = "12")]
    pub work_zone: ::prost::alloc::string::String,
    /// Current location (if include_location = true)
    #[prost(message, optional, tag = "13")]
    pub current_location: ::core::option::Option<super::super::common::v1::Location>,
    /// Successful deliveries count
    #[prost(int32, tag = "14")]
    pub successful_deliveries: i32,
    /// Failed deliveries count
    #[prost(int32, tag = "15")]
    pub failed_deliveries: i32,
    /// Created at timestamp
    #[prost(message, optional, tag = "16")]
    pub created_at: ::core::option::Option<::pbjson_types::Timestamp>,
    /// Last active at timestamp
    #[prost(message, optional, tag = "17")]
    pub last_active_at: ::core::option::Option<::pbjson_types::Timestamp>,
}
/// SortBy options
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum SortBy {
    Unspecified = 0,
    CreatedAt = 1,
    Priority = 2,
    DeliveryPeriodStart = 3,
    /// Requires courier location
    Distance = 4,
    Name = 5,
    Rating = 6,
    Load = 7,
    SuccessfulDeliveries = 8,
}
impl SortBy {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "SORT_BY_UNSPECIFIED",
            Self::CreatedAt => "SORT_BY_CREATED_AT",
            Self::Priority => "SORT_BY_PRIORITY",
            Self::DeliveryPeriodStart => "SORT_BY_DELIVERY_PERIOD_START",
            Self::Distance => "SORT_BY_DISTANCE",
            Self::Name => "SORT_BY_NAME",
            Self::Rating => "SORT_BY_RATING",
            Self::Load => "SORT_BY_LOAD",
            Self::SuccessfulDeliveries => "SORT_BY_SUCCESSFUL_DELIVERIES",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "SORT_BY_UNSPECIFIED" => Some(Self::Unspecified),
            "SORT_BY_CREATED_AT" => Some(Self::CreatedAt),
            "SORT_BY_PRIORITY" => Some(Self::Priority),
            "SORT_BY_DELIVERY_PERIOD_START" => Some(Self::DeliveryPeriodStart),
            "SORT_BY_DISTANCE" => Some(Self::Distance),
            "SORT_BY_NAME" => Some(Self::Name),
            "SORT_BY_RATING" => Some(Self::Rating),
            "SORT_BY_LOAD" => Some(Self::Load),
            "SORT_BY_SUCCESSFUL_DELIVERIES" => Some(Self::SuccessfulDeliveries),
            _ => None,
        }
    }
}
