// This file is @generated by prost-build.
/// PackageAcceptedEvent - canonical name: delivery.package.accepted.v1
/// Event when a package is accepted into the pool
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PackageAcceptedEvent {
    /// Package ID
    #[prost(string, tag = "1")]
    pub package_id: ::prost::alloc::string::String,
    /// Order ID
    #[prost(string, tag = "2")]
    pub order_id: ::prost::alloc::string::String,
    /// Customer ID
    #[prost(string, tag = "3")]
    pub customer_id: ::prost::alloc::string::String,
    /// Package status
    #[prost(enumeration = "super::super::common::v1::PackageStatus", tag = "4")]
    pub status: i32,
    /// Created at timestamp
    #[prost(message, optional, tag = "5")]
    pub created_at: ::core::option::Option<::pbjson_types::Timestamp>,
    /// OccurredAt is the timestamp when the event occurred
    #[prost(message, optional, tag = "6")]
    pub occurred_at: ::core::option::Option<::pbjson_types::Timestamp>,
}
/// PackageAssignedEvent - canonical name: delivery.package.assigned.v1
/// Event when a package is assigned to a courier
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PackageAssignedEvent {
    /// Package ID
    #[prost(string, tag = "1")]
    pub package_id: ::prost::alloc::string::String,
    /// Courier ID
    #[prost(string, tag = "2")]
    pub courier_id: ::prost::alloc::string::String,
    /// Package status
    #[prost(enumeration = "super::super::common::v1::PackageStatus", tag = "3")]
    pub status: i32,
    /// Assigned at timestamp
    #[prost(message, optional, tag = "4")]
    pub assigned_at: ::core::option::Option<::pbjson_types::Timestamp>,
    /// Package details for courier notification
    #[prost(message, optional, tag = "5")]
    pub pickup_address: ::core::option::Option<super::super::common::v1::Address>,
    #[prost(message, optional, tag = "6")]
    pub delivery_address: ::core::option::Option<super::super::common::v1::Address>,
    #[prost(message, optional, tag = "7")]
    pub delivery_period: ::core::option::Option<
        super::super::common::v1::DeliveryPeriod,
    >,
    /// Customer phone
    #[prost(string, tag = "8")]
    pub customer_phone: ::prost::alloc::string::String,
    /// OccurredAt is the timestamp when the event occurred
    #[prost(message, optional, tag = "9")]
    pub occurred_at: ::core::option::Option<::pbjson_types::Timestamp>,
}
/// PackageInTransitEvent - canonical name: delivery.package.in_transit.v1
/// Event when package is picked up and in transit
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PackageInTransitEvent {
    /// Package ID
    #[prost(string, tag = "1")]
    pub package_id: ::prost::alloc::string::String,
    /// Order ID (from OMS, for consumer lookup)
    #[prost(string, tag = "2")]
    pub order_id: ::prost::alloc::string::String,
    /// Courier ID
    #[prost(string, tag = "3")]
    pub courier_id: ::prost::alloc::string::String,
    /// Package status
    #[prost(enumeration = "super::super::common::v1::PackageStatus", tag = "4")]
    pub status: i32,
    /// In transit at timestamp
    #[prost(message, optional, tag = "5")]
    pub in_transit_at: ::core::option::Option<::pbjson_types::Timestamp>,
    /// Courier location
    #[prost(message, optional, tag = "6")]
    pub courier_location: ::core::option::Option<super::super::common::v1::Location>,
    /// OccurredAt is the timestamp when the event occurred
    #[prost(message, optional, tag = "7")]
    pub occurred_at: ::core::option::Option<::pbjson_types::Timestamp>,
}
/// PackageDeliveredEvent - canonical name: delivery.package.delivered.v1
/// Event when package is successfully delivered
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PackageDeliveredEvent {
    /// Package ID
    #[prost(string, tag = "1")]
    pub package_id: ::prost::alloc::string::String,
    /// Order ID
    #[prost(string, tag = "2")]
    pub order_id: ::prost::alloc::string::String,
    /// Courier ID
    #[prost(string, tag = "3")]
    pub courier_id: ::prost::alloc::string::String,
    /// Package status
    #[prost(enumeration = "super::super::common::v1::PackageStatus", tag = "4")]
    pub status: i32,
    /// Delivered at timestamp
    #[prost(message, optional, tag = "5")]
    pub delivered_at: ::core::option::Option<::pbjson_types::Timestamp>,
    /// Delivery location
    #[prost(message, optional, tag = "6")]
    pub delivery_location: ::core::option::Option<super::super::common::v1::Location>,
    /// Optional: delivery confirmation photo
    #[prost(bytes = "vec", tag = "7")]
    pub photo: ::prost::alloc::vec::Vec<u8>,
    /// Optional: customer signature
    #[prost(bytes = "vec", tag = "8")]
    pub customer_signature: ::prost::alloc::vec::Vec<u8>,
    /// OccurredAt is the timestamp when the event occurred
    #[prost(message, optional, tag = "9")]
    pub occurred_at: ::core::option::Option<::pbjson_types::Timestamp>,
}
/// PackageNotDeliveredEvent - canonical name: delivery.package.not_delivered.v1
/// Event when package delivery failed
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PackageNotDeliveredEvent {
    /// Package ID
    #[prost(string, tag = "1")]
    pub package_id: ::prost::alloc::string::String,
    /// Order ID
    #[prost(string, tag = "2")]
    pub order_id: ::prost::alloc::string::String,
    /// Courier ID
    #[prost(string, tag = "3")]
    pub courier_id: ::prost::alloc::string::String,
    /// Package status
    #[prost(enumeration = "super::super::common::v1::PackageStatus", tag = "4")]
    pub status: i32,
    /// Not delivered details (reason; description required if reason == OTHER)
    #[prost(message, optional, tag = "5")]
    pub not_delivered_details: ::core::option::Option<
        super::super::common::v1::NotDeliveredDetails,
    >,
    /// Not delivered at timestamp
    #[prost(message, optional, tag = "6")]
    pub not_delivered_at: ::core::option::Option<::pbjson_types::Timestamp>,
    /// Courier location
    #[prost(message, optional, tag = "7")]
    pub courier_location: ::core::option::Option<super::super::common::v1::Location>,
    /// OccurredAt is the timestamp when the event occurred
    #[prost(message, optional, tag = "8")]
    pub occurred_at: ::core::option::Option<::pbjson_types::Timestamp>,
}
/// CourierRegisteredEvent - canonical name: delivery.courier.registered.v1
/// Event when a new courier is registered
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CourierRegisteredEvent {
    /// Courier ID
    #[prost(string, tag = "1")]
    pub courier_id: ::prost::alloc::string::String,
    /// Courier name
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    /// Courier email
    #[prost(string, tag = "3")]
    pub email: ::prost::alloc::string::String,
    /// Courier phone
    #[prost(string, tag = "4")]
    pub phone: ::prost::alloc::string::String,
    /// Transport type
    #[prost(enumeration = "super::super::common::v1::TransportType", tag = "5")]
    pub transport_type: i32,
    /// Courier status
    #[prost(enumeration = "super::super::common::v1::CourierStatus", tag = "6")]
    pub status: i32,
    /// Registered at timestamp
    #[prost(message, optional, tag = "7")]
    pub registered_at: ::core::option::Option<::pbjson_types::Timestamp>,
    /// OccurredAt is the timestamp when the event occurred
    #[prost(message, optional, tag = "8")]
    pub occurred_at: ::core::option::Option<::pbjson_types::Timestamp>,
}
/// CourierLocationUpdatedEvent - canonical name: delivery.courier.location_updated.v1
/// Event when courier location is updated
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CourierLocationUpdatedEvent {
    /// Courier ID
    #[prost(string, tag = "1")]
    pub courier_id: ::prost::alloc::string::String,
    /// Courier location
    #[prost(message, optional, tag = "2")]
    pub location: ::core::option::Option<super::super::common::v1::Location>,
    /// Updated at timestamp
    #[prost(message, optional, tag = "3")]
    pub updated_at: ::core::option::Option<::pbjson_types::Timestamp>,
    /// OccurredAt is the timestamp when the event occurred
    #[prost(message, optional, tag = "4")]
    pub occurred_at: ::core::option::Option<::pbjson_types::Timestamp>,
}
/// CourierStatusChangedEvent - canonical name: delivery.courier.status_changed.v1
/// Event when courier status changes
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CourierStatusChangedEvent {
    /// Courier ID
    #[prost(string, tag = "1")]
    pub courier_id: ::prost::alloc::string::String,
    /// Old status
    #[prost(enumeration = "super::super::common::v1::CourierStatus", tag = "2")]
    pub old_status: i32,
    /// New status
    #[prost(enumeration = "super::super::common::v1::CourierStatus", tag = "3")]
    pub new_status: i32,
    /// Changed at timestamp
    #[prost(message, optional, tag = "4")]
    pub changed_at: ::core::option::Option<::pbjson_types::Timestamp>,
    /// Optional reason for status change
    #[prost(string, tag = "5")]
    pub reason: ::prost::alloc::string::String,
    /// OccurredAt is the timestamp when the event occurred
    #[prost(message, optional, tag = "6")]
    pub occurred_at: ::core::option::Option<::pbjson_types::Timestamp>,
}
/// PackageRequiresHandlingEvent - canonical name: delivery.package.requires_handling.v1
/// Event when package requires manual handling
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PackageRequiresHandlingEvent {
    /// Package ID
    #[prost(string, tag = "1")]
    pub package_id: ::prost::alloc::string::String,
    /// Order ID
    #[prost(string, tag = "2")]
    pub order_id: ::prost::alloc::string::String,
    /// Package status
    #[prost(enumeration = "super::super::common::v1::PackageStatus", tag = "3")]
    pub status: i32,
    /// Reason for manual handling
    #[prost(string, tag = "4")]
    pub reason: ::prost::alloc::string::String,
    /// Requires handling at timestamp
    #[prost(message, optional, tag = "5")]
    pub requires_handling_at: ::core::option::Option<::pbjson_types::Timestamp>,
    /// OccurredAt is the timestamp when the event occurred
    #[prost(message, optional, tag = "6")]
    pub occurred_at: ::core::option::Option<::pbjson_types::Timestamp>,
}
