// This file is @generated by prost-build.
/// Address represents a physical address with coordinates
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Address {
    #[prost(string, tag = "1")]
    pub street: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub city: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub postal_code: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub country: ::prost::alloc::string::String,
    #[prost(double, tag = "5")]
    pub latitude: f64,
    #[prost(double, tag = "6")]
    pub longitude: f64,
}
/// Location represents a GPS location
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct Location {
    #[prost(double, tag = "1")]
    pub latitude: f64,
    #[prost(double, tag = "2")]
    pub longitude: f64,
    /// meters
    #[prost(double, tag = "3")]
    pub accuracy: f64,
    #[prost(message, optional, tag = "4")]
    pub timestamp: ::core::option::Option<::pbjson_types::Timestamp>,
    /// km/h (optional)
    #[prost(double, optional, tag = "5")]
    pub speed: ::core::option::Option<f64>,
    /// degrees 0-360 (optional)
    #[prost(double, optional, tag = "6")]
    pub heading: ::core::option::Option<f64>,
}
/// DeliveryPeriod represents the desired delivery time window
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeliveryPeriod {
    /// Start of desired delivery period
    #[prost(message, optional, tag = "1")]
    pub start_time: ::core::option::Option<::pbjson_types::Timestamp>,
    /// End of desired delivery period
    #[prost(message, optional, tag = "2")]
    pub end_time: ::core::option::Option<::pbjson_types::Timestamp>,
}
/// PackageInfo contains package physical characteristics
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PackageInfo {
    #[prost(double, tag = "1")]
    pub weight_kg: f64,
    /// "LxWxH" format
    #[prost(string, tag = "2")]
    pub dimensions: ::prost::alloc::string::String,
}
/// WorkHours represents courier working hours
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct WorkHours {
    /// "09:00" format
    #[prost(string, tag = "1")]
    pub start_time: ::prost::alloc::string::String,
    /// "18:00" format
    #[prost(string, tag = "2")]
    pub end_time: ::prost::alloc::string::String,
    /// \[1,2,3,4,5\] - Monday to Friday
    #[prost(int32, repeated, tag = "3")]
    pub work_days: ::prost::alloc::vec::Vec<i32>,
}
/// Priority levels for packages
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum Priority {
    Unspecified = 0,
    Normal = 1,
    Urgent = 2,
}
impl Priority {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "PRIORITY_UNSPECIFIED",
            Self::Normal => "PRIORITY_NORMAL",
            Self::Urgent => "PRIORITY_URGENT",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "PRIORITY_UNSPECIFIED" => Some(Self::Unspecified),
            "PRIORITY_NORMAL" => Some(Self::Normal),
            "PRIORITY_URGENT" => Some(Self::Urgent),
            _ => None,
        }
    }
}
/// Package status
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum PackageStatus {
    Unspecified = 0,
    Accepted = 1,
    InPool = 2,
    Assigned = 3,
    InTransit = 4,
    Delivered = 5,
    NotDelivered = 6,
    RequiresHandling = 7,
}
impl PackageStatus {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "PACKAGE_STATUS_UNSPECIFIED",
            Self::Accepted => "PACKAGE_STATUS_ACCEPTED",
            Self::InPool => "PACKAGE_STATUS_IN_POOL",
            Self::Assigned => "PACKAGE_STATUS_ASSIGNED",
            Self::InTransit => "PACKAGE_STATUS_IN_TRANSIT",
            Self::Delivered => "PACKAGE_STATUS_DELIVERED",
            Self::NotDelivered => "PACKAGE_STATUS_NOT_DELIVERED",
            Self::RequiresHandling => "PACKAGE_STATUS_REQUIRES_HANDLING",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "PACKAGE_STATUS_UNSPECIFIED" => Some(Self::Unspecified),
            "PACKAGE_STATUS_ACCEPTED" => Some(Self::Accepted),
            "PACKAGE_STATUS_IN_POOL" => Some(Self::InPool),
            "PACKAGE_STATUS_ASSIGNED" => Some(Self::Assigned),
            "PACKAGE_STATUS_IN_TRANSIT" => Some(Self::InTransit),
            "PACKAGE_STATUS_DELIVERED" => Some(Self::Delivered),
            "PACKAGE_STATUS_NOT_DELIVERED" => Some(Self::NotDelivered),
            "PACKAGE_STATUS_REQUIRES_HANDLING" => Some(Self::RequiresHandling),
            _ => None,
        }
    }
}
/// Courier status
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum CourierStatus {
    Unspecified = 0,
    Unavailable = 1,
    Free = 2,
    Busy = 3,
}
impl CourierStatus {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "COURIER_STATUS_UNSPECIFIED",
            Self::Unavailable => "COURIER_STATUS_UNAVAILABLE",
            Self::Free => "COURIER_STATUS_FREE",
            Self::Busy => "COURIER_STATUS_BUSY",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "COURIER_STATUS_UNSPECIFIED" => Some(Self::Unspecified),
            "COURIER_STATUS_UNAVAILABLE" => Some(Self::Unavailable),
            "COURIER_STATUS_FREE" => Some(Self::Free),
            "COURIER_STATUS_BUSY" => Some(Self::Busy),
            _ => None,
        }
    }
}
/// Transport type
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum TransportType {
    Unspecified = 0,
    Walking = 1,
    Bicycle = 2,
    Motorcycle = 3,
    Car = 4,
}
impl TransportType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "TRANSPORT_TYPE_UNSPECIFIED",
            Self::Walking => "TRANSPORT_TYPE_WALKING",
            Self::Bicycle => "TRANSPORT_TYPE_BICYCLE",
            Self::Motorcycle => "TRANSPORT_TYPE_MOTORCYCLE",
            Self::Car => "TRANSPORT_TYPE_CAR",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "TRANSPORT_TYPE_UNSPECIFIED" => Some(Self::Unspecified),
            "TRANSPORT_TYPE_WALKING" => Some(Self::Walking),
            "TRANSPORT_TYPE_BICYCLE" => Some(Self::Bicycle),
            "TRANSPORT_TYPE_MOTORCYCLE" => Some(Self::Motorcycle),
            "TRANSPORT_TYPE_CAR" => Some(Self::Car),
            _ => None,
        }
    }
}
/// Delivery status (for deliver order)
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum DeliveryStatus {
    Unspecified = 0,
    Delivered = 1,
    NotDelivered = 2,
}
impl DeliveryStatus {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "DELIVERY_STATUS_UNSPECIFIED",
            Self::Delivered => "DELIVERY_STATUS_DELIVERED",
            Self::NotDelivered => "DELIVERY_STATUS_NOT_DELIVERED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "DELIVERY_STATUS_UNSPECIFIED" => Some(Self::Unspecified),
            "DELIVERY_STATUS_DELIVERED" => Some(Self::Delivered),
            "DELIVERY_STATUS_NOT_DELIVERED" => Some(Self::NotDelivered),
            _ => None,
        }
    }
}
/// Reason for not delivered
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum NotDeliveredReason {
    Unspecified = 0,
    CustomerNotAvailable = 1,
    WrongAddress = 2,
    CustomerRefused = 3,
    AccessDenied = 4,
    PackageDamaged = 5,
    Other = 6,
}
impl NotDeliveredReason {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "NOT_DELIVERED_REASON_UNSPECIFIED",
            Self::CustomerNotAvailable => "NOT_DELIVERED_REASON_CUSTOMER_NOT_AVAILABLE",
            Self::WrongAddress => "NOT_DELIVERED_REASON_WRONG_ADDRESS",
            Self::CustomerRefused => "NOT_DELIVERED_REASON_CUSTOMER_REFUSED",
            Self::AccessDenied => "NOT_DELIVERED_REASON_ACCESS_DENIED",
            Self::PackageDamaged => "NOT_DELIVERED_REASON_PACKAGE_DAMAGED",
            Self::Other => "NOT_DELIVERED_REASON_OTHER",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "NOT_DELIVERED_REASON_UNSPECIFIED" => Some(Self::Unspecified),
            "NOT_DELIVERED_REASON_CUSTOMER_NOT_AVAILABLE" => {
                Some(Self::CustomerNotAvailable)
            }
            "NOT_DELIVERED_REASON_WRONG_ADDRESS" => Some(Self::WrongAddress),
            "NOT_DELIVERED_REASON_CUSTOMER_REFUSED" => Some(Self::CustomerRefused),
            "NOT_DELIVERED_REASON_ACCESS_DENIED" => Some(Self::AccessDenied),
            "NOT_DELIVERED_REASON_PACKAGE_DAMAGED" => Some(Self::PackageDamaged),
            "NOT_DELIVERED_REASON_OTHER" => Some(Self::Other),
            _ => None,
        }
    }
}
