// This file is @generated by prost-build.
/// AcceptOrderCommand - Command to accept an order from OMS
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AcceptOrderCommand {
    /// Order ID
    #[prost(string, tag = "1")]
    pub order_id: ::prost::alloc::string::String,
    /// Customer ID
    #[prost(string, tag = "2")]
    pub customer_id: ::prost::alloc::string::String,
    /// Pickup address
    #[prost(message, optional, tag = "3")]
    pub pickup_address: ::core::option::Option<super::super::common::v1::Address>,
    /// Delivery address
    #[prost(message, optional, tag = "4")]
    pub delivery_address: ::core::option::Option<super::super::common::v1::Address>,
    /// Delivery period
    #[prost(message, optional, tag = "5")]
    pub delivery_period: ::core::option::Option<
        super::super::common::v1::DeliveryPeriod,
    >,
    /// Package info
    #[prost(message, optional, tag = "6")]
    pub package_info: ::core::option::Option<super::super::common::v1::PackageInfo>,
    /// Priority
    #[prost(enumeration = "super::super::common::v1::Priority", tag = "7")]
    pub priority: i32,
}
/// AssignOrderCommand - Command to assign a package to a courier
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AssignOrderCommand {
    /// Package ID
    #[prost(string, tag = "1")]
    pub package_id: ::prost::alloc::string::String,
    /// Assignment type
    #[prost(oneof = "assign_order_command::AssignmentType", tags = "2, 3")]
    pub assignment_type: ::core::option::Option<assign_order_command::AssignmentType>,
}
/// Nested message and enum types in `AssignOrderCommand`.
pub mod assign_order_command {
    /// Assignment type
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum AssignmentType {
        /// Manual assignment - courier ID
        #[prost(string, tag = "2")]
        CourierId(::prost::alloc::string::String),
        /// Auto dispatch
        #[prost(bool, tag = "3")]
        AutoAssign(bool),
    }
}
/// DeliverOrderCommand - Command for courier to confirm delivery
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DeliverOrderCommand {
    /// Package ID
    #[prost(string, tag = "1")]
    pub package_id: ::prost::alloc::string::String,
    /// Courier ID
    #[prost(string, tag = "2")]
    pub courier_id: ::prost::alloc::string::String,
    /// Delivery status
    #[prost(enumeration = "super::super::common::v1::DeliveryStatus", tag = "3")]
    pub status: i32,
    /// Reason (required if status is NOT_DELIVERED)
    #[prost(string, tag = "4")]
    pub reason: ::prost::alloc::string::String,
    /// Optional: delivery confirmation photo
    #[prost(bytes = "vec", tag = "5")]
    pub photo: ::prost::alloc::vec::Vec<u8>,
    /// Optional: customer signature
    #[prost(bytes = "vec", tag = "6")]
    pub customer_signature: ::prost::alloc::vec::Vec<u8>,
    /// Courier's current location after delivery
    #[prost(message, optional, tag = "7")]
    pub current_location: ::core::option::Option<super::super::common::v1::Location>,
}
/// UpdateCourierLocationCommand - Command to update courier location
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UpdateCourierLocationCommand {
    /// Courier ID
    #[prost(string, tag = "1")]
    pub courier_id: ::prost::alloc::string::String,
    /// Courier location
    #[prost(message, optional, tag = "2")]
    pub location: ::core::option::Option<super::super::common::v1::Location>,
}
/// RegisterCourierCommand - Command to register a new courier
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RegisterCourierCommand {
    /// Courier name
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    /// Courier phone
    #[prost(string, tag = "2")]
    pub phone: ::prost::alloc::string::String,
    /// Courier email
    #[prost(string, tag = "3")]
    pub email: ::prost::alloc::string::String,
    /// Transport type
    #[prost(enumeration = "super::super::common::v1::TransportType", tag = "4")]
    pub transport_type: i32,
    /// Max distance in km
    #[prost(double, tag = "5")]
    pub max_distance_km: f64,
    /// Work zone (region/district)
    #[prost(string, tag = "6")]
    pub work_zone: ::prost::alloc::string::String,
    /// Work hours
    #[prost(message, optional, tag = "7")]
    pub work_hours: ::core::option::Option<super::super::common::v1::WorkHours>,
    /// FCM/APNS token for notifications
    #[prost(string, tag = "8")]
    pub push_token: ::prost::alloc::string::String,
}
/// AcceptOrderResponse - Response for AcceptOrderCommand
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AcceptOrderResponse {
    /// Package ID
    #[prost(string, tag = "1")]
    pub package_id: ::prost::alloc::string::String,
    /// Package status
    #[prost(enumeration = "super::super::common::v1::PackageStatus", tag = "2")]
    pub status: i32,
    /// Created at timestamp
    #[prost(message, optional, tag = "3")]
    pub created_at: ::core::option::Option<::pbjson_types::Timestamp>,
}
/// AssignOrderResponse - Response for AssignOrderCommand
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AssignOrderResponse {
    /// Package ID
    #[prost(string, tag = "1")]
    pub package_id: ::prost::alloc::string::String,
    /// Courier ID
    #[prost(string, tag = "2")]
    pub courier_id: ::prost::alloc::string::String,
    /// Assigned at timestamp
    #[prost(message, optional, tag = "3")]
    pub assigned_at: ::core::option::Option<::pbjson_types::Timestamp>,
    /// Package status
    #[prost(enumeration = "super::super::common::v1::PackageStatus", tag = "4")]
    pub status: i32,
}
/// DeliverOrderResponse - Response for DeliverOrderCommand
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeliverOrderResponse {
    /// Package ID
    #[prost(string, tag = "1")]
    pub package_id: ::prost::alloc::string::String,
    /// Package status
    #[prost(enumeration = "super::super::common::v1::PackageStatus", tag = "2")]
    pub status: i32,
    /// Updated at timestamp
    #[prost(message, optional, tag = "3")]
    pub updated_at: ::core::option::Option<::pbjson_types::Timestamp>,
}
/// UpdateCourierLocationResponse - Response for UpdateCourierLocationCommand
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UpdateCourierLocationResponse {
    /// Courier ID
    #[prost(string, tag = "1")]
    pub courier_id: ::prost::alloc::string::String,
    /// Updated at timestamp
    #[prost(message, optional, tag = "2")]
    pub updated_at: ::core::option::Option<::pbjson_types::Timestamp>,
    /// Location saved flag
    #[prost(bool, tag = "3")]
    pub location_saved: bool,
}
/// RegisterCourierResponse - Response for RegisterCourierCommand
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RegisterCourierResponse {
    /// Courier ID
    #[prost(string, tag = "1")]
    pub courier_id: ::prost::alloc::string::String,
    /// Courier status
    #[prost(enumeration = "super::super::common::v1::CourierStatus", tag = "2")]
    pub status: i32,
    /// Temporary password for first login
    #[prost(string, tag = "3")]
    pub temporary_password: ::prost::alloc::string::String,
    /// Created at timestamp
    #[prost(message, optional, tag = "4")]
    pub created_at: ::core::option::Option<::pbjson_types::Timestamp>,
}
