apiVersion: v2
appVersion: "1.0.0"
name: delivery
description: ShortLink Delivery Service - courier management and order delivery
version: 0.1.1
kubeVersion: ">= 1.30.0 || >= v1.30.0-0"
keywords:
  - delivery
  - courier
  - shipping
  - shop
  - shortlink
home: https://github.com/shortlink-org/shortlink
sources:
  - https://github.com/shortlink-org/shortlink
maintainers:
  - email: batazor111@gmail.com
    name: batazor
    url: batazor.ru
type: application
deprecated: false
dependencies:
  - name: shortlink-template
    version: 0.12.2
    repository: oci://ghcr.io/shortlink-org/charts
