# Ignore dot-files and dot-directories (except .env*)
.git
.github
.gitlab
.vscode
.idea
.pytest_cache
.mypy_cache
.ruff_cache
__pycache__
*.pyc
*.yml
cmd
docs
ds
internal
ops
pkg
ui
boundaries
node_modules

# Exclude
!.env.prod
!boundaries/shop/admin
boundaries/shop/admin/src/admin/static
