// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: workers/order/workflow/model/order/v1/order.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/emptypb"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CartItem is the cart item message.
type WorkerOrderItem struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Product ID
	OrderId string `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	// Quantity
	Quantity      int32 `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerOrderItem) Reset() {
	*x = WorkerOrderItem{}
	mi := &file_workers_order_workflow_model_order_v1_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerOrderItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerOrderItem) ProtoMessage() {}

func (x *WorkerOrderItem) ProtoReflect() protoreflect.Message {
	mi := &file_workers_order_workflow_model_order_v1_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerOrderItem.ProtoReflect.Descriptor instead.
func (*WorkerOrderItem) Descriptor() ([]byte, []int) {
	return file_workers_order_workflow_model_order_v1_order_proto_rawDescGZIP(), []int{0}
}

func (x *WorkerOrderItem) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *WorkerOrderItem) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

var File_workers_order_workflow_model_order_v1_order_proto protoreflect.FileDescriptor

const file_workers_order_workflow_model_order_v1_order_proto_rawDesc = "" +
	"\n" +
	"1workers/order/workflow/model/order/v1/order.proto\x12%workers.order.workflow.model.order.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"H\n" +
	"\x0fWorkerOrderItem\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x05R\bquantityB\xd9\x02\n" +
	")com.workers.order.workflow.model.order.v1B\n" +
	"OrderProtoP\x01Zegithub.com/shortlink-org/shortlink/boundaries/shop/oms/internal/workers/order/workflow/model/order/v1\xa2\x02\x05WOWMO\xaa\x02%Workers.Order.Workflow.Model.Order.V1\xca\x02%Workers\\Order\\Workflow\\Model\\Order\\V1\xe2\x021Workers\\Order\\Workflow\\Model\\Order\\V1\\GPBMetadata\xea\x02*Workers::Order::Workflow::Model::Order::V1b\x06proto3"

var (
	file_workers_order_workflow_model_order_v1_order_proto_rawDescOnce sync.Once
	file_workers_order_workflow_model_order_v1_order_proto_rawDescData []byte
)

func file_workers_order_workflow_model_order_v1_order_proto_rawDescGZIP() []byte {
	file_workers_order_workflow_model_order_v1_order_proto_rawDescOnce.Do(func() {
		file_workers_order_workflow_model_order_v1_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_workers_order_workflow_model_order_v1_order_proto_rawDesc), len(file_workers_order_workflow_model_order_v1_order_proto_rawDesc)))
	})
	return file_workers_order_workflow_model_order_v1_order_proto_rawDescData
}

var file_workers_order_workflow_model_order_v1_order_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_workers_order_workflow_model_order_v1_order_proto_goTypes = []any{
	(*WorkerOrderItem)(nil), // 0: workers.order.workflow.model.order.v1.WorkerOrderItem
}
var file_workers_order_workflow_model_order_v1_order_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_workers_order_workflow_model_order_v1_order_proto_init() }
func file_workers_order_workflow_model_order_v1_order_proto_init() {
	if File_workers_order_workflow_model_order_v1_order_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_workers_order_workflow_model_order_v1_order_proto_rawDesc), len(file_workers_order_workflow_model_order_v1_order_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_workers_order_workflow_model_order_v1_order_proto_goTypes,
		DependencyIndexes: file_workers_order_workflow_model_order_v1_order_proto_depIdxs,
		MessageInfos:      file_workers_order_workflow_model_order_v1_order_proto_msgTypes,
	}.Build()
	File_workers_order_workflow_model_order_v1_order_proto = out.File
	file_workers_order_workflow_model_order_v1_order_proto_goTypes = nil
	file_workers_order_workflow_model_order_v1_order_proto_depIdxs = nil
}
