// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: domain/delivery/events/v1/events.proto

package v1

import (
	v1 "github.com/shortlink-org/shop/oms/internal/domain/delivery/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PackageAcceptedEvent - canonical name: delivery.package.accepted.v1
// Event when a package is accepted into the pool
type PackageAcceptedEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Package ID
	PackageId string `protobuf:"bytes,1,opt,name=package_id,json=packageId,proto3" json:"package_id,omitempty"`
	// Order ID
	OrderId string `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	// Customer ID
	CustomerId string `protobuf:"bytes,3,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	// Package status
	Status v1.PackageStatus `protobuf:"varint,4,opt,name=status,proto3,enum=domain.delivery.common.v1.PackageStatus" json:"status,omitempty"`
	// Created at timestamp
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// OccurredAt is the timestamp when the event occurred
	OccurredAt    *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PackageAcceptedEvent) Reset() {
	*x = PackageAcceptedEvent{}
	mi := &file_domain_delivery_events_v1_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PackageAcceptedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PackageAcceptedEvent) ProtoMessage() {}

func (x *PackageAcceptedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_domain_delivery_events_v1_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PackageAcceptedEvent.ProtoReflect.Descriptor instead.
func (*PackageAcceptedEvent) Descriptor() ([]byte, []int) {
	return file_domain_delivery_events_v1_events_proto_rawDescGZIP(), []int{0}
}

func (x *PackageAcceptedEvent) GetPackageId() string {
	if x != nil {
		return x.PackageId
	}
	return ""
}

func (x *PackageAcceptedEvent) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *PackageAcceptedEvent) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *PackageAcceptedEvent) GetStatus() v1.PackageStatus {
	if x != nil {
		return x.Status
	}
	return v1.PackageStatus(0)
}

func (x *PackageAcceptedEvent) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *PackageAcceptedEvent) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

// PackageAssignedEvent - canonical name: delivery.package.assigned.v1
// Event when a package is assigned to a courier
type PackageAssignedEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Package ID
	PackageId string `protobuf:"bytes,1,opt,name=package_id,json=packageId,proto3" json:"package_id,omitempty"`
	// Courier ID
	CourierId string `protobuf:"bytes,2,opt,name=courier_id,json=courierId,proto3" json:"courier_id,omitempty"`
	// Package status
	Status v1.PackageStatus `protobuf:"varint,3,opt,name=status,proto3,enum=domain.delivery.common.v1.PackageStatus" json:"status,omitempty"`
	// Assigned at timestamp
	AssignedAt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=assigned_at,json=assignedAt,proto3" json:"assigned_at,omitempty"`
	// Package details for courier notification
	PickupAddress   *v1.Address        `protobuf:"bytes,5,opt,name=pickup_address,json=pickupAddress,proto3" json:"pickup_address,omitempty"`
	DeliveryAddress *v1.Address        `protobuf:"bytes,6,opt,name=delivery_address,json=deliveryAddress,proto3" json:"delivery_address,omitempty"`
	DeliveryPeriod  *v1.DeliveryPeriod `protobuf:"bytes,7,opt,name=delivery_period,json=deliveryPeriod,proto3" json:"delivery_period,omitempty"`
	// Customer phone
	CustomerPhone string `protobuf:"bytes,8,opt,name=customer_phone,json=customerPhone,proto3" json:"customer_phone,omitempty"`
	// OccurredAt is the timestamp when the event occurred
	OccurredAt    *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PackageAssignedEvent) Reset() {
	*x = PackageAssignedEvent{}
	mi := &file_domain_delivery_events_v1_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PackageAssignedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PackageAssignedEvent) ProtoMessage() {}

func (x *PackageAssignedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_domain_delivery_events_v1_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PackageAssignedEvent.ProtoReflect.Descriptor instead.
func (*PackageAssignedEvent) Descriptor() ([]byte, []int) {
	return file_domain_delivery_events_v1_events_proto_rawDescGZIP(), []int{1}
}

func (x *PackageAssignedEvent) GetPackageId() string {
	if x != nil {
		return x.PackageId
	}
	return ""
}

func (x *PackageAssignedEvent) GetCourierId() string {
	if x != nil {
		return x.CourierId
	}
	return ""
}

func (x *PackageAssignedEvent) GetStatus() v1.PackageStatus {
	if x != nil {
		return x.Status
	}
	return v1.PackageStatus(0)
}

func (x *PackageAssignedEvent) GetAssignedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.AssignedAt
	}
	return nil
}

func (x *PackageAssignedEvent) GetPickupAddress() *v1.Address {
	if x != nil {
		return x.PickupAddress
	}
	return nil
}

func (x *PackageAssignedEvent) GetDeliveryAddress() *v1.Address {
	if x != nil {
		return x.DeliveryAddress
	}
	return nil
}

func (x *PackageAssignedEvent) GetDeliveryPeriod() *v1.DeliveryPeriod {
	if x != nil {
		return x.DeliveryPeriod
	}
	return nil
}

func (x *PackageAssignedEvent) GetCustomerPhone() string {
	if x != nil {
		return x.CustomerPhone
	}
	return ""
}

func (x *PackageAssignedEvent) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

// PackageInTransitEvent - canonical name: delivery.package.in_transit.v1
// Event when package is picked up and in transit
type PackageInTransitEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Package ID
	PackageId string `protobuf:"bytes,1,opt,name=package_id,json=packageId,proto3" json:"package_id,omitempty"`
	// Order ID (from OMS, for consumer lookup)
	OrderId string `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	// Courier ID
	CourierId string `protobuf:"bytes,3,opt,name=courier_id,json=courierId,proto3" json:"courier_id,omitempty"`
	// Package status
	Status v1.PackageStatus `protobuf:"varint,4,opt,name=status,proto3,enum=domain.delivery.common.v1.PackageStatus" json:"status,omitempty"`
	// In transit at timestamp
	InTransitAt *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=in_transit_at,json=inTransitAt,proto3" json:"in_transit_at,omitempty"`
	// Courier location
	CourierLocation *v1.Location `protobuf:"bytes,6,opt,name=courier_location,json=courierLocation,proto3" json:"courier_location,omitempty"`
	// OccurredAt is the timestamp when the event occurred
	OccurredAt    *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PackageInTransitEvent) Reset() {
	*x = PackageInTransitEvent{}
	mi := &file_domain_delivery_events_v1_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PackageInTransitEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PackageInTransitEvent) ProtoMessage() {}

func (x *PackageInTransitEvent) ProtoReflect() protoreflect.Message {
	mi := &file_domain_delivery_events_v1_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PackageInTransitEvent.ProtoReflect.Descriptor instead.
func (*PackageInTransitEvent) Descriptor() ([]byte, []int) {
	return file_domain_delivery_events_v1_events_proto_rawDescGZIP(), []int{2}
}

func (x *PackageInTransitEvent) GetPackageId() string {
	if x != nil {
		return x.PackageId
	}
	return ""
}

func (x *PackageInTransitEvent) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *PackageInTransitEvent) GetCourierId() string {
	if x != nil {
		return x.CourierId
	}
	return ""
}

func (x *PackageInTransitEvent) GetStatus() v1.PackageStatus {
	if x != nil {
		return x.Status
	}
	return v1.PackageStatus(0)
}

func (x *PackageInTransitEvent) GetInTransitAt() *timestamppb.Timestamp {
	if x != nil {
		return x.InTransitAt
	}
	return nil
}

func (x *PackageInTransitEvent) GetCourierLocation() *v1.Location {
	if x != nil {
		return x.CourierLocation
	}
	return nil
}

func (x *PackageInTransitEvent) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

// PackageDeliveredEvent - canonical name: delivery.package.delivered.v1
// Event when package is successfully delivered
type PackageDeliveredEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Package ID
	PackageId string `protobuf:"bytes,1,opt,name=package_id,json=packageId,proto3" json:"package_id,omitempty"`
	// Order ID
	OrderId string `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	// Courier ID
	CourierId string `protobuf:"bytes,3,opt,name=courier_id,json=courierId,proto3" json:"courier_id,omitempty"`
	// Package status
	Status v1.PackageStatus `protobuf:"varint,4,opt,name=status,proto3,enum=domain.delivery.common.v1.PackageStatus" json:"status,omitempty"`
	// Delivered at timestamp
	DeliveredAt *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=delivered_at,json=deliveredAt,proto3" json:"delivered_at,omitempty"`
	// Delivery location
	DeliveryLocation *v1.Location `protobuf:"bytes,6,opt,name=delivery_location,json=deliveryLocation,proto3" json:"delivery_location,omitempty"`
	// Optional: delivery confirmation photo
	Photo []byte `protobuf:"bytes,7,opt,name=photo,proto3" json:"photo,omitempty"`
	// Optional: customer signature
	CustomerSignature []byte `protobuf:"bytes,8,opt,name=customer_signature,json=customerSignature,proto3" json:"customer_signature,omitempty"`
	// OccurredAt is the timestamp when the event occurred
	OccurredAt    *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PackageDeliveredEvent) Reset() {
	*x = PackageDeliveredEvent{}
	mi := &file_domain_delivery_events_v1_events_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PackageDeliveredEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PackageDeliveredEvent) ProtoMessage() {}

func (x *PackageDeliveredEvent) ProtoReflect() protoreflect.Message {
	mi := &file_domain_delivery_events_v1_events_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PackageDeliveredEvent.ProtoReflect.Descriptor instead.
func (*PackageDeliveredEvent) Descriptor() ([]byte, []int) {
	return file_domain_delivery_events_v1_events_proto_rawDescGZIP(), []int{3}
}

func (x *PackageDeliveredEvent) GetPackageId() string {
	if x != nil {
		return x.PackageId
	}
	return ""
}

func (x *PackageDeliveredEvent) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *PackageDeliveredEvent) GetCourierId() string {
	if x != nil {
		return x.CourierId
	}
	return ""
}

func (x *PackageDeliveredEvent) GetStatus() v1.PackageStatus {
	if x != nil {
		return x.Status
	}
	return v1.PackageStatus(0)
}

func (x *PackageDeliveredEvent) GetDeliveredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeliveredAt
	}
	return nil
}

func (x *PackageDeliveredEvent) GetDeliveryLocation() *v1.Location {
	if x != nil {
		return x.DeliveryLocation
	}
	return nil
}

func (x *PackageDeliveredEvent) GetPhoto() []byte {
	if x != nil {
		return x.Photo
	}
	return nil
}

func (x *PackageDeliveredEvent) GetCustomerSignature() []byte {
	if x != nil {
		return x.CustomerSignature
	}
	return nil
}

func (x *PackageDeliveredEvent) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

// PackageNotDeliveredEvent - canonical name: delivery.package.not_delivered.v1
// Event when package delivery failed
type PackageNotDeliveredEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Package ID
	PackageId string `protobuf:"bytes,1,opt,name=package_id,json=packageId,proto3" json:"package_id,omitempty"`
	// Order ID
	OrderId string `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	// Courier ID
	CourierId string `protobuf:"bytes,3,opt,name=courier_id,json=courierId,proto3" json:"courier_id,omitempty"`
	// Package status
	Status v1.PackageStatus `protobuf:"varint,4,opt,name=status,proto3,enum=domain.delivery.common.v1.PackageStatus" json:"status,omitempty"`
	// Not delivered reason
	Reason v1.NotDeliveredReason `protobuf:"varint,5,opt,name=reason,proto3,enum=domain.delivery.common.v1.NotDeliveredReason" json:"reason,omitempty"`
	// Additional description if reason is OTHER
	ReasonDescription string `protobuf:"bytes,6,opt,name=reason_description,json=reasonDescription,proto3" json:"reason_description,omitempty"`
	// Not delivered at timestamp
	NotDeliveredAt *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=not_delivered_at,json=notDeliveredAt,proto3" json:"not_delivered_at,omitempty"`
	// Courier location
	CourierLocation *v1.Location `protobuf:"bytes,8,opt,name=courier_location,json=courierLocation,proto3" json:"courier_location,omitempty"`
	// OccurredAt is the timestamp when the event occurred
	OccurredAt    *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PackageNotDeliveredEvent) Reset() {
	*x = PackageNotDeliveredEvent{}
	mi := &file_domain_delivery_events_v1_events_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PackageNotDeliveredEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PackageNotDeliveredEvent) ProtoMessage() {}

func (x *PackageNotDeliveredEvent) ProtoReflect() protoreflect.Message {
	mi := &file_domain_delivery_events_v1_events_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PackageNotDeliveredEvent.ProtoReflect.Descriptor instead.
func (*PackageNotDeliveredEvent) Descriptor() ([]byte, []int) {
	return file_domain_delivery_events_v1_events_proto_rawDescGZIP(), []int{4}
}

func (x *PackageNotDeliveredEvent) GetPackageId() string {
	if x != nil {
		return x.PackageId
	}
	return ""
}

func (x *PackageNotDeliveredEvent) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *PackageNotDeliveredEvent) GetCourierId() string {
	if x != nil {
		return x.CourierId
	}
	return ""
}

func (x *PackageNotDeliveredEvent) GetStatus() v1.PackageStatus {
	if x != nil {
		return x.Status
	}
	return v1.PackageStatus(0)
}

func (x *PackageNotDeliveredEvent) GetReason() v1.NotDeliveredReason {
	if x != nil {
		return x.Reason
	}
	return v1.NotDeliveredReason(0)
}

func (x *PackageNotDeliveredEvent) GetReasonDescription() string {
	if x != nil {
		return x.ReasonDescription
	}
	return ""
}

func (x *PackageNotDeliveredEvent) GetNotDeliveredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.NotDeliveredAt
	}
	return nil
}

func (x *PackageNotDeliveredEvent) GetCourierLocation() *v1.Location {
	if x != nil {
		return x.CourierLocation
	}
	return nil
}

func (x *PackageNotDeliveredEvent) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

// CourierRegisteredEvent - canonical name: delivery.courier.registered.v1
// Event when a new courier is registered
type CourierRegisteredEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Courier ID
	CourierId string `protobuf:"bytes,1,opt,name=courier_id,json=courierId,proto3" json:"courier_id,omitempty"`
	// Courier name
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Courier email
	Email string `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	// Courier phone
	Phone string `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	// Transport type
	TransportType v1.TransportType `protobuf:"varint,5,opt,name=transport_type,json=transportType,proto3,enum=domain.delivery.common.v1.TransportType" json:"transport_type,omitempty"`
	// Courier status
	Status v1.CourierStatus `protobuf:"varint,6,opt,name=status,proto3,enum=domain.delivery.common.v1.CourierStatus" json:"status,omitempty"`
	// Registered at timestamp
	RegisteredAt *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=registered_at,json=registeredAt,proto3" json:"registered_at,omitempty"`
	// OccurredAt is the timestamp when the event occurred
	OccurredAt    *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CourierRegisteredEvent) Reset() {
	*x = CourierRegisteredEvent{}
	mi := &file_domain_delivery_events_v1_events_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CourierRegisteredEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CourierRegisteredEvent) ProtoMessage() {}

func (x *CourierRegisteredEvent) ProtoReflect() protoreflect.Message {
	mi := &file_domain_delivery_events_v1_events_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CourierRegisteredEvent.ProtoReflect.Descriptor instead.
func (*CourierRegisteredEvent) Descriptor() ([]byte, []int) {
	return file_domain_delivery_events_v1_events_proto_rawDescGZIP(), []int{5}
}

func (x *CourierRegisteredEvent) GetCourierId() string {
	if x != nil {
		return x.CourierId
	}
	return ""
}

func (x *CourierRegisteredEvent) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CourierRegisteredEvent) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CourierRegisteredEvent) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *CourierRegisteredEvent) GetTransportType() v1.TransportType {
	if x != nil {
		return x.TransportType
	}
	return v1.TransportType(0)
}

func (x *CourierRegisteredEvent) GetStatus() v1.CourierStatus {
	if x != nil {
		return x.Status
	}
	return v1.CourierStatus(0)
}

func (x *CourierRegisteredEvent) GetRegisteredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RegisteredAt
	}
	return nil
}

func (x *CourierRegisteredEvent) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

// CourierLocationUpdatedEvent - canonical name: delivery.courier.location_updated.v1
// Event when courier location is updated
type CourierLocationUpdatedEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Courier ID
	CourierId string `protobuf:"bytes,1,opt,name=courier_id,json=courierId,proto3" json:"courier_id,omitempty"`
	// Courier location
	Location *v1.Location `protobuf:"bytes,2,opt,name=location,proto3" json:"location,omitempty"`
	// Updated at timestamp
	UpdatedAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// OccurredAt is the timestamp when the event occurred
	OccurredAt    *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CourierLocationUpdatedEvent) Reset() {
	*x = CourierLocationUpdatedEvent{}
	mi := &file_domain_delivery_events_v1_events_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CourierLocationUpdatedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CourierLocationUpdatedEvent) ProtoMessage() {}

func (x *CourierLocationUpdatedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_domain_delivery_events_v1_events_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CourierLocationUpdatedEvent.ProtoReflect.Descriptor instead.
func (*CourierLocationUpdatedEvent) Descriptor() ([]byte, []int) {
	return file_domain_delivery_events_v1_events_proto_rawDescGZIP(), []int{6}
}

func (x *CourierLocationUpdatedEvent) GetCourierId() string {
	if x != nil {
		return x.CourierId
	}
	return ""
}

func (x *CourierLocationUpdatedEvent) GetLocation() *v1.Location {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *CourierLocationUpdatedEvent) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *CourierLocationUpdatedEvent) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

// CourierStatusChangedEvent - canonical name: delivery.courier.status_changed.v1
// Event when courier status changes
type CourierStatusChangedEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Courier ID
	CourierId string `protobuf:"bytes,1,opt,name=courier_id,json=courierId,proto3" json:"courier_id,omitempty"`
	// Old status
	OldStatus v1.CourierStatus `protobuf:"varint,2,opt,name=old_status,json=oldStatus,proto3,enum=domain.delivery.common.v1.CourierStatus" json:"old_status,omitempty"`
	// New status
	NewStatus v1.CourierStatus `protobuf:"varint,3,opt,name=new_status,json=newStatus,proto3,enum=domain.delivery.common.v1.CourierStatus" json:"new_status,omitempty"`
	// Changed at timestamp
	ChangedAt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=changed_at,json=changedAt,proto3" json:"changed_at,omitempty"`
	// Optional reason for status change
	Reason string `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"`
	// OccurredAt is the timestamp when the event occurred
	OccurredAt    *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CourierStatusChangedEvent) Reset() {
	*x = CourierStatusChangedEvent{}
	mi := &file_domain_delivery_events_v1_events_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CourierStatusChangedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CourierStatusChangedEvent) ProtoMessage() {}

func (x *CourierStatusChangedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_domain_delivery_events_v1_events_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CourierStatusChangedEvent.ProtoReflect.Descriptor instead.
func (*CourierStatusChangedEvent) Descriptor() ([]byte, []int) {
	return file_domain_delivery_events_v1_events_proto_rawDescGZIP(), []int{7}
}

func (x *CourierStatusChangedEvent) GetCourierId() string {
	if x != nil {
		return x.CourierId
	}
	return ""
}

func (x *CourierStatusChangedEvent) GetOldStatus() v1.CourierStatus {
	if x != nil {
		return x.OldStatus
	}
	return v1.CourierStatus(0)
}

func (x *CourierStatusChangedEvent) GetNewStatus() v1.CourierStatus {
	if x != nil {
		return x.NewStatus
	}
	return v1.CourierStatus(0)
}

func (x *CourierStatusChangedEvent) GetChangedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ChangedAt
	}
	return nil
}

func (x *CourierStatusChangedEvent) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *CourierStatusChangedEvent) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

// PackageRequiresHandlingEvent - canonical name: delivery.package.requires_handling.v1
// Event when package requires manual handling
type PackageRequiresHandlingEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Package ID
	PackageId string `protobuf:"bytes,1,opt,name=package_id,json=packageId,proto3" json:"package_id,omitempty"`
	// Order ID
	OrderId string `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	// Package status
	Status v1.PackageStatus `protobuf:"varint,3,opt,name=status,proto3,enum=domain.delivery.common.v1.PackageStatus" json:"status,omitempty"`
	// Reason for manual handling
	Reason string `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	// Requires handling at timestamp
	RequiresHandlingAt *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=requires_handling_at,json=requiresHandlingAt,proto3" json:"requires_handling_at,omitempty"`
	// OccurredAt is the timestamp when the event occurred
	OccurredAt    *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PackageRequiresHandlingEvent) Reset() {
	*x = PackageRequiresHandlingEvent{}
	mi := &file_domain_delivery_events_v1_events_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PackageRequiresHandlingEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PackageRequiresHandlingEvent) ProtoMessage() {}

func (x *PackageRequiresHandlingEvent) ProtoReflect() protoreflect.Message {
	mi := &file_domain_delivery_events_v1_events_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PackageRequiresHandlingEvent.ProtoReflect.Descriptor instead.
func (*PackageRequiresHandlingEvent) Descriptor() ([]byte, []int) {
	return file_domain_delivery_events_v1_events_proto_rawDescGZIP(), []int{8}
}

func (x *PackageRequiresHandlingEvent) GetPackageId() string {
	if x != nil {
		return x.PackageId
	}
	return ""
}

func (x *PackageRequiresHandlingEvent) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *PackageRequiresHandlingEvent) GetStatus() v1.PackageStatus {
	if x != nil {
		return x.Status
	}
	return v1.PackageStatus(0)
}

func (x *PackageRequiresHandlingEvent) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *PackageRequiresHandlingEvent) GetRequiresHandlingAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RequiresHandlingAt
	}
	return nil
}

func (x *PackageRequiresHandlingEvent) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

var File_domain_delivery_events_v1_events_proto protoreflect.FileDescriptor

const file_domain_delivery_events_v1_events_proto_rawDesc = "" +
	"\n" +
	"&domain/delivery/events/v1/events.proto\x12\x19domain.delivery.events.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a&domain/delivery/common/v1/common.proto\"\xab\x02\n" +
	"\x14PackageAcceptedEvent\x12\x1d\n" +
	"\n" +
	"package_id\x18\x01 \x01(\tR\tpackageId\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\x12\x1f\n" +
	"\vcustomer_id\x18\x03 \x01(\tR\n" +
	"customerId\x12@\n" +
	"\x06status\x18\x04 \x01(\x0e2(.domain.delivery.common.v1.PackageStatusR\x06status\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12;\n" +
	"\voccurred_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt\"\xa5\x04\n" +
	"\x14PackageAssignedEvent\x12\x1d\n" +
	"\n" +
	"package_id\x18\x01 \x01(\tR\tpackageId\x12\x1d\n" +
	"\n" +
	"courier_id\x18\x02 \x01(\tR\tcourierId\x12@\n" +
	"\x06status\x18\x03 \x01(\x0e2(.domain.delivery.common.v1.PackageStatusR\x06status\x12;\n" +
	"\vassigned_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"assignedAt\x12I\n" +
	"\x0epickup_address\x18\x05 \x01(\v2\".domain.delivery.common.v1.AddressR\rpickupAddress\x12M\n" +
	"\x10delivery_address\x18\x06 \x01(\v2\".domain.delivery.common.v1.AddressR\x0fdeliveryAddress\x12R\n" +
	"\x0fdelivery_period\x18\a \x01(\v2).domain.delivery.common.v1.DeliveryPeriodR\x0edeliveryPeriod\x12%\n" +
	"\x0ecustomer_phone\x18\b \x01(\tR\rcustomerPhone\x12;\n" +
	"\voccurred_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt\"\xff\x02\n" +
	"\x15PackageInTransitEvent\x12\x1d\n" +
	"\n" +
	"package_id\x18\x01 \x01(\tR\tpackageId\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\x12\x1d\n" +
	"\n" +
	"courier_id\x18\x03 \x01(\tR\tcourierId\x12@\n" +
	"\x06status\x18\x04 \x01(\x0e2(.domain.delivery.common.v1.PackageStatusR\x06status\x12>\n" +
	"\rin_transit_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\vinTransitAt\x12N\n" +
	"\x10courier_location\x18\x06 \x01(\v2#.domain.delivery.common.v1.LocationR\x0fcourierLocation\x12;\n" +
	"\voccurred_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt\"\xc5\x03\n" +
	"\x15PackageDeliveredEvent\x12\x1d\n" +
	"\n" +
	"package_id\x18\x01 \x01(\tR\tpackageId\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\x12\x1d\n" +
	"\n" +
	"courier_id\x18\x03 \x01(\tR\tcourierId\x12@\n" +
	"\x06status\x18\x04 \x01(\x0e2(.domain.delivery.common.v1.PackageStatusR\x06status\x12=\n" +
	"\fdelivered_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\vdeliveredAt\x12P\n" +
	"\x11delivery_location\x18\x06 \x01(\v2#.domain.delivery.common.v1.LocationR\x10deliveryLocation\x12\x14\n" +
	"\x05photo\x18\a \x01(\fR\x05photo\x12-\n" +
	"\x12customer_signature\x18\b \x01(\fR\x11customerSignature\x12;\n" +
	"\voccurred_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt\"\xfe\x03\n" +
	"\x18PackageNotDeliveredEvent\x12\x1d\n" +
	"\n" +
	"package_id\x18\x01 \x01(\tR\tpackageId\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\x12\x1d\n" +
	"\n" +
	"courier_id\x18\x03 \x01(\tR\tcourierId\x12@\n" +
	"\x06status\x18\x04 \x01(\x0e2(.domain.delivery.common.v1.PackageStatusR\x06status\x12E\n" +
	"\x06reason\x18\x05 \x01(\x0e2-.domain.delivery.common.v1.NotDeliveredReasonR\x06reason\x12-\n" +
	"\x12reason_description\x18\x06 \x01(\tR\x11reasonDescription\x12D\n" +
	"\x10not_delivered_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\x0enotDeliveredAt\x12N\n" +
	"\x10courier_location\x18\b \x01(\v2#.domain.delivery.common.v1.LocationR\x0fcourierLocation\x12;\n" +
	"\voccurred_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt\"\x88\x03\n" +
	"\x16CourierRegisteredEvent\x12\x1d\n" +
	"\n" +
	"courier_id\x18\x01 \x01(\tR\tcourierId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\x04 \x01(\tR\x05phone\x12O\n" +
	"\x0etransport_type\x18\x05 \x01(\x0e2(.domain.delivery.common.v1.TransportTypeR\rtransportType\x12@\n" +
	"\x06status\x18\x06 \x01(\x0e2(.domain.delivery.common.v1.CourierStatusR\x06status\x12?\n" +
	"\rregistered_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\fregisteredAt\x12;\n" +
	"\voccurred_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt\"\xf5\x01\n" +
	"\x1bCourierLocationUpdatedEvent\x12\x1d\n" +
	"\n" +
	"courier_id\x18\x01 \x01(\tR\tcourierId\x12?\n" +
	"\blocation\x18\x02 \x01(\v2#.domain.delivery.common.v1.LocationR\blocation\x129\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12;\n" +
	"\voccurred_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt\"\xdc\x02\n" +
	"\x19CourierStatusChangedEvent\x12\x1d\n" +
	"\n" +
	"courier_id\x18\x01 \x01(\tR\tcourierId\x12G\n" +
	"\n" +
	"old_status\x18\x02 \x01(\x0e2(.domain.delivery.common.v1.CourierStatusR\toldStatus\x12G\n" +
	"\n" +
	"new_status\x18\x03 \x01(\x0e2(.domain.delivery.common.v1.CourierStatusR\tnewStatus\x129\n" +
	"\n" +
	"changed_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tchangedAt\x12\x16\n" +
	"\x06reason\x18\x05 \x01(\tR\x06reason\x12;\n" +
	"\voccurred_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt\"\xbd\x02\n" +
	"\x1cPackageRequiresHandlingEvent\x12\x1d\n" +
	"\n" +
	"package_id\x18\x01 \x01(\tR\tpackageId\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\x12@\n" +
	"\x06status\x18\x03 \x01(\x0e2(.domain.delivery.common.v1.PackageStatusR\x06status\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\x12L\n" +
	"\x14requires_handling_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x12requiresHandlingAt\x12;\n" +
	"\voccurred_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAtB\xf9\x01\n" +
	"\x1dcom.domain.delivery.events.v1B\vEventsProtoP\x01ZDgithub.com/shortlink-org/shop/oms/internal/domain/delivery/events/v1\xa2\x02\x03DDE\xaa\x02\x19Domain.Delivery.Events.V1\xca\x02\x19Domain\\Delivery\\Events\\V1\xe2\x02%Domain\\Delivery\\Events\\V1\\GPBMetadata\xea\x02\x1cDomain::Delivery::Events::V1b\x06proto3"

var (
	file_domain_delivery_events_v1_events_proto_rawDescOnce sync.Once
	file_domain_delivery_events_v1_events_proto_rawDescData []byte
)

func file_domain_delivery_events_v1_events_proto_rawDescGZIP() []byte {
	file_domain_delivery_events_v1_events_proto_rawDescOnce.Do(func() {
		file_domain_delivery_events_v1_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_domain_delivery_events_v1_events_proto_rawDesc), len(file_domain_delivery_events_v1_events_proto_rawDesc)))
	})
	return file_domain_delivery_events_v1_events_proto_rawDescData
}

var file_domain_delivery_events_v1_events_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_domain_delivery_events_v1_events_proto_goTypes = []any{
	(*PackageAcceptedEvent)(nil),         // 0: domain.delivery.events.v1.PackageAcceptedEvent
	(*PackageAssignedEvent)(nil),         // 1: domain.delivery.events.v1.PackageAssignedEvent
	(*PackageInTransitEvent)(nil),        // 2: domain.delivery.events.v1.PackageInTransitEvent
	(*PackageDeliveredEvent)(nil),        // 3: domain.delivery.events.v1.PackageDeliveredEvent
	(*PackageNotDeliveredEvent)(nil),     // 4: domain.delivery.events.v1.PackageNotDeliveredEvent
	(*CourierRegisteredEvent)(nil),       // 5: domain.delivery.events.v1.CourierRegisteredEvent
	(*CourierLocationUpdatedEvent)(nil),  // 6: domain.delivery.events.v1.CourierLocationUpdatedEvent
	(*CourierStatusChangedEvent)(nil),    // 7: domain.delivery.events.v1.CourierStatusChangedEvent
	(*PackageRequiresHandlingEvent)(nil), // 8: domain.delivery.events.v1.PackageRequiresHandlingEvent
	(v1.PackageStatus)(0),                // 9: domain.delivery.common.v1.PackageStatus
	(*timestamppb.Timestamp)(nil),        // 10: google.protobuf.Timestamp
	(*v1.Address)(nil),                   // 11: domain.delivery.common.v1.Address
	(*v1.DeliveryPeriod)(nil),            // 12: domain.delivery.common.v1.DeliveryPeriod
	(*v1.Location)(nil),                  // 13: domain.delivery.common.v1.Location
	(v1.NotDeliveredReason)(0),           // 14: domain.delivery.common.v1.NotDeliveredReason
	(v1.TransportType)(0),                // 15: domain.delivery.common.v1.TransportType
	(v1.CourierStatus)(0),                // 16: domain.delivery.common.v1.CourierStatus
}
var file_domain_delivery_events_v1_events_proto_depIdxs = []int32{
	9,  // 0: domain.delivery.events.v1.PackageAcceptedEvent.status:type_name -> domain.delivery.common.v1.PackageStatus
	10, // 1: domain.delivery.events.v1.PackageAcceptedEvent.created_at:type_name -> google.protobuf.Timestamp
	10, // 2: domain.delivery.events.v1.PackageAcceptedEvent.occurred_at:type_name -> google.protobuf.Timestamp
	9,  // 3: domain.delivery.events.v1.PackageAssignedEvent.status:type_name -> domain.delivery.common.v1.PackageStatus
	10, // 4: domain.delivery.events.v1.PackageAssignedEvent.assigned_at:type_name -> google.protobuf.Timestamp
	11, // 5: domain.delivery.events.v1.PackageAssignedEvent.pickup_address:type_name -> domain.delivery.common.v1.Address
	11, // 6: domain.delivery.events.v1.PackageAssignedEvent.delivery_address:type_name -> domain.delivery.common.v1.Address
	12, // 7: domain.delivery.events.v1.PackageAssignedEvent.delivery_period:type_name -> domain.delivery.common.v1.DeliveryPeriod
	10, // 8: domain.delivery.events.v1.PackageAssignedEvent.occurred_at:type_name -> google.protobuf.Timestamp
	9,  // 9: domain.delivery.events.v1.PackageInTransitEvent.status:type_name -> domain.delivery.common.v1.PackageStatus
	10, // 10: domain.delivery.events.v1.PackageInTransitEvent.in_transit_at:type_name -> google.protobuf.Timestamp
	13, // 11: domain.delivery.events.v1.PackageInTransitEvent.courier_location:type_name -> domain.delivery.common.v1.Location
	10, // 12: domain.delivery.events.v1.PackageInTransitEvent.occurred_at:type_name -> google.protobuf.Timestamp
	9,  // 13: domain.delivery.events.v1.PackageDeliveredEvent.status:type_name -> domain.delivery.common.v1.PackageStatus
	10, // 14: domain.delivery.events.v1.PackageDeliveredEvent.delivered_at:type_name -> google.protobuf.Timestamp
	13, // 15: domain.delivery.events.v1.PackageDeliveredEvent.delivery_location:type_name -> domain.delivery.common.v1.Location
	10, // 16: domain.delivery.events.v1.PackageDeliveredEvent.occurred_at:type_name -> google.protobuf.Timestamp
	9,  // 17: domain.delivery.events.v1.PackageNotDeliveredEvent.status:type_name -> domain.delivery.common.v1.PackageStatus
	14, // 18: domain.delivery.events.v1.PackageNotDeliveredEvent.reason:type_name -> domain.delivery.common.v1.NotDeliveredReason
	10, // 19: domain.delivery.events.v1.PackageNotDeliveredEvent.not_delivered_at:type_name -> google.protobuf.Timestamp
	13, // 20: domain.delivery.events.v1.PackageNotDeliveredEvent.courier_location:type_name -> domain.delivery.common.v1.Location
	10, // 21: domain.delivery.events.v1.PackageNotDeliveredEvent.occurred_at:type_name -> google.protobuf.Timestamp
	15, // 22: domain.delivery.events.v1.CourierRegisteredEvent.transport_type:type_name -> domain.delivery.common.v1.TransportType
	16, // 23: domain.delivery.events.v1.CourierRegisteredEvent.status:type_name -> domain.delivery.common.v1.CourierStatus
	10, // 24: domain.delivery.events.v1.CourierRegisteredEvent.registered_at:type_name -> google.protobuf.Timestamp
	10, // 25: domain.delivery.events.v1.CourierRegisteredEvent.occurred_at:type_name -> google.protobuf.Timestamp
	13, // 26: domain.delivery.events.v1.CourierLocationUpdatedEvent.location:type_name -> domain.delivery.common.v1.Location
	10, // 27: domain.delivery.events.v1.CourierLocationUpdatedEvent.updated_at:type_name -> google.protobuf.Timestamp
	10, // 28: domain.delivery.events.v1.CourierLocationUpdatedEvent.occurred_at:type_name -> google.protobuf.Timestamp
	16, // 29: domain.delivery.events.v1.CourierStatusChangedEvent.old_status:type_name -> domain.delivery.common.v1.CourierStatus
	16, // 30: domain.delivery.events.v1.CourierStatusChangedEvent.new_status:type_name -> domain.delivery.common.v1.CourierStatus
	10, // 31: domain.delivery.events.v1.CourierStatusChangedEvent.changed_at:type_name -> google.protobuf.Timestamp
	10, // 32: domain.delivery.events.v1.CourierStatusChangedEvent.occurred_at:type_name -> google.protobuf.Timestamp
	9,  // 33: domain.delivery.events.v1.PackageRequiresHandlingEvent.status:type_name -> domain.delivery.common.v1.PackageStatus
	10, // 34: domain.delivery.events.v1.PackageRequiresHandlingEvent.requires_handling_at:type_name -> google.protobuf.Timestamp
	10, // 35: domain.delivery.events.v1.PackageRequiresHandlingEvent.occurred_at:type_name -> google.protobuf.Timestamp
	36, // [36:36] is the sub-list for method output_type
	36, // [36:36] is the sub-list for method input_type
	36, // [36:36] is the sub-list for extension type_name
	36, // [36:36] is the sub-list for extension extendee
	0,  // [0:36] is the sub-list for field type_name
}

func init() { file_domain_delivery_events_v1_events_proto_init() }
func file_domain_delivery_events_v1_events_proto_init() {
	if File_domain_delivery_events_v1_events_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_domain_delivery_events_v1_events_proto_rawDesc), len(file_domain_delivery_events_v1_events_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_domain_delivery_events_v1_events_proto_goTypes,
		DependencyIndexes: file_domain_delivery_events_v1_events_proto_depIdxs,
		MessageInfos:      file_domain_delivery_events_v1_events_proto_msgTypes,
	}.Build()
	File_domain_delivery_events_v1_events_proto = out.File
	file_domain_delivery_events_v1_events_proto_goTypes = nil
	file_domain_delivery_events_v1_events_proto_depIdxs = nil
}
