{{- if .Values.store.cassandra.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: shop-cassandra-fixed-credentials
  namespace: {{ .Values.store.cassandra.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
type: Opaque
stringData:
  username: shop-cassandra-superuser
  password: {{ .Values.store.credentials.cassandraSuperuserPassword | quote }}
{{- end }}
