// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: domain/order/v1/events/v1/events.proto

package v1

import (
	v1 "github.com/shortlink-org/shortlink/boundaries/shop/oms/internal/domain/order/v1/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// OrderCreated event - canonical name: oms.order.created.v1
// Published when a new order is created
// Delivery information (if needed) should be handled separately by Delivery Service
type OrderCreated struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Order ID
	OrderId string `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	// Customer ID
	CustomerId string `protobuf:"bytes,2,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	// Order items
	Items []*v1.OrderItem `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	// Order status
	Status v1.OrderStatus `protobuf:"varint,4,opt,name=status,proto3,enum=domain.order.common.v1.OrderStatus" json:"status,omitempty"`
	// Created at timestamp
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// OccurredAt is the timestamp when the event occurred
	OccurredAt    *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderCreated) Reset() {
	*x = OrderCreated{}
	mi := &file_domain_order_v1_events_v1_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderCreated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderCreated) ProtoMessage() {}

func (x *OrderCreated) ProtoReflect() protoreflect.Message {
	mi := &file_domain_order_v1_events_v1_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderCreated.ProtoReflect.Descriptor instead.
func (*OrderCreated) Descriptor() ([]byte, []int) {
	return file_domain_order_v1_events_v1_events_proto_rawDescGZIP(), []int{0}
}

func (x *OrderCreated) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *OrderCreated) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *OrderCreated) GetItems() []*v1.OrderItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *OrderCreated) GetStatus() v1.OrderStatus {
	if x != nil {
		return x.Status
	}
	return v1.OrderStatus(0)
}

func (x *OrderCreated) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *OrderCreated) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

// OrderCancelled event - canonical name: oms.order.cancelled.v1
// Published when an order is cancelled
type OrderCancelled struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Order ID
	OrderId string `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	// Customer ID
	CustomerId string `protobuf:"bytes,2,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	// Order status
	Status v1.OrderStatus `protobuf:"varint,3,opt,name=status,proto3,enum=domain.order.common.v1.OrderStatus" json:"status,omitempty"`
	// Cancellation reason (optional)
	Reason string `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	// Cancelled at timestamp
	CancelledAt *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=cancelled_at,json=cancelledAt,proto3" json:"cancelled_at,omitempty"`
	// OccurredAt is the timestamp when the event occurred
	OccurredAt    *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderCancelled) Reset() {
	*x = OrderCancelled{}
	mi := &file_domain_order_v1_events_v1_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderCancelled) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderCancelled) ProtoMessage() {}

func (x *OrderCancelled) ProtoReflect() protoreflect.Message {
	mi := &file_domain_order_v1_events_v1_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderCancelled.ProtoReflect.Descriptor instead.
func (*OrderCancelled) Descriptor() ([]byte, []int) {
	return file_domain_order_v1_events_v1_events_proto_rawDescGZIP(), []int{1}
}

func (x *OrderCancelled) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *OrderCancelled) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *OrderCancelled) GetStatus() v1.OrderStatus {
	if x != nil {
		return x.Status
	}
	return v1.OrderStatus(0)
}

func (x *OrderCancelled) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *OrderCancelled) GetCancelledAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CancelledAt
	}
	return nil
}

func (x *OrderCancelled) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

// OrderCompleted event - canonical name: oms.order.completed.v1
// Published when an order is completed
type OrderCompleted struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Order ID
	OrderId string `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	// Customer ID
	CustomerId string `protobuf:"bytes,2,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	// Order status
	Status v1.OrderStatus `protobuf:"varint,3,opt,name=status,proto3,enum=domain.order.common.v1.OrderStatus" json:"status,omitempty"`
	// Completed at timestamp
	CompletedAt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	// OccurredAt is the timestamp when the event occurred
	OccurredAt    *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderCompleted) Reset() {
	*x = OrderCompleted{}
	mi := &file_domain_order_v1_events_v1_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderCompleted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderCompleted) ProtoMessage() {}

func (x *OrderCompleted) ProtoReflect() protoreflect.Message {
	mi := &file_domain_order_v1_events_v1_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderCompleted.ProtoReflect.Descriptor instead.
func (*OrderCompleted) Descriptor() ([]byte, []int) {
	return file_domain_order_v1_events_v1_events_proto_rawDescGZIP(), []int{2}
}

func (x *OrderCompleted) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *OrderCompleted) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *OrderCompleted) GetStatus() v1.OrderStatus {
	if x != nil {
		return x.Status
	}
	return v1.OrderStatus(0)
}

func (x *OrderCompleted) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

func (x *OrderCompleted) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

// OrderDeliveryRequestedEvent - canonical name: oms.order.delivery_requested.v1
// Event when order is created with delivery info
// This event is published to delivery service to request package acceptance
type OrderDeliveryRequestedEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Order ID
	OrderId string `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	// Customer ID
	CustomerId string `protobuf:"bytes,2,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	// Pickup address
	PickupAddress *v1.DeliveryAddress `protobuf:"bytes,3,opt,name=pickup_address,json=pickupAddress,proto3" json:"pickup_address,omitempty"`
	// Delivery address
	DeliveryAddress *v1.DeliveryAddress `protobuf:"bytes,4,opt,name=delivery_address,json=deliveryAddress,proto3" json:"delivery_address,omitempty"`
	// Delivery period
	DeliveryPeriod *v1.DeliveryPeriod `protobuf:"bytes,5,opt,name=delivery_period,json=deliveryPeriod,proto3" json:"delivery_period,omitempty"`
	// Package info
	PackageInfo *v1.PackageInfo `protobuf:"bytes,6,opt,name=package_info,json=packageInfo,proto3" json:"package_info,omitempty"`
	// Priority
	Priority v1.DeliveryPriority `protobuf:"varint,7,opt,name=priority,proto3,enum=domain.order.common.v1.DeliveryPriority" json:"priority,omitempty"`
	// Timestamp when event was created
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// OccurredAt is the timestamp when the event occurred
	OccurredAt    *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderDeliveryRequestedEvent) Reset() {
	*x = OrderDeliveryRequestedEvent{}
	mi := &file_domain_order_v1_events_v1_events_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderDeliveryRequestedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderDeliveryRequestedEvent) ProtoMessage() {}

func (x *OrderDeliveryRequestedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_domain_order_v1_events_v1_events_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderDeliveryRequestedEvent.ProtoReflect.Descriptor instead.
func (*OrderDeliveryRequestedEvent) Descriptor() ([]byte, []int) {
	return file_domain_order_v1_events_v1_events_proto_rawDescGZIP(), []int{3}
}

func (x *OrderDeliveryRequestedEvent) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *OrderDeliveryRequestedEvent) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *OrderDeliveryRequestedEvent) GetPickupAddress() *v1.DeliveryAddress {
	if x != nil {
		return x.PickupAddress
	}
	return nil
}

func (x *OrderDeliveryRequestedEvent) GetDeliveryAddress() *v1.DeliveryAddress {
	if x != nil {
		return x.DeliveryAddress
	}
	return nil
}

func (x *OrderDeliveryRequestedEvent) GetDeliveryPeriod() *v1.DeliveryPeriod {
	if x != nil {
		return x.DeliveryPeriod
	}
	return nil
}

func (x *OrderDeliveryRequestedEvent) GetPackageInfo() *v1.PackageInfo {
	if x != nil {
		return x.PackageInfo
	}
	return nil
}

func (x *OrderDeliveryRequestedEvent) GetPriority() v1.DeliveryPriority {
	if x != nil {
		return x.Priority
	}
	return v1.DeliveryPriority(0)
}

func (x *OrderDeliveryRequestedEvent) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *OrderDeliveryRequestedEvent) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

// OrderDeliveryStatusUpdatedEvent - canonical name: oms.order.delivery_status_updated.v1
// Event when delivery status is updated
// This event is received from delivery service
type OrderDeliveryStatusUpdatedEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Order ID
	OrderId string `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	// Package ID assigned by delivery service
	PackageId string `protobuf:"bytes,2,opt,name=package_id,json=packageId,proto3" json:"package_id,omitempty"`
	// Delivery status
	Status v1.DeliveryStatus `protobuf:"varint,3,opt,name=status,proto3,enum=domain.order.common.v1.DeliveryStatus" json:"status,omitempty"`
	// Timestamp when status was updated
	UpdatedAt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// Optional: courier ID if assigned
	CourierId string `protobuf:"bytes,5,opt,name=courier_id,json=courierId,proto3" json:"courier_id,omitempty"`
	// OccurredAt is the timestamp when the event occurred
	OccurredAt    *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderDeliveryStatusUpdatedEvent) Reset() {
	*x = OrderDeliveryStatusUpdatedEvent{}
	mi := &file_domain_order_v1_events_v1_events_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderDeliveryStatusUpdatedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderDeliveryStatusUpdatedEvent) ProtoMessage() {}

func (x *OrderDeliveryStatusUpdatedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_domain_order_v1_events_v1_events_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderDeliveryStatusUpdatedEvent.ProtoReflect.Descriptor instead.
func (*OrderDeliveryStatusUpdatedEvent) Descriptor() ([]byte, []int) {
	return file_domain_order_v1_events_v1_events_proto_rawDescGZIP(), []int{4}
}

func (x *OrderDeliveryStatusUpdatedEvent) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *OrderDeliveryStatusUpdatedEvent) GetPackageId() string {
	if x != nil {
		return x.PackageId
	}
	return ""
}

func (x *OrderDeliveryStatusUpdatedEvent) GetStatus() v1.DeliveryStatus {
	if x != nil {
		return x.Status
	}
	return v1.DeliveryStatus(0)
}

func (x *OrderDeliveryStatusUpdatedEvent) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *OrderDeliveryStatusUpdatedEvent) GetCourierId() string {
	if x != nil {
		return x.CourierId
	}
	return ""
}

func (x *OrderDeliveryStatusUpdatedEvent) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

// OrderDeliveryCompletedEvent - canonical name: oms.order.delivery_completed.v1
// Event when delivery is completed
// This event is received from delivery service
type OrderDeliveryCompletedEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Order ID
	OrderId string `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	// Package ID
	PackageId string `protobuf:"bytes,2,opt,name=package_id,json=packageId,proto3" json:"package_id,omitempty"`
	// Courier ID
	CourierId string `protobuf:"bytes,3,opt,name=courier_id,json=courierId,proto3" json:"courier_id,omitempty"`
	// Timestamp when delivery was completed
	DeliveredAt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=delivered_at,json=deliveredAt,proto3" json:"delivered_at,omitempty"`
	// Delivery location
	DeliveryLocation *v1.DeliveryLocation `protobuf:"bytes,5,opt,name=delivery_location,json=deliveryLocation,proto3" json:"delivery_location,omitempty"`
	// OccurredAt is the timestamp when the event occurred
	OccurredAt    *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderDeliveryCompletedEvent) Reset() {
	*x = OrderDeliveryCompletedEvent{}
	mi := &file_domain_order_v1_events_v1_events_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderDeliveryCompletedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderDeliveryCompletedEvent) ProtoMessage() {}

func (x *OrderDeliveryCompletedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_domain_order_v1_events_v1_events_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderDeliveryCompletedEvent.ProtoReflect.Descriptor instead.
func (*OrderDeliveryCompletedEvent) Descriptor() ([]byte, []int) {
	return file_domain_order_v1_events_v1_events_proto_rawDescGZIP(), []int{5}
}

func (x *OrderDeliveryCompletedEvent) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *OrderDeliveryCompletedEvent) GetPackageId() string {
	if x != nil {
		return x.PackageId
	}
	return ""
}

func (x *OrderDeliveryCompletedEvent) GetCourierId() string {
	if x != nil {
		return x.CourierId
	}
	return ""
}

func (x *OrderDeliveryCompletedEvent) GetDeliveredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeliveredAt
	}
	return nil
}

func (x *OrderDeliveryCompletedEvent) GetDeliveryLocation() *v1.DeliveryLocation {
	if x != nil {
		return x.DeliveryLocation
	}
	return nil
}

func (x *OrderDeliveryCompletedEvent) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

// OrderDeliveryFailedEvent - canonical name: oms.order.delivery_failed.v1
// Event when delivery failed
// This event is received from delivery service
type OrderDeliveryFailedEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Order ID
	OrderId string `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	// Package ID
	PackageId string `protobuf:"bytes,2,opt,name=package_id,json=packageId,proto3" json:"package_id,omitempty"`
	// Courier ID
	CourierId string `protobuf:"bytes,3,opt,name=courier_id,json=courierId,proto3" json:"courier_id,omitempty"`
	// Reason for failure
	Reason v1.NotDeliveredReason `protobuf:"varint,4,opt,name=reason,proto3,enum=domain.order.common.v1.NotDeliveredReason" json:"reason,omitempty"`
	// Timestamp when delivery failed
	FailedAt *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=failed_at,json=failedAt,proto3" json:"failed_at,omitempty"`
	// Optional: failure description
	Description string `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	// OccurredAt is the timestamp when the event occurred
	OccurredAt    *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderDeliveryFailedEvent) Reset() {
	*x = OrderDeliveryFailedEvent{}
	mi := &file_domain_order_v1_events_v1_events_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderDeliveryFailedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderDeliveryFailedEvent) ProtoMessage() {}

func (x *OrderDeliveryFailedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_domain_order_v1_events_v1_events_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderDeliveryFailedEvent.ProtoReflect.Descriptor instead.
func (*OrderDeliveryFailedEvent) Descriptor() ([]byte, []int) {
	return file_domain_order_v1_events_v1_events_proto_rawDescGZIP(), []int{6}
}

func (x *OrderDeliveryFailedEvent) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *OrderDeliveryFailedEvent) GetPackageId() string {
	if x != nil {
		return x.PackageId
	}
	return ""
}

func (x *OrderDeliveryFailedEvent) GetCourierId() string {
	if x != nil {
		return x.CourierId
	}
	return ""
}

func (x *OrderDeliveryFailedEvent) GetReason() v1.NotDeliveredReason {
	if x != nil {
		return x.Reason
	}
	return v1.NotDeliveredReason(0)
}

func (x *OrderDeliveryFailedEvent) GetFailedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FailedAt
	}
	return nil
}

func (x *OrderDeliveryFailedEvent) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *OrderDeliveryFailedEvent) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

var File_domain_order_v1_events_v1_events_proto protoreflect.FileDescriptor

const file_domain_order_v1_events_v1_events_proto_rawDesc = "" +
	"\n" +
	"&domain/order/v1/events/v1/events.proto\x12\x16domain.order.events.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a&domain/order/v1/common/v1/common.proto\"\xb8\x02\n" +
	"\fOrderCreated\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x1f\n" +
	"\vcustomer_id\x18\x02 \x01(\tR\n" +
	"customerId\x127\n" +
	"\x05items\x18\x03 \x03(\v2!.domain.order.common.v1.OrderItemR\x05items\x12;\n" +
	"\x06status\x18\x04 \x01(\x0e2#.domain.order.common.v1.OrderStatusR\x06status\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12;\n" +
	"\voccurred_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt\"\x9d\x02\n" +
	"\x0eOrderCancelled\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x1f\n" +
	"\vcustomer_id\x18\x02 \x01(\tR\n" +
	"customerId\x12;\n" +
	"\x06status\x18\x03 \x01(\x0e2#.domain.order.common.v1.OrderStatusR\x06status\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\x12=\n" +
	"\fcancelled_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\vcancelledAt\x12;\n" +
	"\voccurred_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt\"\x85\x02\n" +
	"\x0eOrderCompleted\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x1f\n" +
	"\vcustomer_id\x18\x02 \x01(\tR\n" +
	"customerId\x12;\n" +
	"\x06status\x18\x03 \x01(\x0e2#.domain.order.common.v1.OrderStatusR\x06status\x12=\n" +
	"\fcompleted_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt\x12;\n" +
	"\voccurred_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt\"\xd4\x04\n" +
	"\x1bOrderDeliveryRequestedEvent\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x1f\n" +
	"\vcustomer_id\x18\x02 \x01(\tR\n" +
	"customerId\x12N\n" +
	"\x0epickup_address\x18\x03 \x01(\v2'.domain.order.common.v1.DeliveryAddressR\rpickupAddress\x12R\n" +
	"\x10delivery_address\x18\x04 \x01(\v2'.domain.order.common.v1.DeliveryAddressR\x0fdeliveryAddress\x12O\n" +
	"\x0fdelivery_period\x18\x05 \x01(\v2&.domain.order.common.v1.DeliveryPeriodR\x0edeliveryPeriod\x12F\n" +
	"\fpackage_info\x18\x06 \x01(\v2#.domain.order.common.v1.PackageInfoR\vpackageInfo\x12D\n" +
	"\bpriority\x18\a \x01(\x0e2(.domain.order.common.v1.DeliveryPriorityR\bpriority\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12;\n" +
	"\voccurred_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt\"\xb2\x02\n" +
	"\x1fOrderDeliveryStatusUpdatedEvent\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x1d\n" +
	"\n" +
	"package_id\x18\x02 \x01(\tR\tpackageId\x12>\n" +
	"\x06status\x18\x03 \x01(\x0e2&.domain.order.common.v1.DeliveryStatusR\x06status\x129\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x1d\n" +
	"\n" +
	"courier_id\x18\x05 \x01(\tR\tcourierId\x12;\n" +
	"\voccurred_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt\"\xc9\x02\n" +
	"\x1bOrderDeliveryCompletedEvent\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x1d\n" +
	"\n" +
	"package_id\x18\x02 \x01(\tR\tpackageId\x12\x1d\n" +
	"\n" +
	"courier_id\x18\x03 \x01(\tR\tcourierId\x12=\n" +
	"\fdelivered_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\vdeliveredAt\x12U\n" +
	"\x11delivery_location\x18\x05 \x01(\v2(.domain.order.common.v1.DeliveryLocationR\x10deliveryLocation\x12;\n" +
	"\voccurred_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt\"\xcf\x02\n" +
	"\x18OrderDeliveryFailedEvent\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x1d\n" +
	"\n" +
	"package_id\x18\x02 \x01(\tR\tpackageId\x12\x1d\n" +
	"\n" +
	"courier_id\x18\x03 \x01(\tR\tcourierId\x12B\n" +
	"\x06reason\x18\x04 \x01(\x0e2*.domain.order.common.v1.NotDeliveredReasonR\x06reason\x127\n" +
	"\tfailed_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\bfailedAt\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\x12;\n" +
	"\voccurred_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAtB\xff\x01\n" +
	"\x1acom.domain.order.events.v1B\vEventsProtoP\x01ZYgithub.com/shortlink-org/shortlink/boundaries/shop/oms/internal/domain/order/v1/events/v1\xa2\x02\x03DOE\xaa\x02\x16Domain.Order.Events.V1\xca\x02\x16Domain\\Order\\Events\\V1\xe2\x02\"Domain\\Order\\Events\\V1\\GPBMetadata\xea\x02\x19Domain::Order::Events::V1b\x06proto3"

var (
	file_domain_order_v1_events_v1_events_proto_rawDescOnce sync.Once
	file_domain_order_v1_events_v1_events_proto_rawDescData []byte
)

func file_domain_order_v1_events_v1_events_proto_rawDescGZIP() []byte {
	file_domain_order_v1_events_v1_events_proto_rawDescOnce.Do(func() {
		file_domain_order_v1_events_v1_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_domain_order_v1_events_v1_events_proto_rawDesc), len(file_domain_order_v1_events_v1_events_proto_rawDesc)))
	})
	return file_domain_order_v1_events_v1_events_proto_rawDescData
}

var file_domain_order_v1_events_v1_events_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_domain_order_v1_events_v1_events_proto_goTypes = []any{
	(*OrderCreated)(nil),                    // 0: domain.order.events.v1.OrderCreated
	(*OrderCancelled)(nil),                  // 1: domain.order.events.v1.OrderCancelled
	(*OrderCompleted)(nil),                  // 2: domain.order.events.v1.OrderCompleted
	(*OrderDeliveryRequestedEvent)(nil),     // 3: domain.order.events.v1.OrderDeliveryRequestedEvent
	(*OrderDeliveryStatusUpdatedEvent)(nil), // 4: domain.order.events.v1.OrderDeliveryStatusUpdatedEvent
	(*OrderDeliveryCompletedEvent)(nil),     // 5: domain.order.events.v1.OrderDeliveryCompletedEvent
	(*OrderDeliveryFailedEvent)(nil),        // 6: domain.order.events.v1.OrderDeliveryFailedEvent
	(*v1.OrderItem)(nil),                    // 7: domain.order.common.v1.OrderItem
	(v1.OrderStatus)(0),                     // 8: domain.order.common.v1.OrderStatus
	(*timestamppb.Timestamp)(nil),           // 9: google.protobuf.Timestamp
	(*v1.DeliveryAddress)(nil),              // 10: domain.order.common.v1.DeliveryAddress
	(*v1.DeliveryPeriod)(nil),               // 11: domain.order.common.v1.DeliveryPeriod
	(*v1.PackageInfo)(nil),                  // 12: domain.order.common.v1.PackageInfo
	(v1.DeliveryPriority)(0),                // 13: domain.order.common.v1.DeliveryPriority
	(v1.DeliveryStatus)(0),                  // 14: domain.order.common.v1.DeliveryStatus
	(*v1.DeliveryLocation)(nil),             // 15: domain.order.common.v1.DeliveryLocation
	(v1.NotDeliveredReason)(0),              // 16: domain.order.common.v1.NotDeliveredReason
}
var file_domain_order_v1_events_v1_events_proto_depIdxs = []int32{
	7,  // 0: domain.order.events.v1.OrderCreated.items:type_name -> domain.order.common.v1.OrderItem
	8,  // 1: domain.order.events.v1.OrderCreated.status:type_name -> domain.order.common.v1.OrderStatus
	9,  // 2: domain.order.events.v1.OrderCreated.created_at:type_name -> google.protobuf.Timestamp
	9,  // 3: domain.order.events.v1.OrderCreated.occurred_at:type_name -> google.protobuf.Timestamp
	8,  // 4: domain.order.events.v1.OrderCancelled.status:type_name -> domain.order.common.v1.OrderStatus
	9,  // 5: domain.order.events.v1.OrderCancelled.cancelled_at:type_name -> google.protobuf.Timestamp
	9,  // 6: domain.order.events.v1.OrderCancelled.occurred_at:type_name -> google.protobuf.Timestamp
	8,  // 7: domain.order.events.v1.OrderCompleted.status:type_name -> domain.order.common.v1.OrderStatus
	9,  // 8: domain.order.events.v1.OrderCompleted.completed_at:type_name -> google.protobuf.Timestamp
	9,  // 9: domain.order.events.v1.OrderCompleted.occurred_at:type_name -> google.protobuf.Timestamp
	10, // 10: domain.order.events.v1.OrderDeliveryRequestedEvent.pickup_address:type_name -> domain.order.common.v1.DeliveryAddress
	10, // 11: domain.order.events.v1.OrderDeliveryRequestedEvent.delivery_address:type_name -> domain.order.common.v1.DeliveryAddress
	11, // 12: domain.order.events.v1.OrderDeliveryRequestedEvent.delivery_period:type_name -> domain.order.common.v1.DeliveryPeriod
	12, // 13: domain.order.events.v1.OrderDeliveryRequestedEvent.package_info:type_name -> domain.order.common.v1.PackageInfo
	13, // 14: domain.order.events.v1.OrderDeliveryRequestedEvent.priority:type_name -> domain.order.common.v1.DeliveryPriority
	9,  // 15: domain.order.events.v1.OrderDeliveryRequestedEvent.created_at:type_name -> google.protobuf.Timestamp
	9,  // 16: domain.order.events.v1.OrderDeliveryRequestedEvent.occurred_at:type_name -> google.protobuf.Timestamp
	14, // 17: domain.order.events.v1.OrderDeliveryStatusUpdatedEvent.status:type_name -> domain.order.common.v1.DeliveryStatus
	9,  // 18: domain.order.events.v1.OrderDeliveryStatusUpdatedEvent.updated_at:type_name -> google.protobuf.Timestamp
	9,  // 19: domain.order.events.v1.OrderDeliveryStatusUpdatedEvent.occurred_at:type_name -> google.protobuf.Timestamp
	9,  // 20: domain.order.events.v1.OrderDeliveryCompletedEvent.delivered_at:type_name -> google.protobuf.Timestamp
	15, // 21: domain.order.events.v1.OrderDeliveryCompletedEvent.delivery_location:type_name -> domain.order.common.v1.DeliveryLocation
	9,  // 22: domain.order.events.v1.OrderDeliveryCompletedEvent.occurred_at:type_name -> google.protobuf.Timestamp
	16, // 23: domain.order.events.v1.OrderDeliveryFailedEvent.reason:type_name -> domain.order.common.v1.NotDeliveredReason
	9,  // 24: domain.order.events.v1.OrderDeliveryFailedEvent.failed_at:type_name -> google.protobuf.Timestamp
	9,  // 25: domain.order.events.v1.OrderDeliveryFailedEvent.occurred_at:type_name -> google.protobuf.Timestamp
	26, // [26:26] is the sub-list for method output_type
	26, // [26:26] is the sub-list for method input_type
	26, // [26:26] is the sub-list for extension type_name
	26, // [26:26] is the sub-list for extension extendee
	0,  // [0:26] is the sub-list for field type_name
}

func init() { file_domain_order_v1_events_v1_events_proto_init() }
func file_domain_order_v1_events_v1_events_proto_init() {
	if File_domain_order_v1_events_v1_events_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_domain_order_v1_events_v1_events_proto_rawDesc), len(file_domain_order_v1_events_v1_events_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_domain_order_v1_events_v1_events_proto_goTypes,
		DependencyIndexes: file_domain_order_v1_events_v1_events_proto_depIdxs,
		MessageInfos:      file_domain_order_v1_events_v1_events_proto_msgTypes,
	}.Build()
	File_domain_order_v1_events_v1_events_proto = out.File
	file_domain_order_v1_events_v1_events_proto_goTypes = nil
	file_domain_order_v1_events_v1_events_proto_depIdxs = nil
}
