// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: infrastructure/grpc/delivery/delivery.proto

package delivery

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Priority level for delivery
type Priority int32

const (
	Priority_PRIORITY_UNSPECIFIED Priority = 0
	Priority_PRIORITY_NORMAL      Priority = 1
	Priority_PRIORITY_URGENT      Priority = 2
)

// Enum value maps for Priority.
var (
	Priority_name = map[int32]string{
		0: "PRIORITY_UNSPECIFIED",
		1: "PRIORITY_NORMAL",
		2: "PRIORITY_URGENT",
	}
	Priority_value = map[string]int32{
		"PRIORITY_UNSPECIFIED": 0,
		"PRIORITY_NORMAL":      1,
		"PRIORITY_URGENT":      2,
	}
)

func (x Priority) Enum() *Priority {
	p := new(Priority)
	*p = x
	return p
}

func (x Priority) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Priority) Descriptor() protoreflect.EnumDescriptor {
	return file_infrastructure_grpc_delivery_delivery_proto_enumTypes[0].Descriptor()
}

func (Priority) Type() protoreflect.EnumType {
	return &file_infrastructure_grpc_delivery_delivery_proto_enumTypes[0]
}

func (x Priority) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Priority.Descriptor instead.
func (Priority) EnumDescriptor() ([]byte, []int) {
	return file_infrastructure_grpc_delivery_delivery_proto_rawDescGZIP(), []int{0}
}

// PackageStatus represents the delivery lifecycle state
type PackageStatus int32

const (
	PackageStatus_PACKAGE_STATUS_UNSPECIFIED       PackageStatus = 0
	PackageStatus_PACKAGE_STATUS_ACCEPTED          PackageStatus = 1
	PackageStatus_PACKAGE_STATUS_IN_POOL           PackageStatus = 2
	PackageStatus_PACKAGE_STATUS_ASSIGNED          PackageStatus = 3
	PackageStatus_PACKAGE_STATUS_IN_TRANSIT        PackageStatus = 4
	PackageStatus_PACKAGE_STATUS_DELIVERED         PackageStatus = 5
	PackageStatus_PACKAGE_STATUS_NOT_DELIVERED     PackageStatus = 6
	PackageStatus_PACKAGE_STATUS_REQUIRES_HANDLING PackageStatus = 7
)

// Enum value maps for PackageStatus.
var (
	PackageStatus_name = map[int32]string{
		0: "PACKAGE_STATUS_UNSPECIFIED",
		1: "PACKAGE_STATUS_ACCEPTED",
		2: "PACKAGE_STATUS_IN_POOL",
		3: "PACKAGE_STATUS_ASSIGNED",
		4: "PACKAGE_STATUS_IN_TRANSIT",
		5: "PACKAGE_STATUS_DELIVERED",
		6: "PACKAGE_STATUS_NOT_DELIVERED",
		7: "PACKAGE_STATUS_REQUIRES_HANDLING",
	}
	PackageStatus_value = map[string]int32{
		"PACKAGE_STATUS_UNSPECIFIED":       0,
		"PACKAGE_STATUS_ACCEPTED":          1,
		"PACKAGE_STATUS_IN_POOL":           2,
		"PACKAGE_STATUS_ASSIGNED":          3,
		"PACKAGE_STATUS_IN_TRANSIT":        4,
		"PACKAGE_STATUS_DELIVERED":         5,
		"PACKAGE_STATUS_NOT_DELIVERED":     6,
		"PACKAGE_STATUS_REQUIRES_HANDLING": 7,
	}
)

func (x PackageStatus) Enum() *PackageStatus {
	p := new(PackageStatus)
	*p = x
	return p
}

func (x PackageStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PackageStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_infrastructure_grpc_delivery_delivery_proto_enumTypes[1].Descriptor()
}

func (PackageStatus) Type() protoreflect.EnumType {
	return &file_infrastructure_grpc_delivery_delivery_proto_enumTypes[1]
}

func (x PackageStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PackageStatus.Descriptor instead.
func (PackageStatus) EnumDescriptor() ([]byte, []int) {
	return file_infrastructure_grpc_delivery_delivery_proto_rawDescGZIP(), []int{1}
}

// Address represents a physical address for pickup/delivery
type Address struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Street        string                 `protobuf:"bytes,1,opt,name=street,proto3" json:"street,omitempty"`
	City          string                 `protobuf:"bytes,2,opt,name=city,proto3" json:"city,omitempty"`
	PostalCode    string                 `protobuf:"bytes,3,opt,name=postal_code,json=postalCode,proto3" json:"postal_code,omitempty"`
	Country       string                 `protobuf:"bytes,4,opt,name=country,proto3" json:"country,omitempty"`
	Latitude      float64                `protobuf:"fixed64,5,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,6,opt,name=longitude,proto3" json:"longitude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Address) Reset() {
	*x = Address{}
	mi := &file_infrastructure_grpc_delivery_delivery_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Address) ProtoMessage() {}

func (x *Address) ProtoReflect() protoreflect.Message {
	mi := &file_infrastructure_grpc_delivery_delivery_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Address.ProtoReflect.Descriptor instead.
func (*Address) Descriptor() ([]byte, []int) {
	return file_infrastructure_grpc_delivery_delivery_proto_rawDescGZIP(), []int{0}
}

func (x *Address) GetStreet() string {
	if x != nil {
		return x.Street
	}
	return ""
}

func (x *Address) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *Address) GetPostalCode() string {
	if x != nil {
		return x.PostalCode
	}
	return ""
}

func (x *Address) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *Address) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *Address) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

// DeliveryPeriod represents the desired delivery time window
type DeliveryPeriod struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeliveryPeriod) Reset() {
	*x = DeliveryPeriod{}
	mi := &file_infrastructure_grpc_delivery_delivery_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliveryPeriod) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliveryPeriod) ProtoMessage() {}

func (x *DeliveryPeriod) ProtoReflect() protoreflect.Message {
	mi := &file_infrastructure_grpc_delivery_delivery_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliveryPeriod.ProtoReflect.Descriptor instead.
func (*DeliveryPeriod) Descriptor() ([]byte, []int) {
	return file_infrastructure_grpc_delivery_delivery_proto_rawDescGZIP(), []int{1}
}

func (x *DeliveryPeriod) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *DeliveryPeriod) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

// PackageInfo contains physical characteristics of the package
type PackageInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WeightKg      float64                `protobuf:"fixed64,1,opt,name=weight_kg,json=weightKg,proto3" json:"weight_kg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PackageInfo) Reset() {
	*x = PackageInfo{}
	mi := &file_infrastructure_grpc_delivery_delivery_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PackageInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PackageInfo) ProtoMessage() {}

func (x *PackageInfo) ProtoReflect() protoreflect.Message {
	mi := &file_infrastructure_grpc_delivery_delivery_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PackageInfo.ProtoReflect.Descriptor instead.
func (*PackageInfo) Descriptor() ([]byte, []int) {
	return file_infrastructure_grpc_delivery_delivery_proto_rawDescGZIP(), []int{2}
}

func (x *PackageInfo) GetWeightKg() float64 {
	if x != nil {
		return x.WeightKg
	}
	return 0
}

// RecipientContacts contains recipient contact details for delivery
type RecipientContacts struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RecipientName  string                 `protobuf:"bytes,1,opt,name=recipient_name,json=recipientName,proto3" json:"recipient_name,omitempty"`
	RecipientPhone string                 `protobuf:"bytes,2,opt,name=recipient_phone,json=recipientPhone,proto3" json:"recipient_phone,omitempty"`
	RecipientEmail string                 `protobuf:"bytes,3,opt,name=recipient_email,json=recipientEmail,proto3" json:"recipient_email,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RecipientContacts) Reset() {
	*x = RecipientContacts{}
	mi := &file_infrastructure_grpc_delivery_delivery_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecipientContacts) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecipientContacts) ProtoMessage() {}

func (x *RecipientContacts) ProtoReflect() protoreflect.Message {
	mi := &file_infrastructure_grpc_delivery_delivery_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecipientContacts.ProtoReflect.Descriptor instead.
func (*RecipientContacts) Descriptor() ([]byte, []int) {
	return file_infrastructure_grpc_delivery_delivery_proto_rawDescGZIP(), []int{3}
}

func (x *RecipientContacts) GetRecipientName() string {
	if x != nil {
		return x.RecipientName
	}
	return ""
}

func (x *RecipientContacts) GetRecipientPhone() string {
	if x != nil {
		return x.RecipientPhone
	}
	return ""
}

func (x *RecipientContacts) GetRecipientEmail() string {
	if x != nil {
		return x.RecipientEmail
	}
	return ""
}

// AcceptOrderRequest contains data to accept an order for delivery
type AcceptOrderRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	OrderId           string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	CustomerId        string                 `protobuf:"bytes,2,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	PickupAddress     *Address               `protobuf:"bytes,3,opt,name=pickup_address,json=pickupAddress,proto3" json:"pickup_address,omitempty"`
	DeliveryAddress   *Address               `protobuf:"bytes,4,opt,name=delivery_address,json=deliveryAddress,proto3" json:"delivery_address,omitempty"`
	DeliveryPeriod    *DeliveryPeriod        `protobuf:"bytes,5,opt,name=delivery_period,json=deliveryPeriod,proto3" json:"delivery_period,omitempty"`
	PackageInfo       *PackageInfo           `protobuf:"bytes,6,opt,name=package_info,json=packageInfo,proto3" json:"package_info,omitempty"`
	Priority          Priority               `protobuf:"varint,7,opt,name=priority,proto3,enum=infrastructure.grpc.delivery.v1.Priority" json:"priority,omitempty"`
	RecipientContacts *RecipientContacts     `protobuf:"bytes,8,opt,name=recipient_contacts,json=recipientContacts,proto3" json:"recipient_contacts,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AcceptOrderRequest) Reset() {
	*x = AcceptOrderRequest{}
	mi := &file_infrastructure_grpc_delivery_delivery_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptOrderRequest) ProtoMessage() {}

func (x *AcceptOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_infrastructure_grpc_delivery_delivery_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptOrderRequest.ProtoReflect.Descriptor instead.
func (*AcceptOrderRequest) Descriptor() ([]byte, []int) {
	return file_infrastructure_grpc_delivery_delivery_proto_rawDescGZIP(), []int{4}
}

func (x *AcceptOrderRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *AcceptOrderRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *AcceptOrderRequest) GetPickupAddress() *Address {
	if x != nil {
		return x.PickupAddress
	}
	return nil
}

func (x *AcceptOrderRequest) GetDeliveryAddress() *Address {
	if x != nil {
		return x.DeliveryAddress
	}
	return nil
}

func (x *AcceptOrderRequest) GetDeliveryPeriod() *DeliveryPeriod {
	if x != nil {
		return x.DeliveryPeriod
	}
	return nil
}

func (x *AcceptOrderRequest) GetPackageInfo() *PackageInfo {
	if x != nil {
		return x.PackageInfo
	}
	return nil
}

func (x *AcceptOrderRequest) GetPriority() Priority {
	if x != nil {
		return x.Priority
	}
	return Priority_PRIORITY_UNSPECIFIED
}

func (x *AcceptOrderRequest) GetRecipientContacts() *RecipientContacts {
	if x != nil {
		return x.RecipientContacts
	}
	return nil
}

// AcceptOrderResponse returns the created package data
type AcceptOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PackageId     string                 `protobuf:"bytes,1,opt,name=package_id,json=packageId,proto3" json:"package_id,omitempty"`
	Status        PackageStatus          `protobuf:"varint,2,opt,name=status,proto3,enum=infrastructure.grpc.delivery.v1.PackageStatus" json:"status,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptOrderResponse) Reset() {
	*x = AcceptOrderResponse{}
	mi := &file_infrastructure_grpc_delivery_delivery_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptOrderResponse) ProtoMessage() {}

func (x *AcceptOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_infrastructure_grpc_delivery_delivery_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptOrderResponse.ProtoReflect.Descriptor instead.
func (*AcceptOrderResponse) Descriptor() ([]byte, []int) {
	return file_infrastructure_grpc_delivery_delivery_proto_rawDescGZIP(), []int{5}
}

func (x *AcceptOrderResponse) GetPackageId() string {
	if x != nil {
		return x.PackageId
	}
	return ""
}

func (x *AcceptOrderResponse) GetStatus() PackageStatus {
	if x != nil {
		return x.Status
	}
	return PackageStatus_PACKAGE_STATUS_UNSPECIFIED
}

func (x *AcceptOrderResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

var File_infrastructure_grpc_delivery_delivery_proto protoreflect.FileDescriptor

const file_infrastructure_grpc_delivery_delivery_proto_rawDesc = "" +
	"\n" +
	"+infrastructure/grpc/delivery/delivery.proto\x12\x1finfrastructure.grpc.delivery.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xaa\x01\n" +
	"\aAddress\x12\x16\n" +
	"\x06street\x18\x01 \x01(\tR\x06street\x12\x12\n" +
	"\x04city\x18\x02 \x01(\tR\x04city\x12\x1f\n" +
	"\vpostal_code\x18\x03 \x01(\tR\n" +
	"postalCode\x12\x18\n" +
	"\acountry\x18\x04 \x01(\tR\acountry\x12\x1a\n" +
	"\blatitude\x18\x05 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x06 \x01(\x01R\tlongitude\"\x82\x01\n" +
	"\x0eDeliveryPeriod\x129\n" +
	"\n" +
	"start_time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\"*\n" +
	"\vPackageInfo\x12\x1b\n" +
	"\tweight_kg\x18\x01 \x01(\x01R\bweightKg\"\x8c\x01\n" +
	"\x11RecipientContacts\x12%\n" +
	"\x0erecipient_name\x18\x01 \x01(\tR\rrecipientName\x12'\n" +
	"\x0frecipient_phone\x18\x02 \x01(\tR\x0erecipientPhone\x12'\n" +
	"\x0frecipient_email\x18\x03 \x01(\tR\x0erecipientEmail\"\xcb\x04\n" +
	"\x12AcceptOrderRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x1f\n" +
	"\vcustomer_id\x18\x02 \x01(\tR\n" +
	"customerId\x12O\n" +
	"\x0epickup_address\x18\x03 \x01(\v2(.infrastructure.grpc.delivery.v1.AddressR\rpickupAddress\x12S\n" +
	"\x10delivery_address\x18\x04 \x01(\v2(.infrastructure.grpc.delivery.v1.AddressR\x0fdeliveryAddress\x12X\n" +
	"\x0fdelivery_period\x18\x05 \x01(\v2/.infrastructure.grpc.delivery.v1.DeliveryPeriodR\x0edeliveryPeriod\x12O\n" +
	"\fpackage_info\x18\x06 \x01(\v2,.infrastructure.grpc.delivery.v1.PackageInfoR\vpackageInfo\x12E\n" +
	"\bpriority\x18\a \x01(\x0e2).infrastructure.grpc.delivery.v1.PriorityR\bpriority\x12a\n" +
	"\x12recipient_contacts\x18\b \x01(\v22.infrastructure.grpc.delivery.v1.RecipientContactsR\x11recipientContacts\"\xb7\x01\n" +
	"\x13AcceptOrderResponse\x12\x1d\n" +
	"\n" +
	"package_id\x18\x01 \x01(\tR\tpackageId\x12F\n" +
	"\x06status\x18\x02 \x01(\x0e2..infrastructure.grpc.delivery.v1.PackageStatusR\x06status\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt*N\n" +
	"\bPriority\x12\x18\n" +
	"\x14PRIORITY_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fPRIORITY_NORMAL\x10\x01\x12\x13\n" +
	"\x0fPRIORITY_URGENT\x10\x02*\x8a\x02\n" +
	"\rPackageStatus\x12\x1e\n" +
	"\x1aPACKAGE_STATUS_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17PACKAGE_STATUS_ACCEPTED\x10\x01\x12\x1a\n" +
	"\x16PACKAGE_STATUS_IN_POOL\x10\x02\x12\x1b\n" +
	"\x17PACKAGE_STATUS_ASSIGNED\x10\x03\x12\x1d\n" +
	"\x19PACKAGE_STATUS_IN_TRANSIT\x10\x04\x12\x1c\n" +
	"\x18PACKAGE_STATUS_DELIVERED\x10\x05\x12 \n" +
	"\x1cPACKAGE_STATUS_NOT_DELIVERED\x10\x06\x12$\n" +
	" PACKAGE_STATUS_REQUIRES_HANDLING\x10\a2\x8b\x01\n" +
	"\x0fDeliveryService\x12x\n" +
	"\vAcceptOrder\x123.infrastructure.grpc.delivery.v1.AcceptOrderRequest\x1a4.infrastructure.grpc.delivery.v1.AcceptOrderResponseB\x9c\x02\n" +
	"#com.infrastructure.grpc.delivery.v1B\rDeliveryProtoP\x01ZGgithub.com/shortlink-org/shop/oms/internal/infrastructure/grpc/delivery\xa2\x02\x03IGD\xaa\x02\x1fInfrastructure.Grpc.Delivery.V1\xca\x02\x1fInfrastructure\\Grpc\\Delivery\\V1\xe2\x02+Infrastructure\\Grpc\\Delivery\\V1\\GPBMetadata\xea\x02\"Infrastructure::Grpc::Delivery::V1b\x06proto3"

var (
	file_infrastructure_grpc_delivery_delivery_proto_rawDescOnce sync.Once
	file_infrastructure_grpc_delivery_delivery_proto_rawDescData []byte
)

func file_infrastructure_grpc_delivery_delivery_proto_rawDescGZIP() []byte {
	file_infrastructure_grpc_delivery_delivery_proto_rawDescOnce.Do(func() {
		file_infrastructure_grpc_delivery_delivery_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_infrastructure_grpc_delivery_delivery_proto_rawDesc), len(file_infrastructure_grpc_delivery_delivery_proto_rawDesc)))
	})
	return file_infrastructure_grpc_delivery_delivery_proto_rawDescData
}

var file_infrastructure_grpc_delivery_delivery_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_infrastructure_grpc_delivery_delivery_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_infrastructure_grpc_delivery_delivery_proto_goTypes = []any{
	(Priority)(0),                 // 0: infrastructure.grpc.delivery.v1.Priority
	(PackageStatus)(0),            // 1: infrastructure.grpc.delivery.v1.PackageStatus
	(*Address)(nil),               // 2: infrastructure.grpc.delivery.v1.Address
	(*DeliveryPeriod)(nil),        // 3: infrastructure.grpc.delivery.v1.DeliveryPeriod
	(*PackageInfo)(nil),           // 4: infrastructure.grpc.delivery.v1.PackageInfo
	(*RecipientContacts)(nil),     // 5: infrastructure.grpc.delivery.v1.RecipientContacts
	(*AcceptOrderRequest)(nil),    // 6: infrastructure.grpc.delivery.v1.AcceptOrderRequest
	(*AcceptOrderResponse)(nil),   // 7: infrastructure.grpc.delivery.v1.AcceptOrderResponse
	(*timestamppb.Timestamp)(nil), // 8: google.protobuf.Timestamp
}
var file_infrastructure_grpc_delivery_delivery_proto_depIdxs = []int32{
	8,  // 0: infrastructure.grpc.delivery.v1.DeliveryPeriod.start_time:type_name -> google.protobuf.Timestamp
	8,  // 1: infrastructure.grpc.delivery.v1.DeliveryPeriod.end_time:type_name -> google.protobuf.Timestamp
	2,  // 2: infrastructure.grpc.delivery.v1.AcceptOrderRequest.pickup_address:type_name -> infrastructure.grpc.delivery.v1.Address
	2,  // 3: infrastructure.grpc.delivery.v1.AcceptOrderRequest.delivery_address:type_name -> infrastructure.grpc.delivery.v1.Address
	3,  // 4: infrastructure.grpc.delivery.v1.AcceptOrderRequest.delivery_period:type_name -> infrastructure.grpc.delivery.v1.DeliveryPeriod
	4,  // 5: infrastructure.grpc.delivery.v1.AcceptOrderRequest.package_info:type_name -> infrastructure.grpc.delivery.v1.PackageInfo
	0,  // 6: infrastructure.grpc.delivery.v1.AcceptOrderRequest.priority:type_name -> infrastructure.grpc.delivery.v1.Priority
	5,  // 7: infrastructure.grpc.delivery.v1.AcceptOrderRequest.recipient_contacts:type_name -> infrastructure.grpc.delivery.v1.RecipientContacts
	1,  // 8: infrastructure.grpc.delivery.v1.AcceptOrderResponse.status:type_name -> infrastructure.grpc.delivery.v1.PackageStatus
	8,  // 9: infrastructure.grpc.delivery.v1.AcceptOrderResponse.created_at:type_name -> google.protobuf.Timestamp
	6,  // 10: infrastructure.grpc.delivery.v1.DeliveryService.AcceptOrder:input_type -> infrastructure.grpc.delivery.v1.AcceptOrderRequest
	7,  // 11: infrastructure.grpc.delivery.v1.DeliveryService.AcceptOrder:output_type -> infrastructure.grpc.delivery.v1.AcceptOrderResponse
	11, // [11:12] is the sub-list for method output_type
	10, // [10:11] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_infrastructure_grpc_delivery_delivery_proto_init() }
func file_infrastructure_grpc_delivery_delivery_proto_init() {
	if File_infrastructure_grpc_delivery_delivery_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_infrastructure_grpc_delivery_delivery_proto_rawDesc), len(file_infrastructure_grpc_delivery_delivery_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_infrastructure_grpc_delivery_delivery_proto_goTypes,
		DependencyIndexes: file_infrastructure_grpc_delivery_delivery_proto_depIdxs,
		EnumInfos:         file_infrastructure_grpc_delivery_delivery_proto_enumTypes,
		MessageInfos:      file_infrastructure_grpc_delivery_delivery_proto_msgTypes,
	}.Build()
	File_infrastructure_grpc_delivery_delivery_proto = out.File
	file_infrastructure_grpc_delivery_delivery_proto_goTypes = nil
	file_infrastructure_grpc_delivery_delivery_proto_depIdxs = nil
}
