// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// This is a simplified version for the OMS delivery client.

package delivery

import (
	"context"

	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
)

// DeliveryServiceClient is the client API for DeliveryService service.
type DeliveryServiceClient interface {
	// AcceptOrder accepts an order from OMS for delivery
	AcceptOrder(ctx context.Context, in *AcceptOrderRequest, opts ...grpc.CallOption) (*AcceptOrderResponse, error)
}

type deliveryServiceClient struct {
	cc grpc.ClientConnInterface
}

// NewDeliveryServiceClient creates a new DeliveryService client.
func NewDeliveryServiceClient(cc grpc.ClientConnInterface) DeliveryServiceClient {
	return &deliveryServiceClient{cc}
}

func (c *deliveryServiceClient) AcceptOrder(ctx context.Context, in *AcceptOrderRequest, opts ...grpc.CallOption) (*AcceptOrderResponse, error) {
	out := new(AcceptOrderResponse)
	err := c.cc.Invoke(ctx, "/infrastructure.rpc.delivery.v1.DeliveryService/AcceptOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DeliveryServiceServer is the server API for DeliveryService service.
type DeliveryServiceServer interface {
	// AcceptOrder accepts an order from OMS for delivery
	AcceptOrder(context.Context, *AcceptOrderRequest) (*AcceptOrderResponse, error)
}

// UnimplementedDeliveryServiceServer should be embedded to have forward compatible implementations.
type UnimplementedDeliveryServiceServer struct{}

func (UnimplementedDeliveryServiceServer) AcceptOrder(context.Context, *AcceptOrderRequest) (*AcceptOrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AcceptOrder not implemented")
}
