// Code generated by protoc-gen-go. DO NOT EDIT.
// This is a simplified version for the OMS delivery client.

package delivery

import (
	"google.golang.org/protobuf/types/known/timestamppb"
)

// Priority level for delivery
type Priority int32

const (
	Priority_PRIORITY_UNSPECIFIED Priority = 0
	Priority_PRIORITY_NORMAL      Priority = 1
	Priority_PRIORITY_URGENT      Priority = 2
)

// PackageStatus represents the delivery lifecycle state
type PackageStatus int32

const (
	PackageStatus_PACKAGE_STATUS_UNSPECIFIED       PackageStatus = 0
	PackageStatus_PACKAGE_STATUS_ACCEPTED          PackageStatus = 1
	PackageStatus_PACKAGE_STATUS_IN_POOL           PackageStatus = 2
	PackageStatus_PACKAGE_STATUS_ASSIGNED          PackageStatus = 3
	PackageStatus_PACKAGE_STATUS_IN_TRANSIT        PackageStatus = 4
	PackageStatus_PACKAGE_STATUS_DELIVERED         PackageStatus = 5
	PackageStatus_PACKAGE_STATUS_NOT_DELIVERED     PackageStatus = 6
	PackageStatus_PACKAGE_STATUS_REQUIRES_HANDLING PackageStatus = 7
)

// Address represents a physical address for pickup/delivery
type Address struct {
	Street     string  `protobuf:"bytes,1,opt,name=street,proto3" json:"street,omitempty"`
	City       string  `protobuf:"bytes,2,opt,name=city,proto3" json:"city,omitempty"`
	PostalCode string  `protobuf:"bytes,3,opt,name=postal_code,json=postalCode,proto3" json:"postal_code,omitempty"`
	Country    string  `protobuf:"bytes,4,opt,name=country,proto3" json:"country,omitempty"`
	Latitude   float64 `protobuf:"fixed64,5,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude  float64 `protobuf:"fixed64,6,opt,name=longitude,proto3" json:"longitude,omitempty"`
}

// DeliveryPeriod represents the desired delivery time window
type DeliveryPeriod struct {
	StartTime *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime   *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
}

// PackageInfo contains physical characteristics of the package
type PackageInfo struct {
	WeightKg   float64 `protobuf:"fixed64,1,opt,name=weight_kg,json=weightKg,proto3" json:"weight_kg,omitempty"`
	Dimensions string  `protobuf:"bytes,2,opt,name=dimensions,proto3" json:"dimensions,omitempty"`
}

// AcceptOrderRequest contains data to accept an order for delivery
type AcceptOrderRequest struct {
	OrderId         string          `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	CustomerId      string          `protobuf:"bytes,2,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	PickupAddress   *Address        `protobuf:"bytes,3,opt,name=pickup_address,json=pickupAddress,proto3" json:"pickup_address,omitempty"`
	DeliveryAddress *Address        `protobuf:"bytes,4,opt,name=delivery_address,json=deliveryAddress,proto3" json:"delivery_address,omitempty"`
	DeliveryPeriod  *DeliveryPeriod `protobuf:"bytes,5,opt,name=delivery_period,json=deliveryPeriod,proto3" json:"delivery_period,omitempty"`
	PackageInfo     *PackageInfo    `protobuf:"bytes,6,opt,name=package_info,json=packageInfo,proto3" json:"package_info,omitempty"`
	Priority        Priority        `protobuf:"varint,7,opt,name=priority,proto3,enum=infrastructure.grpc.delivery.v1.Priority" json:"priority,omitempty"`
}

// AcceptOrderResponse returns the created package data
type AcceptOrderResponse struct {
	PackageId string                 `protobuf:"bytes,1,opt,name=package_id,json=packageId,proto3" json:"package_id,omitempty"`
	Status    PackageStatus          `protobuf:"varint,2,opt,name=status,proto3,enum=infrastructure.grpc.delivery.v1.PackageStatus" json:"status,omitempty"`
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
}
