// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: infrastructure/rpc/order/v1/model/v1/model.proto

package v1

import (
	v1 "github.com/shortlink-org/shop/oms/internal/domain/order/v1/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/emptypb"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Define the Order message
type OrderState struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier for the order
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Identifier for the customer who placed the order
	CustomerId string `protobuf:"bytes,2,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	// List of items in the order
	Items []*OrderItem `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	// Current status of the order
	Status v1.OrderStatus `protobuf:"varint,4,opt,name=status,proto3,enum=domain.order.common.v1.OrderStatus" json:"status,omitempty"`
	// Timestamp for when the order was created
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Timestamp for when the order was last updated
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderState) Reset() {
	*x = OrderState{}
	mi := &file_infrastructure_rpc_order_v1_model_v1_model_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderState) ProtoMessage() {}

func (x *OrderState) ProtoReflect() protoreflect.Message {
	mi := &file_infrastructure_rpc_order_v1_model_v1_model_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderState.ProtoReflect.Descriptor instead.
func (*OrderState) Descriptor() ([]byte, []int) {
	return file_infrastructure_rpc_order_v1_model_v1_model_proto_rawDescGZIP(), []int{0}
}

func (x *OrderState) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *OrderState) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *OrderState) GetItems() []*OrderItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *OrderState) GetStatus() v1.OrderStatus {
	if x != nil {
		return x.Status
	}
	return v1.OrderStatus(0)
}

func (x *OrderState) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *OrderState) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// Define the OrderItem message
type OrderItem struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier for the item
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Quantity of the item ordered
	Quantity int32 `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	// Price of a single item
	Price         float64 `protobuf:"fixed64,3,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderItem) Reset() {
	*x = OrderItem{}
	mi := &file_infrastructure_rpc_order_v1_model_v1_model_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderItem) ProtoMessage() {}

func (x *OrderItem) ProtoReflect() protoreflect.Message {
	mi := &file_infrastructure_rpc_order_v1_model_v1_model_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderItem.ProtoReflect.Descriptor instead.
func (*OrderItem) Descriptor() ([]byte, []int) {
	return file_infrastructure_rpc_order_v1_model_v1_model_proto_rawDescGZIP(), []int{1}
}

func (x *OrderItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *OrderItem) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *OrderItem) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

// Request message for creating an order
type CreateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Order details
	Order         *OrderState `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRequest) Reset() {
	*x = CreateRequest{}
	mi := &file_infrastructure_rpc_order_v1_model_v1_model_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRequest) ProtoMessage() {}

func (x *CreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_infrastructure_rpc_order_v1_model_v1_model_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRequest.ProtoReflect.Descriptor instead.
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return file_infrastructure_rpc_order_v1_model_v1_model_proto_rawDescGZIP(), []int{2}
}

func (x *CreateRequest) GetOrder() *OrderState {
	if x != nil {
		return x.Order
	}
	return nil
}

// Request message for getting an order by ID
type GetRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the order to retrieve
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_infrastructure_rpc_order_v1_model_v1_model_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_infrastructure_rpc_order_v1_model_v1_model_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_infrastructure_rpc_order_v1_model_v1_model_proto_rawDescGZIP(), []int{3}
}

func (x *GetRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// Response message for getting an order by ID
type GetResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Retrieved order details
	Order         *OrderState `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_infrastructure_rpc_order_v1_model_v1_model_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_infrastructure_rpc_order_v1_model_v1_model_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_infrastructure_rpc_order_v1_model_v1_model_proto_rawDescGZIP(), []int{4}
}

func (x *GetResponse) GetOrder() *OrderState {
	if x != nil {
		return x.Order
	}
	return nil
}

// Request message for updating an order
type UpdateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Updated order details
	Order *OrderState `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	// Fields to update
	UpdateMask    *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRequest) Reset() {
	*x = UpdateRequest{}
	mi := &file_infrastructure_rpc_order_v1_model_v1_model_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRequest) ProtoMessage() {}

func (x *UpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_infrastructure_rpc_order_v1_model_v1_model_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRequest.ProtoReflect.Descriptor instead.
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return file_infrastructure_rpc_order_v1_model_v1_model_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateRequest) GetOrder() *OrderState {
	if x != nil {
		return x.Order
	}
	return nil
}

func (x *UpdateRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

// Request message for deleting an order by ID
type CancelRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the order to delete
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelRequest) Reset() {
	*x = CancelRequest{}
	mi := &file_infrastructure_rpc_order_v1_model_v1_model_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelRequest) ProtoMessage() {}

func (x *CancelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_infrastructure_rpc_order_v1_model_v1_model_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelRequest.ProtoReflect.Descriptor instead.
func (*CancelRequest) Descriptor() ([]byte, []int) {
	return file_infrastructure_rpc_order_v1_model_v1_model_proto_rawDescGZIP(), []int{6}
}

func (x *CancelRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_infrastructure_rpc_order_v1_model_v1_model_proto protoreflect.FileDescriptor

const file_infrastructure_rpc_order_v1_model_v1_model_proto_rawDesc = "" +
	"\n" +
	"0infrastructure/rpc/order/v1/model/v1/model.proto\x12$infrastructure.rpc.order.v1.model.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a google/protobuf/field_mask.proto\x1a&domain/order/v1/common/v1/common.proto\"\xb7\x02\n" +
	"\n" +
	"OrderState\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vcustomer_id\x18\x02 \x01(\tR\n" +
	"customerId\x12E\n" +
	"\x05items\x18\x03 \x03(\v2/.infrastructure.rpc.order.v1.model.v1.OrderItemR\x05items\x12;\n" +
	"\x06status\x18\x04 \x01(\x0e2#.domain.order.common.v1.OrderStatusR\x06status\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"M\n" +
	"\tOrderItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x05R\bquantity\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x01R\x05price\"W\n" +
	"\rCreateRequest\x12F\n" +
	"\x05order\x18\x01 \x01(\v20.infrastructure.rpc.order.v1.model.v1.OrderStateR\x05order\"\x1c\n" +
	"\n" +
	"GetRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"U\n" +
	"\vGetResponse\x12F\n" +
	"\x05order\x18\x01 \x01(\v20.infrastructure.rpc.order.v1.model.v1.OrderStateR\x05order\"\x94\x01\n" +
	"\rUpdateRequest\x12F\n" +
	"\x05order\x18\x01 \x01(\v20.infrastructure.rpc.order.v1.model.v1.OrderStateR\x05order\x12;\n" +
	"\vupdate_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskR\n" +
	"updateMask\"\x1f\n" +
	"\rCancelRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02idB\xbe\x02\n" +
	"(com.infrastructure.rpc.order.v1.model.v1B\n" +
	"ModelProtoP\x01ZOgithub.com/shortlink-org/shop/oms/internal/infrastructure/rpc/order/v1/model/v1\xa2\x02\x05IROVM\xaa\x02$Infrastructure.Rpc.Order.V1.Model.V1\xca\x02$Infrastructure\\Rpc\\Order\\V1\\Model\\V1\xe2\x020Infrastructure\\Rpc\\Order\\V1\\Model\\V1\\GPBMetadata\xea\x02)Infrastructure::Rpc::Order::V1::Model::V1b\x06proto3"

var (
	file_infrastructure_rpc_order_v1_model_v1_model_proto_rawDescOnce sync.Once
	file_infrastructure_rpc_order_v1_model_v1_model_proto_rawDescData []byte
)

func file_infrastructure_rpc_order_v1_model_v1_model_proto_rawDescGZIP() []byte {
	file_infrastructure_rpc_order_v1_model_v1_model_proto_rawDescOnce.Do(func() {
		file_infrastructure_rpc_order_v1_model_v1_model_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_infrastructure_rpc_order_v1_model_v1_model_proto_rawDesc), len(file_infrastructure_rpc_order_v1_model_v1_model_proto_rawDesc)))
	})
	return file_infrastructure_rpc_order_v1_model_v1_model_proto_rawDescData
}

var file_infrastructure_rpc_order_v1_model_v1_model_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_infrastructure_rpc_order_v1_model_v1_model_proto_goTypes = []any{
	(*OrderState)(nil),            // 0: infrastructure.rpc.order.v1.model.v1.OrderState
	(*OrderItem)(nil),             // 1: infrastructure.rpc.order.v1.model.v1.OrderItem
	(*CreateRequest)(nil),         // 2: infrastructure.rpc.order.v1.model.v1.CreateRequest
	(*GetRequest)(nil),            // 3: infrastructure.rpc.order.v1.model.v1.GetRequest
	(*GetResponse)(nil),           // 4: infrastructure.rpc.order.v1.model.v1.GetResponse
	(*UpdateRequest)(nil),         // 5: infrastructure.rpc.order.v1.model.v1.UpdateRequest
	(*CancelRequest)(nil),         // 6: infrastructure.rpc.order.v1.model.v1.CancelRequest
	(v1.OrderStatus)(0),           // 7: domain.order.common.v1.OrderStatus
	(*timestamppb.Timestamp)(nil), // 8: google.protobuf.Timestamp
	(*fieldmaskpb.FieldMask)(nil), // 9: google.protobuf.FieldMask
}
var file_infrastructure_rpc_order_v1_model_v1_model_proto_depIdxs = []int32{
	1, // 0: infrastructure.rpc.order.v1.model.v1.OrderState.items:type_name -> infrastructure.rpc.order.v1.model.v1.OrderItem
	7, // 1: infrastructure.rpc.order.v1.model.v1.OrderState.status:type_name -> domain.order.common.v1.OrderStatus
	8, // 2: infrastructure.rpc.order.v1.model.v1.OrderState.created_at:type_name -> google.protobuf.Timestamp
	8, // 3: infrastructure.rpc.order.v1.model.v1.OrderState.updated_at:type_name -> google.protobuf.Timestamp
	0, // 4: infrastructure.rpc.order.v1.model.v1.CreateRequest.order:type_name -> infrastructure.rpc.order.v1.model.v1.OrderState
	0, // 5: infrastructure.rpc.order.v1.model.v1.GetResponse.order:type_name -> infrastructure.rpc.order.v1.model.v1.OrderState
	0, // 6: infrastructure.rpc.order.v1.model.v1.UpdateRequest.order:type_name -> infrastructure.rpc.order.v1.model.v1.OrderState
	9, // 7: infrastructure.rpc.order.v1.model.v1.UpdateRequest.update_mask:type_name -> google.protobuf.FieldMask
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_infrastructure_rpc_order_v1_model_v1_model_proto_init() }
func file_infrastructure_rpc_order_v1_model_v1_model_proto_init() {
	if File_infrastructure_rpc_order_v1_model_v1_model_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_infrastructure_rpc_order_v1_model_v1_model_proto_rawDesc), len(file_infrastructure_rpc_order_v1_model_v1_model_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_infrastructure_rpc_order_v1_model_v1_model_proto_goTypes,
		DependencyIndexes: file_infrastructure_rpc_order_v1_model_v1_model_proto_depIdxs,
		MessageInfos:      file_infrastructure_rpc_order_v1_model_v1_model_proto_msgTypes,
	}.Build()
	File_infrastructure_rpc_order_v1_model_v1_model_proto = out.File
	file_infrastructure_rpc_order_v1_model_v1_model_proto_goTypes = nil
	file_infrastructure_rpc_order_v1_model_v1_model_proto_depIdxs = nil
}
