// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: infrastructure/rpc/cart/v1/model/v1/model.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/emptypb"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CartItem is the cart item message.
type CartItem struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Field mask
	FieldMask *fieldmaskpb.FieldMask `protobuf:"bytes,6,opt,name=field_mask,json=fieldMask,proto3" json:"field_mask,omitempty"`
	// Good ID
	GoodId string `protobuf:"bytes,1,opt,name=good_id,json=goodId,proto3" json:"good_id,omitempty"`
	// Quantity
	Quantity      int32 `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CartItem) Reset() {
	*x = CartItem{}
	mi := &file_infrastructure_rpc_cart_v1_model_v1_model_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CartItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CartItem) ProtoMessage() {}

func (x *CartItem) ProtoReflect() protoreflect.Message {
	mi := &file_infrastructure_rpc_cart_v1_model_v1_model_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CartItem.ProtoReflect.Descriptor instead.
func (*CartItem) Descriptor() ([]byte, []int) {
	return file_infrastructure_rpc_cart_v1_model_v1_model_proto_rawDescGZIP(), []int{0}
}

func (x *CartItem) GetFieldMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.FieldMask
	}
	return nil
}

func (x *CartItem) GetGoodId() string {
	if x != nil {
		return x.GoodId
	}
	return ""
}

func (x *CartItem) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

// CartState is the cart state message.
type CartState struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Field mask
	FieldMask *fieldmaskpb.FieldMask `protobuf:"bytes,6,opt,name=field_mask,json=fieldMask,proto3" json:"field_mask,omitempty"`
	// Cart ID
	CartId string `protobuf:"bytes,1,opt,name=cart_id,json=cartId,proto3" json:"cart_id,omitempty"`
	// User ID
	CustomerId string `protobuf:"bytes,2,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	// Items
	Items []*CartItem `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	// Created at
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Updated at
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CartState) Reset() {
	*x = CartState{}
	mi := &file_infrastructure_rpc_cart_v1_model_v1_model_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CartState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CartState) ProtoMessage() {}

func (x *CartState) ProtoReflect() protoreflect.Message {
	mi := &file_infrastructure_rpc_cart_v1_model_v1_model_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CartState.ProtoReflect.Descriptor instead.
func (*CartState) Descriptor() ([]byte, []int) {
	return file_infrastructure_rpc_cart_v1_model_v1_model_proto_rawDescGZIP(), []int{1}
}

func (x *CartState) GetFieldMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.FieldMask
	}
	return nil
}

func (x *CartState) GetCartId() string {
	if x != nil {
		return x.CartId
	}
	return ""
}

func (x *CartState) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *CartState) GetItems() []*CartItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *CartState) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *CartState) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// AddRequest is the request message for adding an item to the cart.
type AddRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Cart ID
	CustomerId string `protobuf:"bytes,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	// Item to add
	Items         []*CartItem `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddRequest) Reset() {
	*x = AddRequest{}
	mi := &file_infrastructure_rpc_cart_v1_model_v1_model_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddRequest) ProtoMessage() {}

func (x *AddRequest) ProtoReflect() protoreflect.Message {
	mi := &file_infrastructure_rpc_cart_v1_model_v1_model_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddRequest.ProtoReflect.Descriptor instead.
func (*AddRequest) Descriptor() ([]byte, []int) {
	return file_infrastructure_rpc_cart_v1_model_v1_model_proto_rawDescGZIP(), []int{2}
}

func (x *AddRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *AddRequest) GetItems() []*CartItem {
	if x != nil {
		return x.Items
	}
	return nil
}

// RemoveRequest is the request message for removing an item from the cart.
type RemoveRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Cart ID
	CustomerId string `protobuf:"bytes,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	// Item to remove
	Items         []*CartItem `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveRequest) Reset() {
	*x = RemoveRequest{}
	mi := &file_infrastructure_rpc_cart_v1_model_v1_model_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveRequest) ProtoMessage() {}

func (x *RemoveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_infrastructure_rpc_cart_v1_model_v1_model_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveRequest.ProtoReflect.Descriptor instead.
func (*RemoveRequest) Descriptor() ([]byte, []int) {
	return file_infrastructure_rpc_cart_v1_model_v1_model_proto_rawDescGZIP(), []int{3}
}

func (x *RemoveRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *RemoveRequest) GetItems() []*CartItem {
	if x != nil {
		return x.Items
	}
	return nil
}

// GetRequest is the request message for getting the cart state.
type GetRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Cart ID
	CustomerId    string `protobuf:"bytes,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_infrastructure_rpc_cart_v1_model_v1_model_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_infrastructure_rpc_cart_v1_model_v1_model_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_infrastructure_rpc_cart_v1_model_v1_model_proto_rawDescGZIP(), []int{4}
}

func (x *GetRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

// GetResponse is the response message for getting the cart state.
type GetResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Cart state
	State         *CartState `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_infrastructure_rpc_cart_v1_model_v1_model_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_infrastructure_rpc_cart_v1_model_v1_model_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_infrastructure_rpc_cart_v1_model_v1_model_proto_rawDescGZIP(), []int{5}
}

func (x *GetResponse) GetState() *CartState {
	if x != nil {
		return x.State
	}
	return nil
}

// ResetRequest is the request message for resetting the cart.
type ResetRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Cart ID
	CustomerId    string `protobuf:"bytes,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetRequest) Reset() {
	*x = ResetRequest{}
	mi := &file_infrastructure_rpc_cart_v1_model_v1_model_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetRequest) ProtoMessage() {}

func (x *ResetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_infrastructure_rpc_cart_v1_model_v1_model_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetRequest.ProtoReflect.Descriptor instead.
func (*ResetRequest) Descriptor() ([]byte, []int) {
	return file_infrastructure_rpc_cart_v1_model_v1_model_proto_rawDescGZIP(), []int{6}
}

func (x *ResetRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

var File_infrastructure_rpc_cart_v1_model_v1_model_proto protoreflect.FileDescriptor

const file_infrastructure_rpc_cart_v1_model_v1_model_proto_rawDesc = "" +
	"\n" +
	"/infrastructure/rpc/cart/v1/model/v1/model.proto\x12#infrastructure.rpc.cart.v1.model.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a google/protobuf/field_mask.proto\"z\n" +
	"\bCartItem\x129\n" +
	"\n" +
	"field_mask\x18\x06 \x01(\v2\x1a.google.protobuf.FieldMaskR\tfieldMask\x12\x17\n" +
	"\agood_id\x18\x01 \x01(\tR\x06goodId\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x05R\bquantity\"\xbb\x02\n" +
	"\tCartState\x129\n" +
	"\n" +
	"field_mask\x18\x06 \x01(\v2\x1a.google.protobuf.FieldMaskR\tfieldMask\x12\x17\n" +
	"\acart_id\x18\x01 \x01(\tR\x06cartId\x12\x1f\n" +
	"\vcustomer_id\x18\x02 \x01(\tR\n" +
	"customerId\x12C\n" +
	"\x05items\x18\x03 \x03(\v2-.infrastructure.rpc.cart.v1.model.v1.CartItemR\x05items\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"r\n" +
	"\n" +
	"AddRequest\x12\x1f\n" +
	"\vcustomer_id\x18\x01 \x01(\tR\n" +
	"customerId\x12C\n" +
	"\x05items\x18\x02 \x03(\v2-.infrastructure.rpc.cart.v1.model.v1.CartItemR\x05items\"u\n" +
	"\rRemoveRequest\x12\x1f\n" +
	"\vcustomer_id\x18\x01 \x01(\tR\n" +
	"customerId\x12C\n" +
	"\x05items\x18\x02 \x03(\v2-.infrastructure.rpc.cart.v1.model.v1.CartItemR\x05items\"-\n" +
	"\n" +
	"GetRequest\x12\x1f\n" +
	"\vcustomer_id\x18\x01 \x01(\tR\n" +
	"customerId\"S\n" +
	"\vGetResponse\x12D\n" +
	"\x05state\x18\x01 \x01(\v2..infrastructure.rpc.cart.v1.model.v1.CartStateR\x05state\"/\n" +
	"\fResetRequest\x12\x1f\n" +
	"\vcustomer_id\x18\x01 \x01(\tR\n" +
	"customerIdB\xb8\x02\n" +
	"'com.infrastructure.rpc.cart.v1.model.v1B\n" +
	"ModelProtoP\x01ZNgithub.com/shortlink-org/shop/oms/internal/infrastructure/rpc/cart/v1/model/v1\xa2\x02\x05IRCVM\xaa\x02#Infrastructure.Rpc.Cart.V1.Model.V1\xca\x02#Infrastructure\\Rpc\\Cart\\V1\\Model\\V1\xe2\x02/Infrastructure\\Rpc\\Cart\\V1\\Model\\V1\\GPBMetadata\xea\x02(Infrastructure::Rpc::Cart::V1::Model::V1b\x06proto3"

var (
	file_infrastructure_rpc_cart_v1_model_v1_model_proto_rawDescOnce sync.Once
	file_infrastructure_rpc_cart_v1_model_v1_model_proto_rawDescData []byte
)

func file_infrastructure_rpc_cart_v1_model_v1_model_proto_rawDescGZIP() []byte {
	file_infrastructure_rpc_cart_v1_model_v1_model_proto_rawDescOnce.Do(func() {
		file_infrastructure_rpc_cart_v1_model_v1_model_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_infrastructure_rpc_cart_v1_model_v1_model_proto_rawDesc), len(file_infrastructure_rpc_cart_v1_model_v1_model_proto_rawDesc)))
	})
	return file_infrastructure_rpc_cart_v1_model_v1_model_proto_rawDescData
}

var file_infrastructure_rpc_cart_v1_model_v1_model_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_infrastructure_rpc_cart_v1_model_v1_model_proto_goTypes = []any{
	(*CartItem)(nil),              // 0: infrastructure.rpc.cart.v1.model.v1.CartItem
	(*CartState)(nil),             // 1: infrastructure.rpc.cart.v1.model.v1.CartState
	(*AddRequest)(nil),            // 2: infrastructure.rpc.cart.v1.model.v1.AddRequest
	(*RemoveRequest)(nil),         // 3: infrastructure.rpc.cart.v1.model.v1.RemoveRequest
	(*GetRequest)(nil),            // 4: infrastructure.rpc.cart.v1.model.v1.GetRequest
	(*GetResponse)(nil),           // 5: infrastructure.rpc.cart.v1.model.v1.GetResponse
	(*ResetRequest)(nil),          // 6: infrastructure.rpc.cart.v1.model.v1.ResetRequest
	(*fieldmaskpb.FieldMask)(nil), // 7: google.protobuf.FieldMask
	(*timestamppb.Timestamp)(nil), // 8: google.protobuf.Timestamp
}
var file_infrastructure_rpc_cart_v1_model_v1_model_proto_depIdxs = []int32{
	7, // 0: infrastructure.rpc.cart.v1.model.v1.CartItem.field_mask:type_name -> google.protobuf.FieldMask
	7, // 1: infrastructure.rpc.cart.v1.model.v1.CartState.field_mask:type_name -> google.protobuf.FieldMask
	0, // 2: infrastructure.rpc.cart.v1.model.v1.CartState.items:type_name -> infrastructure.rpc.cart.v1.model.v1.CartItem
	8, // 3: infrastructure.rpc.cart.v1.model.v1.CartState.created_at:type_name -> google.protobuf.Timestamp
	8, // 4: infrastructure.rpc.cart.v1.model.v1.CartState.updated_at:type_name -> google.protobuf.Timestamp
	0, // 5: infrastructure.rpc.cart.v1.model.v1.AddRequest.items:type_name -> infrastructure.rpc.cart.v1.model.v1.CartItem
	0, // 6: infrastructure.rpc.cart.v1.model.v1.RemoveRequest.items:type_name -> infrastructure.rpc.cart.v1.model.v1.CartItem
	1, // 7: infrastructure.rpc.cart.v1.model.v1.GetResponse.state:type_name -> infrastructure.rpc.cart.v1.model.v1.CartState
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_infrastructure_rpc_cart_v1_model_v1_model_proto_init() }
func file_infrastructure_rpc_cart_v1_model_v1_model_proto_init() {
	if File_infrastructure_rpc_cart_v1_model_v1_model_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_infrastructure_rpc_cart_v1_model_v1_model_proto_rawDesc), len(file_infrastructure_rpc_cart_v1_model_v1_model_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_infrastructure_rpc_cart_v1_model_v1_model_proto_goTypes,
		DependencyIndexes: file_infrastructure_rpc_cart_v1_model_v1_model_proto_depIdxs,
		MessageInfos:      file_infrastructure_rpc_cart_v1_model_v1_model_proto_msgTypes,
	}.Build()
	File_infrastructure_rpc_cart_v1_model_v1_model_proto = out.File
	file_infrastructure_rpc_cart_v1_model_v1_model_proto_goTypes = nil
	file_infrastructure_rpc_cart_v1_model_v1_model_proto_depIdxs = nil
}
