# Generated by Django to merge conflicting migrations

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("offices", "0002_add_history"),
        ("offices", "0002_berlin_offices"),
    ]

    operations = []
