// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"

	v1 "github.com/shortlink-org/shop/oms/internal/domain/cart/v1"
)

// MockCartRepository is an autogenerated mock type for the CartRepository type
type MockCartRepository struct {
	mock.Mock
}

type MockCartRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCartRepository) EXPECT() *MockCartRepository_Expecter {
	return &MockCartRepository_Expecter{mock: &_m.Mock}
}

// Load provides a mock function with given fields: ctx, customerID
func (_m *MockCartRepository) Load(ctx context.Context, customerID uuid.UUID) (*v1.State, error) {
	ret := _m.Called(ctx, customerID)

	if len(ret) == 0 {
		panic("no return value specified for Load")
	}

	var r0 *v1.State
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*v1.State, error)); ok {
		return rf(ctx, customerID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *v1.State); ok {
		r0 = rf(ctx, customerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.State)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, customerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCartRepository_Load_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Load'
type MockCartRepository_Load_Call struct {
	*mock.Call
}

// Load is a helper method to define mock.On call
//   - ctx context.Context
//   - customerID uuid.UUID
func (_e *MockCartRepository_Expecter) Load(ctx interface{}, customerID interface{}) *MockCartRepository_Load_Call {
	return &MockCartRepository_Load_Call{Call: _e.mock.On("Load", ctx, customerID)}
}

func (_c *MockCartRepository_Load_Call) Run(run func(ctx context.Context, customerID uuid.UUID)) *MockCartRepository_Load_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockCartRepository_Load_Call) Return(_a0 *v1.State, _a1 error) *MockCartRepository_Load_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCartRepository_Load_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*v1.State, error)) *MockCartRepository_Load_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function with given fields: ctx, state
func (_m *MockCartRepository) Save(ctx context.Context, state *v1.State) error {
	ret := _m.Called(ctx, state)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.State) error); ok {
		r0 = rf(ctx, state)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCartRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockCartRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - state *v1.State
func (_e *MockCartRepository_Expecter) Save(ctx interface{}, state interface{}) *MockCartRepository_Save_Call {
	return &MockCartRepository_Save_Call{Call: _e.mock.On("Save", ctx, state)}
}

func (_c *MockCartRepository_Save_Call) Run(run func(ctx context.Context, state *v1.State)) *MockCartRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v1.State))
	})
	return _c
}

func (_c *MockCartRepository_Save_Call) Return(_a0 error) *MockCartRepository_Save_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCartRepository_Save_Call) RunAndReturn(run func(context.Context, *v1.State) error) *MockCartRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCartRepository creates a new instance of MockCartRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCartRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCartRepository {
	mock := &MockCartRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
