// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	ports "github.com/shortlink-org/shop/oms/internal/domain/ports"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"

	v1 "github.com/shortlink-org/shop/oms/internal/domain/order/v1"
)

// MockOrderRepository is an autogenerated mock type for the OrderRepository type
type MockOrderRepository struct {
	mock.Mock
}

type MockOrderRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOrderRepository) EXPECT() *MockOrderRepository_Expecter {
	return &MockOrderRepository_Expecter{mock: &_m.Mock}
}

// List provides a mock function with given fields: ctx, filter, page, pageSize
func (_m *MockOrderRepository) List(ctx context.Context, filter ports.ListFilter, page int32, pageSize int32) (*ports.ListResult, error) {
	ret := _m.Called(ctx, filter, page, pageSize)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *ports.ListResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ports.ListFilter, int32, int32) (*ports.ListResult, error)); ok {
		return rf(ctx, filter, page, pageSize)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ports.ListFilter, int32, int32) *ports.ListResult); ok {
		r0 = rf(ctx, filter, page, pageSize)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ports.ListResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ports.ListFilter, int32, int32) error); ok {
		r1 = rf(ctx, filter, page, pageSize)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOrderRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockOrderRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - filter ports.ListFilter
//   - page int32
//   - pageSize int32
func (_e *MockOrderRepository_Expecter) List(ctx interface{}, filter interface{}, page interface{}, pageSize interface{}) *MockOrderRepository_List_Call {
	return &MockOrderRepository_List_Call{Call: _e.mock.On("List", ctx, filter, page, pageSize)}
}

func (_c *MockOrderRepository_List_Call) Run(run func(ctx context.Context, filter ports.ListFilter, page int32, pageSize int32)) *MockOrderRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(ports.ListFilter), args[2].(int32), args[3].(int32))
	})
	return _c
}

func (_c *MockOrderRepository_List_Call) Return(_a0 *ports.ListResult, _a1 error) *MockOrderRepository_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOrderRepository_List_Call) RunAndReturn(run func(context.Context, ports.ListFilter, int32, int32) (*ports.ListResult, error)) *MockOrderRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// ListByCustomer provides a mock function with given fields: ctx, customerID
func (_m *MockOrderRepository) ListByCustomer(ctx context.Context, customerID uuid.UUID) ([]*v1.OrderState, error) {
	ret := _m.Called(ctx, customerID)

	if len(ret) == 0 {
		panic("no return value specified for ListByCustomer")
	}

	var r0 []*v1.OrderState
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*v1.OrderState, error)); ok {
		return rf(ctx, customerID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*v1.OrderState); ok {
		r0 = rf(ctx, customerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*v1.OrderState)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, customerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOrderRepository_ListByCustomer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByCustomer'
type MockOrderRepository_ListByCustomer_Call struct {
	*mock.Call
}

// ListByCustomer is a helper method to define mock.On call
//   - ctx context.Context
//   - customerID uuid.UUID
func (_e *MockOrderRepository_Expecter) ListByCustomer(ctx interface{}, customerID interface{}) *MockOrderRepository_ListByCustomer_Call {
	return &MockOrderRepository_ListByCustomer_Call{Call: _e.mock.On("ListByCustomer", ctx, customerID)}
}

func (_c *MockOrderRepository_ListByCustomer_Call) Run(run func(ctx context.Context, customerID uuid.UUID)) *MockOrderRepository_ListByCustomer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockOrderRepository_ListByCustomer_Call) Return(_a0 []*v1.OrderState, _a1 error) *MockOrderRepository_ListByCustomer_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOrderRepository_ListByCustomer_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]*v1.OrderState, error)) *MockOrderRepository_ListByCustomer_Call {
	_c.Call.Return(run)
	return _c
}

// Load provides a mock function with given fields: ctx, orderID
func (_m *MockOrderRepository) Load(ctx context.Context, orderID uuid.UUID) (*v1.OrderState, error) {
	ret := _m.Called(ctx, orderID)

	if len(ret) == 0 {
		panic("no return value specified for Load")
	}

	var r0 *v1.OrderState
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*v1.OrderState, error)); ok {
		return rf(ctx, orderID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *v1.OrderState); ok {
		r0 = rf(ctx, orderID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.OrderState)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, orderID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOrderRepository_Load_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Load'
type MockOrderRepository_Load_Call struct {
	*mock.Call
}

// Load is a helper method to define mock.On call
//   - ctx context.Context
//   - orderID uuid.UUID
func (_e *MockOrderRepository_Expecter) Load(ctx interface{}, orderID interface{}) *MockOrderRepository_Load_Call {
	return &MockOrderRepository_Load_Call{Call: _e.mock.On("Load", ctx, orderID)}
}

func (_c *MockOrderRepository_Load_Call) Run(run func(ctx context.Context, orderID uuid.UUID)) *MockOrderRepository_Load_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockOrderRepository_Load_Call) Return(_a0 *v1.OrderState, _a1 error) *MockOrderRepository_Load_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOrderRepository_Load_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*v1.OrderState, error)) *MockOrderRepository_Load_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function with given fields: ctx, state
func (_m *MockOrderRepository) Save(ctx context.Context, state *v1.OrderState) error {
	ret := _m.Called(ctx, state)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.OrderState) error); ok {
		r0 = rf(ctx, state)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockOrderRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockOrderRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - state *v1.OrderState
func (_e *MockOrderRepository_Expecter) Save(ctx interface{}, state interface{}) *MockOrderRepository_Save_Call {
	return &MockOrderRepository_Save_Call{Call: _e.mock.On("Save", ctx, state)}
}

func (_c *MockOrderRepository_Save_Call) Run(run func(ctx context.Context, state *v1.OrderState)) *MockOrderRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v1.OrderState))
	})
	return _c
}

func (_c *MockOrderRepository_Save_Call) Return(_a0 error) *MockOrderRepository_Save_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOrderRepository_Save_Call) RunAndReturn(run func(context.Context, *v1.OrderState) error) *MockOrderRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockOrderRepository creates a new instance of MockOrderRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrderRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrderRepository {
	mock := &MockOrderRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
