// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package queries

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

// Shopping carts by customer
type OmsCart struct {
	CustomerID uuid.UUID
	// Optimistic concurrency control version
	Version   int32
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

// Items in shopping carts
type OmsCartItem struct {
	CartID   uuid.UUID
	GoodID   uuid.UUID
	Quantity int32
	Price    decimal.Decimal
	Discount decimal.Decimal
}
