// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: query.sql

package queries

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgconn"
	"github.com/shopspring/decimal"
)

const deleteCartItems = `-- name: DeleteCartItems :exec
DELETE FROM oms.cart_items
WHERE cart_id = $1
`

func (q *Queries) DeleteCartItems(ctx context.Context, cartID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteCartItems, cartID)
	return err
}

const getCart = `-- name: GetCart :one
SELECT customer_id, version, created_at, updated_at
FROM oms.carts
WHERE customer_id = $1
`

func (q *Queries) GetCart(ctx context.Context, customerID uuid.UUID) (OmsCart, error) {
	row := q.db.QueryRow(ctx, getCart, customerID)
	var i OmsCart
	err := row.Scan(
		&i.CustomerID,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCartItems = `-- name: GetCartItems :many
SELECT good_id, quantity, price, discount
FROM oms.cart_items
WHERE cart_id = $1
`

type GetCartItemsRow struct {
	GoodID   uuid.UUID
	Quantity int32
	Price    decimal.Decimal
	Discount decimal.Decimal
}

func (q *Queries) GetCartItems(ctx context.Context, cartID uuid.UUID) ([]GetCartItemsRow, error) {
	rows, err := q.db.Query(ctx, getCartItems, cartID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCartItemsRow
	for rows.Next() {
		var i GetCartItemsRow
		if err := rows.Scan(
			&i.GoodID,
			&i.Quantity,
			&i.Price,
			&i.Discount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertCart = `-- name: InsertCart :exec
INSERT INTO oms.carts (customer_id, version, created_at, updated_at)
VALUES ($1, 1, NOW(), NOW())
`

func (q *Queries) InsertCart(ctx context.Context, customerID uuid.UUID) error {
	_, err := q.db.Exec(ctx, insertCart, customerID)
	return err
}

const insertCartItem = `-- name: InsertCartItem :exec
INSERT INTO oms.cart_items (cart_id, good_id, quantity, price, discount)
VALUES ($1, $2, $3, $4, $5)
`

type InsertCartItemParams struct {
	CartID   uuid.UUID
	GoodID   uuid.UUID
	Quantity int32
	Price    decimal.Decimal
	Discount decimal.Decimal
}

func (q *Queries) InsertCartItem(ctx context.Context, arg InsertCartItemParams) error {
	_, err := q.db.Exec(ctx, insertCartItem,
		arg.CartID,
		arg.GoodID,
		arg.Quantity,
		arg.Price,
		arg.Discount,
	)
	return err
}

const upsertCart = `-- name: UpsertCart :execresult
INSERT INTO oms.carts (customer_id, version, created_at, updated_at)
VALUES ($1, $2, NOW(), NOW())
ON CONFLICT (customer_id)
DO UPDATE SET version = $2, updated_at = NOW()
WHERE oms.carts.version = $3
`

type UpsertCartParams struct {
	CustomerID uuid.UUID
	Version    int32
	Version_2  int32
}

func (q *Queries) UpsertCart(ctx context.Context, arg UpsertCartParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, upsertCart, arg.CustomerID, arg.Version, arg.Version_2)
}
