// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package queries

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgconn"
)

type Querier interface {
	DeleteCartItems(ctx context.Context, cartID uuid.UUID) error
	GetCart(ctx context.Context, customerID uuid.UUID) (OmsCart, error)
	GetCartItems(ctx context.Context, cartID uuid.UUID) ([]GetCartItemsRow, error)
	InsertCart(ctx context.Context, customerID uuid.UUID) error
	InsertCartItem(ctx context.Context, arg InsertCartItemParams) error
	UpsertCart(ctx context.Context, arg UpsertCartParams) (pgconn.CommandTag, error)
}
