// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: domain/cart/v1/event.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Cart event
type Event int32

const (
	// Unspecified
	Event_EVENT_UNSPECIFIED Event = 0
	// Add item
	Event_EVENT_ADD Event = 1
	// Remove item
	Event_EVENT_REMOVE Event = 2
	// Reset cart
	Event_EVENT_RESET Event = 3
	// Get cart
	Event_EVENT_GET Event = 4
)

// Enum value maps for Event.
var (
	Event_name = map[int32]string{
		0: "EVENT_UNSPECIFIED",
		1: "EVENT_ADD",
		2: "EVENT_REMOVE",
		3: "EVENT_RESET",
		4: "EVENT_GET",
	}
	Event_value = map[string]int32{
		"EVENT_UNSPECIFIED": 0,
		"EVENT_ADD":         1,
		"EVENT_REMOVE":      2,
		"EVENT_RESET":       3,
		"EVENT_GET":         4,
	}
)

func (x Event) Enum() *Event {
	p := new(Event)
	*p = x
	return p
}

func (x Event) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Event) Descriptor() protoreflect.EnumDescriptor {
	return file_domain_cart_v1_event_proto_enumTypes[0].Descriptor()
}

func (Event) Type() protoreflect.EnumType {
	return &file_domain_cart_v1_event_proto_enumTypes[0]
}

func (x Event) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Event.Descriptor instead.
func (Event) EnumDescriptor() ([]byte, []int) {
	return file_domain_cart_v1_event_proto_rawDescGZIP(), []int{0}
}

// EventTopic represents event topic names following canonical naming format:
// {service}.{aggregate}.{event}.{version}
// For OMS Service: oms.cart.{event}.v1
type EventTopic int32

const (
	// Unspecified topic
	EventTopic_EVENT_TOPIC_UNSPECIFIED EventTopic = 0
	// oms.cart.item_added.v1 - CartItemAdded event
	EventTopic_EVENT_TOPIC_CART_ITEM_ADDED EventTopic = 1
	// oms.cart.item_removed.v1 - CartItemRemoved event
	EventTopic_EVENT_TOPIC_CART_ITEM_REMOVED EventTopic = 2
	// oms.cart.reset.v1 - CartReset event
	EventTopic_EVENT_TOPIC_CART_RESET EventTopic = 3
)

// Enum value maps for EventTopic.
var (
	EventTopic_name = map[int32]string{
		0: "EVENT_TOPIC_UNSPECIFIED",
		1: "EVENT_TOPIC_CART_ITEM_ADDED",
		2: "EVENT_TOPIC_CART_ITEM_REMOVED",
		3: "EVENT_TOPIC_CART_RESET",
	}
	EventTopic_value = map[string]int32{
		"EVENT_TOPIC_UNSPECIFIED":       0,
		"EVENT_TOPIC_CART_ITEM_ADDED":   1,
		"EVENT_TOPIC_CART_ITEM_REMOVED": 2,
		"EVENT_TOPIC_CART_RESET":        3,
	}
)

func (x EventTopic) Enum() *EventTopic {
	p := new(EventTopic)
	*p = x
	return p
}

func (x EventTopic) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventTopic) Descriptor() protoreflect.EnumDescriptor {
	return file_domain_cart_v1_event_proto_enumTypes[1].Descriptor()
}

func (EventTopic) Type() protoreflect.EnumType {
	return &file_domain_cart_v1_event_proto_enumTypes[1]
}

func (x EventTopic) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventTopic.Descriptor instead.
func (EventTopic) EnumDescriptor() ([]byte, []int) {
	return file_domain_cart_v1_event_proto_rawDescGZIP(), []int{1}
}

var File_domain_cart_v1_event_proto protoreflect.FileDescriptor

const file_domain_cart_v1_event_proto_rawDesc = "" +
	"\n" +
	"\x1adomain/cart/v1/event.proto\x12\x0edomain.cart.v1*_\n" +
	"\x05Event\x12\x15\n" +
	"\x11EVENT_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tEVENT_ADD\x10\x01\x12\x10\n" +
	"\fEVENT_REMOVE\x10\x02\x12\x0f\n" +
	"\vEVENT_RESET\x10\x03\x12\r\n" +
	"\tEVENT_GET\x10\x04*\x89\x01\n" +
	"\n" +
	"EventTopic\x12\x1b\n" +
	"\x17EVENT_TOPIC_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bEVENT_TOPIC_CART_ITEM_ADDED\x10\x01\x12!\n" +
	"\x1dEVENT_TOPIC_CART_ITEM_REMOVED\x10\x02\x12\x1a\n" +
	"\x16EVENT_TOPIC_CART_RESET\x10\x03B\xb5\x01\n" +
	"\x12com.domain.cart.v1B\n" +
	"EventProtoP\x01Z9github.com/shortlink-org/shop/oms/internal/domain/cart/v1\xa2\x02\x03DCX\xaa\x02\x0eDomain.Cart.V1\xca\x02\x0eDomain\\Cart\\V1\xe2\x02\x1aDomain\\Cart\\V1\\GPBMetadata\xea\x02\x10Domain::Cart::V1b\x06proto3"

var (
	file_domain_cart_v1_event_proto_rawDescOnce sync.Once
	file_domain_cart_v1_event_proto_rawDescData []byte
)

func file_domain_cart_v1_event_proto_rawDescGZIP() []byte {
	file_domain_cart_v1_event_proto_rawDescOnce.Do(func() {
		file_domain_cart_v1_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_domain_cart_v1_event_proto_rawDesc), len(file_domain_cart_v1_event_proto_rawDesc)))
	})
	return file_domain_cart_v1_event_proto_rawDescData
}

var file_domain_cart_v1_event_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_domain_cart_v1_event_proto_goTypes = []any{
	(Event)(0),      // 0: domain.cart.v1.Event
	(EventTopic)(0), // 1: domain.cart.v1.EventTopic
}
var file_domain_cart_v1_event_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_domain_cart_v1_event_proto_init() }
func file_domain_cart_v1_event_proto_init() {
	if File_domain_cart_v1_event_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_domain_cart_v1_event_proto_rawDesc), len(file_domain_cart_v1_event_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_domain_cart_v1_event_proto_goTypes,
		DependencyIndexes: file_domain_cart_v1_event_proto_depIdxs,
		EnumInfos:         file_domain_cart_v1_event_proto_enumTypes,
	}.Build()
	File_domain_cart_v1_event_proto = out.File
	file_domain_cart_v1_event_proto_goTypes = nil
	file_domain_cart_v1_event_proto_depIdxs = nil
}
