with-expecter: true
dir: "mocks"
outpkg: mocks
packages:
  github.com/shortlink-org/shop/oms/internal/domain/ports:
    interfaces:
      UnitOfWork:
      CartRepository:
      OrderRepository:
      EventPublisher:
      PricerClient:
