// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: domain/stock/v1/stock_event.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// StockChangeEvent - Event when stock quantity changes
type StockChangeEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// good_id is the good ID (UUID as string)
	GoodId string `protobuf:"bytes,1,opt,name=good_id,json=goodId,proto3" json:"good_id,omitempty"`
	// old_quantity is the previous stock quantity
	OldQuantity uint32 `protobuf:"varint,2,opt,name=old_quantity,json=oldQuantity,proto3" json:"old_quantity,omitempty"`
	// new_quantity is the new stock quantity
	NewQuantity uint32 `protobuf:"varint,3,opt,name=new_quantity,json=newQuantity,proto3" json:"new_quantity,omitempty"`
	// timestamp is when the stock change occurred
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StockChangeEvent) Reset() {
	*x = StockChangeEvent{}
	mi := &file_domain_stock_v1_stock_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StockChangeEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockChangeEvent) ProtoMessage() {}

func (x *StockChangeEvent) ProtoReflect() protoreflect.Message {
	mi := &file_domain_stock_v1_stock_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockChangeEvent.ProtoReflect.Descriptor instead.
func (*StockChangeEvent) Descriptor() ([]byte, []int) {
	return file_domain_stock_v1_stock_event_proto_rawDescGZIP(), []int{0}
}

func (x *StockChangeEvent) GetGoodId() string {
	if x != nil {
		return x.GoodId
	}
	return ""
}

func (x *StockChangeEvent) GetOldQuantity() uint32 {
	if x != nil {
		return x.OldQuantity
	}
	return 0
}

func (x *StockChangeEvent) GetNewQuantity() uint32 {
	if x != nil {
		return x.NewQuantity
	}
	return 0
}

func (x *StockChangeEvent) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

var File_domain_stock_v1_stock_event_proto protoreflect.FileDescriptor

const file_domain_stock_v1_stock_event_proto_rawDesc = "" +
	"\n" +
	"!domain/stock/v1/stock_event.proto\x12\x0fdomain.stock.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xab\x01\n" +
	"\x10StockChangeEvent\x12\x17\n" +
	"\agood_id\x18\x01 \x01(\tR\x06goodId\x12!\n" +
	"\fold_quantity\x18\x02 \x01(\rR\voldQuantity\x12!\n" +
	"\fnew_quantity\x18\x03 \x01(\rR\vnewQuantity\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestampB\xc0\x01\n" +
	"\x13com.domain.stock.v1B\x0fStockEventProtoP\x01Z:github.com/shortlink-org/shop/oms/internal/domain/stock/v1\xa2\x02\x03DSX\xaa\x02\x0fDomain.Stock.V1\xca\x02\x0fDomain\\Stock\\V1\xe2\x02\x1bDomain\\Stock\\V1\\GPBMetadata\xea\x02\x11Domain::Stock::V1b\x06proto3"

var (
	file_domain_stock_v1_stock_event_proto_rawDescOnce sync.Once
	file_domain_stock_v1_stock_event_proto_rawDescData []byte
)

func file_domain_stock_v1_stock_event_proto_rawDescGZIP() []byte {
	file_domain_stock_v1_stock_event_proto_rawDescOnce.Do(func() {
		file_domain_stock_v1_stock_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_domain_stock_v1_stock_event_proto_rawDesc), len(file_domain_stock_v1_stock_event_proto_rawDesc)))
	})
	return file_domain_stock_v1_stock_event_proto_rawDescData
}

var file_domain_stock_v1_stock_event_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_domain_stock_v1_stock_event_proto_goTypes = []any{
	(*StockChangeEvent)(nil),      // 0: domain.stock.v1.StockChangeEvent
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_domain_stock_v1_stock_event_proto_depIdxs = []int32{
	1, // 0: domain.stock.v1.StockChangeEvent.timestamp:type_name -> google.protobuf.Timestamp
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_domain_stock_v1_stock_event_proto_init() }
func file_domain_stock_v1_stock_event_proto_init() {
	if File_domain_stock_v1_stock_event_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_domain_stock_v1_stock_event_proto_rawDesc), len(file_domain_stock_v1_stock_event_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_domain_stock_v1_stock_event_proto_goTypes,
		DependencyIndexes: file_domain_stock_v1_stock_event_proto_depIdxs,
		MessageInfos:      file_domain_stock_v1_stock_event_proto_msgTypes,
	}.Build()
	File_domain_stock_v1_stock_event_proto = out.File
	file_domain_stock_v1_stock_event_proto_goTypes = nil
	file_domain_stock_v1_stock_event_proto_depIdxs = nil
}
