// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: domain/delivery/common/v1/common.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Priority levels for packages
type Priority int32

const (
	Priority_PRIORITY_UNSPECIFIED Priority = 0
	Priority_PRIORITY_NORMAL      Priority = 1
	Priority_PRIORITY_URGENT      Priority = 2
)

// Enum value maps for Priority.
var (
	Priority_name = map[int32]string{
		0: "PRIORITY_UNSPECIFIED",
		1: "PRIORITY_NORMAL",
		2: "PRIORITY_URGENT",
	}
	Priority_value = map[string]int32{
		"PRIORITY_UNSPECIFIED": 0,
		"PRIORITY_NORMAL":      1,
		"PRIORITY_URGENT":      2,
	}
)

func (x Priority) Enum() *Priority {
	p := new(Priority)
	*p = x
	return p
}

func (x Priority) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Priority) Descriptor() protoreflect.EnumDescriptor {
	return file_domain_delivery_common_v1_common_proto_enumTypes[0].Descriptor()
}

func (Priority) Type() protoreflect.EnumType {
	return &file_domain_delivery_common_v1_common_proto_enumTypes[0]
}

func (x Priority) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Priority.Descriptor instead.
func (Priority) EnumDescriptor() ([]byte, []int) {
	return file_domain_delivery_common_v1_common_proto_rawDescGZIP(), []int{0}
}

// Package status
type PackageStatus int32

const (
	PackageStatus_PACKAGE_STATUS_UNSPECIFIED       PackageStatus = 0
	PackageStatus_PACKAGE_STATUS_ACCEPTED          PackageStatus = 1
	PackageStatus_PACKAGE_STATUS_IN_POOL           PackageStatus = 2
	PackageStatus_PACKAGE_STATUS_ASSIGNED          PackageStatus = 3
	PackageStatus_PACKAGE_STATUS_IN_TRANSIT        PackageStatus = 4
	PackageStatus_PACKAGE_STATUS_DELIVERED         PackageStatus = 5
	PackageStatus_PACKAGE_STATUS_NOT_DELIVERED     PackageStatus = 6
	PackageStatus_PACKAGE_STATUS_REQUIRES_HANDLING PackageStatus = 7
)

// Enum value maps for PackageStatus.
var (
	PackageStatus_name = map[int32]string{
		0: "PACKAGE_STATUS_UNSPECIFIED",
		1: "PACKAGE_STATUS_ACCEPTED",
		2: "PACKAGE_STATUS_IN_POOL",
		3: "PACKAGE_STATUS_ASSIGNED",
		4: "PACKAGE_STATUS_IN_TRANSIT",
		5: "PACKAGE_STATUS_DELIVERED",
		6: "PACKAGE_STATUS_NOT_DELIVERED",
		7: "PACKAGE_STATUS_REQUIRES_HANDLING",
	}
	PackageStatus_value = map[string]int32{
		"PACKAGE_STATUS_UNSPECIFIED":       0,
		"PACKAGE_STATUS_ACCEPTED":          1,
		"PACKAGE_STATUS_IN_POOL":           2,
		"PACKAGE_STATUS_ASSIGNED":          3,
		"PACKAGE_STATUS_IN_TRANSIT":        4,
		"PACKAGE_STATUS_DELIVERED":         5,
		"PACKAGE_STATUS_NOT_DELIVERED":     6,
		"PACKAGE_STATUS_REQUIRES_HANDLING": 7,
	}
)

func (x PackageStatus) Enum() *PackageStatus {
	p := new(PackageStatus)
	*p = x
	return p
}

func (x PackageStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PackageStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_domain_delivery_common_v1_common_proto_enumTypes[1].Descriptor()
}

func (PackageStatus) Type() protoreflect.EnumType {
	return &file_domain_delivery_common_v1_common_proto_enumTypes[1]
}

func (x PackageStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PackageStatus.Descriptor instead.
func (PackageStatus) EnumDescriptor() ([]byte, []int) {
	return file_domain_delivery_common_v1_common_proto_rawDescGZIP(), []int{1}
}

// Courier status
type CourierStatus int32

const (
	CourierStatus_COURIER_STATUS_UNSPECIFIED CourierStatus = 0
	CourierStatus_COURIER_STATUS_UNAVAILABLE CourierStatus = 1
	CourierStatus_COURIER_STATUS_FREE        CourierStatus = 2
	CourierStatus_COURIER_STATUS_BUSY        CourierStatus = 3
	CourierStatus_COURIER_STATUS_ARCHIVED    CourierStatus = 4
)

// Enum value maps for CourierStatus.
var (
	CourierStatus_name = map[int32]string{
		0: "COURIER_STATUS_UNSPECIFIED",
		1: "COURIER_STATUS_UNAVAILABLE",
		2: "COURIER_STATUS_FREE",
		3: "COURIER_STATUS_BUSY",
		4: "COURIER_STATUS_ARCHIVED",
	}
	CourierStatus_value = map[string]int32{
		"COURIER_STATUS_UNSPECIFIED": 0,
		"COURIER_STATUS_UNAVAILABLE": 1,
		"COURIER_STATUS_FREE":        2,
		"COURIER_STATUS_BUSY":        3,
		"COURIER_STATUS_ARCHIVED":    4,
	}
)

func (x CourierStatus) Enum() *CourierStatus {
	p := new(CourierStatus)
	*p = x
	return p
}

func (x CourierStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CourierStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_domain_delivery_common_v1_common_proto_enumTypes[2].Descriptor()
}

func (CourierStatus) Type() protoreflect.EnumType {
	return &file_domain_delivery_common_v1_common_proto_enumTypes[2]
}

func (x CourierStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CourierStatus.Descriptor instead.
func (CourierStatus) EnumDescriptor() ([]byte, []int) {
	return file_domain_delivery_common_v1_common_proto_rawDescGZIP(), []int{2}
}

// Transport type
type TransportType int32

const (
	TransportType_TRANSPORT_TYPE_UNSPECIFIED TransportType = 0
	TransportType_TRANSPORT_TYPE_WALKING     TransportType = 1
	TransportType_TRANSPORT_TYPE_BICYCLE     TransportType = 2
	TransportType_TRANSPORT_TYPE_MOTORCYCLE  TransportType = 3
	TransportType_TRANSPORT_TYPE_CAR         TransportType = 4
)

// Enum value maps for TransportType.
var (
	TransportType_name = map[int32]string{
		0: "TRANSPORT_TYPE_UNSPECIFIED",
		1: "TRANSPORT_TYPE_WALKING",
		2: "TRANSPORT_TYPE_BICYCLE",
		3: "TRANSPORT_TYPE_MOTORCYCLE",
		4: "TRANSPORT_TYPE_CAR",
	}
	TransportType_value = map[string]int32{
		"TRANSPORT_TYPE_UNSPECIFIED": 0,
		"TRANSPORT_TYPE_WALKING":     1,
		"TRANSPORT_TYPE_BICYCLE":     2,
		"TRANSPORT_TYPE_MOTORCYCLE":  3,
		"TRANSPORT_TYPE_CAR":         4,
	}
)

func (x TransportType) Enum() *TransportType {
	p := new(TransportType)
	*p = x
	return p
}

func (x TransportType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TransportType) Descriptor() protoreflect.EnumDescriptor {
	return file_domain_delivery_common_v1_common_proto_enumTypes[3].Descriptor()
}

func (TransportType) Type() protoreflect.EnumType {
	return &file_domain_delivery_common_v1_common_proto_enumTypes[3]
}

func (x TransportType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TransportType.Descriptor instead.
func (TransportType) EnumDescriptor() ([]byte, []int) {
	return file_domain_delivery_common_v1_common_proto_rawDescGZIP(), []int{3}
}

// Delivery status (for deliver order)
type DeliveryStatus int32

const (
	DeliveryStatus_DELIVERY_STATUS_UNSPECIFIED   DeliveryStatus = 0
	DeliveryStatus_DELIVERY_STATUS_DELIVERED     DeliveryStatus = 1
	DeliveryStatus_DELIVERY_STATUS_NOT_DELIVERED DeliveryStatus = 2
)

// Enum value maps for DeliveryStatus.
var (
	DeliveryStatus_name = map[int32]string{
		0: "DELIVERY_STATUS_UNSPECIFIED",
		1: "DELIVERY_STATUS_DELIVERED",
		2: "DELIVERY_STATUS_NOT_DELIVERED",
	}
	DeliveryStatus_value = map[string]int32{
		"DELIVERY_STATUS_UNSPECIFIED":   0,
		"DELIVERY_STATUS_DELIVERED":     1,
		"DELIVERY_STATUS_NOT_DELIVERED": 2,
	}
)

func (x DeliveryStatus) Enum() *DeliveryStatus {
	p := new(DeliveryStatus)
	*p = x
	return p
}

func (x DeliveryStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeliveryStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_domain_delivery_common_v1_common_proto_enumTypes[4].Descriptor()
}

func (DeliveryStatus) Type() protoreflect.EnumType {
	return &file_domain_delivery_common_v1_common_proto_enumTypes[4]
}

func (x DeliveryStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeliveryStatus.Descriptor instead.
func (DeliveryStatus) EnumDescriptor() ([]byte, []int) {
	return file_domain_delivery_common_v1_common_proto_rawDescGZIP(), []int{4}
}

// Reason for not delivered
type NotDeliveredReason int32

const (
	NotDeliveredReason_NOT_DELIVERED_REASON_UNSPECIFIED            NotDeliveredReason = 0
	NotDeliveredReason_NOT_DELIVERED_REASON_CUSTOMER_NOT_AVAILABLE NotDeliveredReason = 1
	NotDeliveredReason_NOT_DELIVERED_REASON_WRONG_ADDRESS          NotDeliveredReason = 2
	NotDeliveredReason_NOT_DELIVERED_REASON_CUSTOMER_REFUSED       NotDeliveredReason = 3
	NotDeliveredReason_NOT_DELIVERED_REASON_ACCESS_DENIED          NotDeliveredReason = 4
	NotDeliveredReason_NOT_DELIVERED_REASON_PACKAGE_DAMAGED        NotDeliveredReason = 5
	NotDeliveredReason_NOT_DELIVERED_REASON_OTHER                  NotDeliveredReason = 6
)

// Enum value maps for NotDeliveredReason.
var (
	NotDeliveredReason_name = map[int32]string{
		0: "NOT_DELIVERED_REASON_UNSPECIFIED",
		1: "NOT_DELIVERED_REASON_CUSTOMER_NOT_AVAILABLE",
		2: "NOT_DELIVERED_REASON_WRONG_ADDRESS",
		3: "NOT_DELIVERED_REASON_CUSTOMER_REFUSED",
		4: "NOT_DELIVERED_REASON_ACCESS_DENIED",
		5: "NOT_DELIVERED_REASON_PACKAGE_DAMAGED",
		6: "NOT_DELIVERED_REASON_OTHER",
	}
	NotDeliveredReason_value = map[string]int32{
		"NOT_DELIVERED_REASON_UNSPECIFIED":            0,
		"NOT_DELIVERED_REASON_CUSTOMER_NOT_AVAILABLE": 1,
		"NOT_DELIVERED_REASON_WRONG_ADDRESS":          2,
		"NOT_DELIVERED_REASON_CUSTOMER_REFUSED":       3,
		"NOT_DELIVERED_REASON_ACCESS_DENIED":          4,
		"NOT_DELIVERED_REASON_PACKAGE_DAMAGED":        5,
		"NOT_DELIVERED_REASON_OTHER":                  6,
	}
)

func (x NotDeliveredReason) Enum() *NotDeliveredReason {
	p := new(NotDeliveredReason)
	*p = x
	return p
}

func (x NotDeliveredReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NotDeliveredReason) Descriptor() protoreflect.EnumDescriptor {
	return file_domain_delivery_common_v1_common_proto_enumTypes[5].Descriptor()
}

func (NotDeliveredReason) Type() protoreflect.EnumType {
	return &file_domain_delivery_common_v1_common_proto_enumTypes[5]
}

func (x NotDeliveredReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NotDeliveredReason.Descriptor instead.
func (NotDeliveredReason) EnumDescriptor() ([]byte, []int) {
	return file_domain_delivery_common_v1_common_proto_rawDescGZIP(), []int{5}
}

// Address represents a physical address with coordinates
type Address struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Street        string                 `protobuf:"bytes,1,opt,name=street,proto3" json:"street,omitempty"`
	City          string                 `protobuf:"bytes,2,opt,name=city,proto3" json:"city,omitempty"`
	PostalCode    string                 `protobuf:"bytes,3,opt,name=postal_code,json=postalCode,proto3" json:"postal_code,omitempty"`
	Country       string                 `protobuf:"bytes,4,opt,name=country,proto3" json:"country,omitempty"`
	Latitude      float64                `protobuf:"fixed64,5,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,6,opt,name=longitude,proto3" json:"longitude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Address) Reset() {
	*x = Address{}
	mi := &file_domain_delivery_common_v1_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Address) ProtoMessage() {}

func (x *Address) ProtoReflect() protoreflect.Message {
	mi := &file_domain_delivery_common_v1_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Address.ProtoReflect.Descriptor instead.
func (*Address) Descriptor() ([]byte, []int) {
	return file_domain_delivery_common_v1_common_proto_rawDescGZIP(), []int{0}
}

func (x *Address) GetStreet() string {
	if x != nil {
		return x.Street
	}
	return ""
}

func (x *Address) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *Address) GetPostalCode() string {
	if x != nil {
		return x.PostalCode
	}
	return ""
}

func (x *Address) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *Address) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *Address) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

// Location represents a GPS location
type Location struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Latitude      float64                `protobuf:"fixed64,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Accuracy      float64                `protobuf:"fixed64,3,opt,name=accuracy,proto3" json:"accuracy,omitempty"` // meters
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Speed         *float64               `protobuf:"fixed64,5,opt,name=speed,proto3,oneof" json:"speed,omitempty"`     // km/h (optional)
	Heading       *float64               `protobuf:"fixed64,6,opt,name=heading,proto3,oneof" json:"heading,omitempty"` // degrees 0-360 (optional)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Location) Reset() {
	*x = Location{}
	mi := &file_domain_delivery_common_v1_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Location) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Location) ProtoMessage() {}

func (x *Location) ProtoReflect() protoreflect.Message {
	mi := &file_domain_delivery_common_v1_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Location.ProtoReflect.Descriptor instead.
func (*Location) Descriptor() ([]byte, []int) {
	return file_domain_delivery_common_v1_common_proto_rawDescGZIP(), []int{1}
}

func (x *Location) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *Location) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *Location) GetAccuracy() float64 {
	if x != nil {
		return x.Accuracy
	}
	return 0
}

func (x *Location) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Location) GetSpeed() float64 {
	if x != nil && x.Speed != nil {
		return *x.Speed
	}
	return 0
}

func (x *Location) GetHeading() float64 {
	if x != nil && x.Heading != nil {
		return *x.Heading
	}
	return 0
}

// DeliveryPeriod represents the desired delivery time window
type DeliveryPeriod struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"` // Start of desired delivery period
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`       // End of desired delivery period
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeliveryPeriod) Reset() {
	*x = DeliveryPeriod{}
	mi := &file_domain_delivery_common_v1_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliveryPeriod) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliveryPeriod) ProtoMessage() {}

func (x *DeliveryPeriod) ProtoReflect() protoreflect.Message {
	mi := &file_domain_delivery_common_v1_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliveryPeriod.ProtoReflect.Descriptor instead.
func (*DeliveryPeriod) Descriptor() ([]byte, []int) {
	return file_domain_delivery_common_v1_common_proto_rawDescGZIP(), []int{2}
}

func (x *DeliveryPeriod) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *DeliveryPeriod) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

// PackageInfo contains package physical characteristics
type PackageInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WeightKg      float64                `protobuf:"fixed64,1,opt,name=weight_kg,json=weightKg,proto3" json:"weight_kg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PackageInfo) Reset() {
	*x = PackageInfo{}
	mi := &file_domain_delivery_common_v1_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PackageInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PackageInfo) ProtoMessage() {}

func (x *PackageInfo) ProtoReflect() protoreflect.Message {
	mi := &file_domain_delivery_common_v1_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PackageInfo.ProtoReflect.Descriptor instead.
func (*PackageInfo) Descriptor() ([]byte, []int) {
	return file_domain_delivery_common_v1_common_proto_rawDescGZIP(), []int{3}
}

func (x *PackageInfo) GetWeightKg() float64 {
	if x != nil {
		return x.WeightKg
	}
	return 0
}

// WorkHours represents courier working hours
type WorkHours struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartTime     string                 `protobuf:"bytes,1,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`      // "09:00" format
	EndTime       string                 `protobuf:"bytes,2,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`            // "18:00" format
	WorkDays      []int32                `protobuf:"varint,3,rep,packed,name=work_days,json=workDays,proto3" json:"work_days,omitempty"` // [1,2,3,4,5] - Monday to Friday
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkHours) Reset() {
	*x = WorkHours{}
	mi := &file_domain_delivery_common_v1_common_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkHours) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkHours) ProtoMessage() {}

func (x *WorkHours) ProtoReflect() protoreflect.Message {
	mi := &file_domain_delivery_common_v1_common_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkHours.ProtoReflect.Descriptor instead.
func (*WorkHours) Descriptor() ([]byte, []int) {
	return file_domain_delivery_common_v1_common_proto_rawDescGZIP(), []int{4}
}

func (x *WorkHours) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *WorkHours) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *WorkHours) GetWorkDays() []int32 {
	if x != nil {
		return x.WorkDays
	}
	return nil
}

// NotDeliveredDetails contains reason and optional description (required if reason == OTHER)
type NotDeliveredDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        NotDeliveredReason     `protobuf:"varint,1,opt,name=reason,proto3,enum=domain.delivery.common.v1.NotDeliveredReason" json:"reason,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"` // required if reason == OTHER
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotDeliveredDetails) Reset() {
	*x = NotDeliveredDetails{}
	mi := &file_domain_delivery_common_v1_common_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotDeliveredDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotDeliveredDetails) ProtoMessage() {}

func (x *NotDeliveredDetails) ProtoReflect() protoreflect.Message {
	mi := &file_domain_delivery_common_v1_common_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotDeliveredDetails.ProtoReflect.Descriptor instead.
func (*NotDeliveredDetails) Descriptor() ([]byte, []int) {
	return file_domain_delivery_common_v1_common_proto_rawDescGZIP(), []int{5}
}

func (x *NotDeliveredDetails) GetReason() NotDeliveredReason {
	if x != nil {
		return x.Reason
	}
	return NotDeliveredReason_NOT_DELIVERED_REASON_UNSPECIFIED
}

func (x *NotDeliveredDetails) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

var File_domain_delivery_common_v1_common_proto protoreflect.FileDescriptor

const file_domain_delivery_common_v1_common_proto_rawDesc = "" +
	"\n" +
	"&domain/delivery/common/v1/common.proto\x12\x19domain.delivery.common.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xaa\x01\n" +
	"\aAddress\x12\x16\n" +
	"\x06street\x18\x01 \x01(\tR\x06street\x12\x12\n" +
	"\x04city\x18\x02 \x01(\tR\x04city\x12\x1f\n" +
	"\vpostal_code\x18\x03 \x01(\tR\n" +
	"postalCode\x12\x18\n" +
	"\acountry\x18\x04 \x01(\tR\acountry\x12\x1a\n" +
	"\blatitude\x18\x05 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x06 \x01(\x01R\tlongitude\"\xea\x01\n" +
	"\bLocation\x12\x1a\n" +
	"\blatitude\x18\x01 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x02 \x01(\x01R\tlongitude\x12\x1a\n" +
	"\baccuracy\x18\x03 \x01(\x01R\baccuracy\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x19\n" +
	"\x05speed\x18\x05 \x01(\x01H\x00R\x05speed\x88\x01\x01\x12\x1d\n" +
	"\aheading\x18\x06 \x01(\x01H\x01R\aheading\x88\x01\x01B\b\n" +
	"\x06_speedB\n" +
	"\n" +
	"\b_heading\"\x82\x01\n" +
	"\x0eDeliveryPeriod\x129\n" +
	"\n" +
	"start_time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\"*\n" +
	"\vPackageInfo\x12\x1b\n" +
	"\tweight_kg\x18\x01 \x01(\x01R\bweightKg\"b\n" +
	"\tWorkHours\x12\x1d\n" +
	"\n" +
	"start_time\x18\x01 \x01(\tR\tstartTime\x12\x19\n" +
	"\bend_time\x18\x02 \x01(\tR\aendTime\x12\x1b\n" +
	"\twork_days\x18\x03 \x03(\x05R\bworkDays\"~\n" +
	"\x13NotDeliveredDetails\x12E\n" +
	"\x06reason\x18\x01 \x01(\x0e2-.domain.delivery.common.v1.NotDeliveredReasonR\x06reason\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription*N\n" +
	"\bPriority\x12\x18\n" +
	"\x14PRIORITY_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fPRIORITY_NORMAL\x10\x01\x12\x13\n" +
	"\x0fPRIORITY_URGENT\x10\x02*\x8a\x02\n" +
	"\rPackageStatus\x12\x1e\n" +
	"\x1aPACKAGE_STATUS_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17PACKAGE_STATUS_ACCEPTED\x10\x01\x12\x1a\n" +
	"\x16PACKAGE_STATUS_IN_POOL\x10\x02\x12\x1b\n" +
	"\x17PACKAGE_STATUS_ASSIGNED\x10\x03\x12\x1d\n" +
	"\x19PACKAGE_STATUS_IN_TRANSIT\x10\x04\x12\x1c\n" +
	"\x18PACKAGE_STATUS_DELIVERED\x10\x05\x12 \n" +
	"\x1cPACKAGE_STATUS_NOT_DELIVERED\x10\x06\x12$\n" +
	" PACKAGE_STATUS_REQUIRES_HANDLING\x10\a*\x9e\x01\n" +
	"\rCourierStatus\x12\x1e\n" +
	"\x1aCOURIER_STATUS_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aCOURIER_STATUS_UNAVAILABLE\x10\x01\x12\x17\n" +
	"\x13COURIER_STATUS_FREE\x10\x02\x12\x17\n" +
	"\x13COURIER_STATUS_BUSY\x10\x03\x12\x1b\n" +
	"\x17COURIER_STATUS_ARCHIVED\x10\x04*\x9e\x01\n" +
	"\rTransportType\x12\x1e\n" +
	"\x1aTRANSPORT_TYPE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16TRANSPORT_TYPE_WALKING\x10\x01\x12\x1a\n" +
	"\x16TRANSPORT_TYPE_BICYCLE\x10\x02\x12\x1d\n" +
	"\x19TRANSPORT_TYPE_MOTORCYCLE\x10\x03\x12\x16\n" +
	"\x12TRANSPORT_TYPE_CAR\x10\x04*s\n" +
	"\x0eDeliveryStatus\x12\x1f\n" +
	"\x1bDELIVERY_STATUS_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19DELIVERY_STATUS_DELIVERED\x10\x01\x12!\n" +
	"\x1dDELIVERY_STATUS_NOT_DELIVERED\x10\x02*\xb0\x02\n" +
	"\x12NotDeliveredReason\x12$\n" +
	" NOT_DELIVERED_REASON_UNSPECIFIED\x10\x00\x12/\n" +
	"+NOT_DELIVERED_REASON_CUSTOMER_NOT_AVAILABLE\x10\x01\x12&\n" +
	"\"NOT_DELIVERED_REASON_WRONG_ADDRESS\x10\x02\x12)\n" +
	"%NOT_DELIVERED_REASON_CUSTOMER_REFUSED\x10\x03\x12&\n" +
	"\"NOT_DELIVERED_REASON_ACCESS_DENIED\x10\x04\x12(\n" +
	"$NOT_DELIVERED_REASON_PACKAGE_DAMAGED\x10\x05\x12\x1e\n" +
	"\x1aNOT_DELIVERED_REASON_OTHER\x10\x06B\xf9\x01\n" +
	"\x1dcom.domain.delivery.common.v1B\vCommonProtoP\x01ZDgithub.com/shortlink-org/shop/oms/internal/domain/delivery/common/v1\xa2\x02\x03DDC\xaa\x02\x19Domain.Delivery.Common.V1\xca\x02\x19Domain\\Delivery\\Common\\V1\xe2\x02%Domain\\Delivery\\Common\\V1\\GPBMetadata\xea\x02\x1cDomain::Delivery::Common::V1b\x06proto3"

var (
	file_domain_delivery_common_v1_common_proto_rawDescOnce sync.Once
	file_domain_delivery_common_v1_common_proto_rawDescData []byte
)

func file_domain_delivery_common_v1_common_proto_rawDescGZIP() []byte {
	file_domain_delivery_common_v1_common_proto_rawDescOnce.Do(func() {
		file_domain_delivery_common_v1_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_domain_delivery_common_v1_common_proto_rawDesc), len(file_domain_delivery_common_v1_common_proto_rawDesc)))
	})
	return file_domain_delivery_common_v1_common_proto_rawDescData
}

var file_domain_delivery_common_v1_common_proto_enumTypes = make([]protoimpl.EnumInfo, 6)
var file_domain_delivery_common_v1_common_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_domain_delivery_common_v1_common_proto_goTypes = []any{
	(Priority)(0),                 // 0: domain.delivery.common.v1.Priority
	(PackageStatus)(0),            // 1: domain.delivery.common.v1.PackageStatus
	(CourierStatus)(0),            // 2: domain.delivery.common.v1.CourierStatus
	(TransportType)(0),            // 3: domain.delivery.common.v1.TransportType
	(DeliveryStatus)(0),           // 4: domain.delivery.common.v1.DeliveryStatus
	(NotDeliveredReason)(0),       // 5: domain.delivery.common.v1.NotDeliveredReason
	(*Address)(nil),               // 6: domain.delivery.common.v1.Address
	(*Location)(nil),              // 7: domain.delivery.common.v1.Location
	(*DeliveryPeriod)(nil),        // 8: domain.delivery.common.v1.DeliveryPeriod
	(*PackageInfo)(nil),           // 9: domain.delivery.common.v1.PackageInfo
	(*WorkHours)(nil),             // 10: domain.delivery.common.v1.WorkHours
	(*NotDeliveredDetails)(nil),   // 11: domain.delivery.common.v1.NotDeliveredDetails
	(*timestamppb.Timestamp)(nil), // 12: google.protobuf.Timestamp
}
var file_domain_delivery_common_v1_common_proto_depIdxs = []int32{
	12, // 0: domain.delivery.common.v1.Location.timestamp:type_name -> google.protobuf.Timestamp
	12, // 1: domain.delivery.common.v1.DeliveryPeriod.start_time:type_name -> google.protobuf.Timestamp
	12, // 2: domain.delivery.common.v1.DeliveryPeriod.end_time:type_name -> google.protobuf.Timestamp
	5,  // 3: domain.delivery.common.v1.NotDeliveredDetails.reason:type_name -> domain.delivery.common.v1.NotDeliveredReason
	4,  // [4:4] is the sub-list for method output_type
	4,  // [4:4] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_domain_delivery_common_v1_common_proto_init() }
func file_domain_delivery_common_v1_common_proto_init() {
	if File_domain_delivery_common_v1_common_proto != nil {
		return
	}
	file_domain_delivery_common_v1_common_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_domain_delivery_common_v1_common_proto_rawDesc), len(file_domain_delivery_common_v1_common_proto_rawDesc)),
			NumEnums:      6,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_domain_delivery_common_v1_common_proto_goTypes,
		DependencyIndexes: file_domain_delivery_common_v1_common_proto_depIdxs,
		EnumInfos:         file_domain_delivery_common_v1_common_proto_enumTypes,
		MessageInfos:      file_domain_delivery_common_v1_common_proto_msgTypes,
	}.Build()
	File_domain_delivery_common_v1_common_proto = out.File
	file_domain_delivery_common_v1_common_proto_goTypes = nil
	file_domain_delivery_common_v1_common_proto_depIdxs = nil
}
