// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package crud

import (
	"github.com/jackc/pgx/v5/pgtype"
)

// Customer orders
type OmsOrder struct {
	ID         pgtype.UUID
	CustomerID pgtype.UUID
	// Order status: PENDING, PROCESSING, COMPLETED, CANCELLED
	Status string
	// Optimistic concurrency control version
	Version   int32
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

// Items in orders
type OmsOrderItem struct {
	OrderID  pgtype.UUID
	GoodID   pgtype.UUID
	Quantity int32
	Price    pgtype.Numeric
}
