// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package crud

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

// Customer orders
type OmsOrder struct {
	ID         uuid.UUID
	CustomerID uuid.UUID
	// Order status: PENDING, PROCESSING, COMPLETED, CANCELLED
	Status string
	// Optimistic concurrency control version
	Version   int32
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

// Items in orders
type OmsOrderItem struct {
	OrderID  uuid.UUID
	GoodID   uuid.UUID
	Quantity int32
	Price    decimal.Decimal
}
