// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package crud

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

// Customer orders
type OmsOrder struct {
	ID         uuid.UUID
	CustomerID uuid.UUID
	// Order status: PENDING, PROCESSING, COMPLETED, CANCELLED
	Status string
	// Optimistic concurrency control version
	Version   int32
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

// Delivery information for orders
type OmsOrderDeliveryInfo struct {
	OrderID uuid.UUID
	// Street address for package pickup
	PickupStreet     pgtype.Text
	PickupCity       pgtype.Text
	PickupPostalCode pgtype.Text
	PickupCountry    pgtype.Text
	PickupLatitude   pgtype.Numeric
	PickupLongitude  pgtype.Numeric
	// Street address for package delivery
	DeliveryStreet     string
	DeliveryCity       string
	DeliveryPostalCode pgtype.Text
	DeliveryCountry    string
	DeliveryLatitude   pgtype.Numeric
	DeliveryLongitude  pgtype.Numeric
	// Start of desired delivery time window
	PeriodStart pgtype.Timestamptz
	// End of desired delivery time window
	PeriodEnd  pgtype.Timestamptz
	WeightKg   pgtype.Numeric
	Dimensions pgtype.Text
	// Delivery priority: NORMAL, URGENT
	Priority string
	// Package ID assigned by delivery service
	PackageID pgtype.UUID
}

// Items in orders
type OmsOrderItem struct {
	OrderID  uuid.UUID
	GoodID   uuid.UUID
	Quantity int32
	Price    decimal.Decimal
}
