"""Django settings for admin project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

import environ
from django.utils.csp import CSP

env = environ.Env()

# GDAL/GEOS library paths for GeoDjango
# These are required for django.contrib.gis to find the libraries
GDAL_LIBRARY_PATH = env("GDAL_LIBRARY_PATH", default=None)
GEOS_LIBRARY_PATH = env("GEOS_LIBRARY_PATH", default=None)

# Read .env file if it exists
environ.Env.read_env(os.path.join(Path(__file__).resolve().parent.parent, ".env"))

ORY_SDK_URL = env("ORY_SDK_URL", default="http://127.0.0.1:4433")
ORY_UI_URL = env("ORY_UI_URL", default="http://127.0.0.1:3000/next/auth")
LOGIN_URL = env("LOGIN_URL", default="http://127.0.0.1:3000/next/auth/login")

# Delivery Service gRPC configuration
DELIVERY_GRPC_HOST = env("DELIVERY_GRPC_HOST", default="localhost:50051")

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-q6%&)a&ky2h5wr$$op*x_j=)0wh5d43l&a^+#==(3o@erjw*&s"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env("DEBUG", default=True)

ALLOWED_HOSTS = [
    "*",  # Allow all hosts
]


# Application definition

INSTALLED_APPS = [
    "django_admin_tailwind",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.gis",  # GeoDjango
    "django_prometheus",
    "debug_toolbar",
    # django_ory_auth removed - using Oathkeeper header-based auth instead
    # See ADR: docs/ADR/decisions/0005-oathkeeper-auth.md
    "health_check",
    "health_check.db",
    "health_check.cache",
    "health_check.contrib.migrations",
    "rest_framework",
    "mapwidgets",  # Django Map Widgets for GeoDjango
    "domain.goods",
    "domain.offices",
    "domain.couriers",
    "drf_spectacular",
]

MIDDLEWARE = [
    "admin.json_log_middleware.JsonLogMiddleware",
    "django_prometheus.middleware.PrometheusBeforeMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",  # Serve static files in production
    "django.middleware.csp.ContentSecurityPolicyMiddleware",  # CSP middleware (Django 6.0+)
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "admin.remote_user_middleware.OathkeeperRemoteUserMiddleware",  # Oathkeeper X-User-ID header auth
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "debug_toolbar.middleware.DebugToolbarMiddleware",
    "django_prometheus.middleware.PrometheusAfterMiddleware",
]

ROOT_URLCONF = "admin.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.template.context_processors.csp",  # CSP nonce context processor (Django 6.0+)
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "admin.ory_context.processor",
            ],
        },
    },
]

WSGI_APPLICATION = "admin.wsgi.application"


# CSRF
CSRF_COOKIE_DOMAIN = env("CSRF_COOKIE_DOMAIN", default=None)
CSRF_COOKIE_SECURE = env.bool("CSRF_COOKIE_SECURE", default=False)
CSRF_TRUSTED_ORIGINS = [
    "http://127.0.0.1:8000",
    "http://localhost:8000",
    "https://shortlink.best",
    "https://shop.shortlink.best",  # Django admin hostname
]

# Content Security Policy (CSP)
# https://docs.djangoproject.com/en/6.0/ref/middleware/#content-security-policy
# https://docs.djangoproject.com/en/6.0/howto/csp/
SECURE_CSP = {
    "default-src": [CSP.SELF],
    "script-src": [
        CSP.SELF,
        CSP.NONCE,
        CSP.UNSAFE_EVAL,
        "https://cdn.tailwindcss.com",
        "https://cdn.jsdelivr.net",
        "https://unpkg.com",  # Leaflet
    ],
    "style-src": [CSP.SELF, CSP.UNSAFE_INLINE],  # Tailwind requires unsafe-inline for styles
    "img-src": [
        CSP.SELF,
        "data:",
        "https:",
        "https://*.tile.openstreetmap.org",  # OSM tiles
    ],
    "font-src": [CSP.SELF, "https://fonts.gstatic.com"],
    "connect-src": [CSP.SELF, "https://*.tile.openstreetmap.org"],
    "frame-ancestors": [CSP.SELF],
    "base-uri": [CSP.SELF],
    "form-action": [CSP.SELF],
}

# Report-only mode for CSP (useful for testing without blocking)
# SECURE_CSP_REPORT_ONLY = SECURE_CSP

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
# Using django-prometheus backend for database metrics
# https://github.com/django-commons/django-prometheus#monitoring-your-databases

DATABASES = {
    "default": {
        "ENGINE": "django.contrib.gis.db.backends.postgis",  # PostGIS for GeoDjango
        "NAME": env("POSTGRES_DB", default="shortlink"),
        "USER": env("POSTGRES_USER", default="postgres"),
        "PASSWORD": env("POSTGRES_PASSWORD", default="shortlink"),
        "HOST": env("POSTGRES_HOST", default="localhost"),
        "PORT": env("POSTGRES_PORT", default="5432"),
        "OPTIONS": {
            "sslmode": env("POSTGRES_SSLMODE", default="prefer"),
        },
    }
}

# Cache
# https://github.com/jazzband/django-redis

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": env("REDIS_URL", default="redis://localhost:6379/1"),
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "COMPRESSOR": "django_redis.compressors.zlib.ZlibCompressor",
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",  # Django default (for local admin)
    "admin.auth_backends.OryRemoteUserBackend",  # Oathkeeper header-based auth
]

# Remote user header for Oathkeeper authentication
# Oathkeeper injects X-User-ID header with identity.id from Kratos session
# Django converts X-User-ID to HTTP_X_USER_ID
REMOTE_USER_HEADER = "HTTP_X_USER_ID"


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "/admin/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

# WhiteNoise configuration for serving static files in production
# https://whitenoise.readthedocs.io/
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/6.0/ref/settings/#default-auto-field
# Note: Django 6.0 defaults to BigAutoField, this line can be removed
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# Debug toolbar settings
def show_toolbar(request):
    """Show the debug toolbar if the cookie "debug_enable" is set to "true" and the user is authenticated."""
    if "debug_enable" in request.COOKIES and request.user.is_authenticated:
        cookie_value = request.COOKIES["debug_enable"]
        if cookie_value == "true":
            return True
    return False


DEBUG_TOOLBAR_CONFIG = {
    "SHOW_TOOLBAR_CALLBACK": "admin.settings.show_toolbar",
}

# Prometheus
# Only export metrics when running server (not management commands)
import sys
_is_runserver = len(sys.argv) > 1 and sys.argv[1] == "runserver"
PROMETHEUS_METRICS_EXPORT_PORT = 9090 if _is_runserver else None
PROMETHEUS_METRICS_EXPORT_ADDRESS = "0.0.0.0" if _is_runserver else ""
PROMETHEUS_EXPORT_MIGRATIONS = False

# Logging
# Structured JSON logging with OpenTelemetry trace context
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "json": {
            "()": "json_log_formatter.JSONFormatter",
        },
        "verbose": {
            "format": "[{levelname}] {asctime} [{trace_id}] {name}: {message}",
            "style": "{",
        },
    },
    "filters": {
        "trace_context": {
            "()": "django.utils.log.CallbackFilter",
            "callback": lambda record: setattr(record, "trace_id", getattr(record, "trace_id", "-")) or True,
        },
    },
    "handlers": {
        "stdout": {
            "class": "logging.StreamHandler",
            "formatter": "json",
            "filters": ["trace_context"],
        },
    },
    "root": {
        "handlers": ["stdout"],
        "level": "INFO",
    },
    "loggers": {
        "django": {
            "level": "ERROR",
            "handlers": ["stdout"],
            "propagate": False,
        },
        "django.db.backends": {
            "level": "WARNING",  # Set to DEBUG to see all SQL queries
            "handlers": ["stdout"],
            "propagate": False,
        },
        "admin": {
            "level": "INFO",
            "handlers": ["stdout"],
            "propagate": False,
        },
    },
}

REST_FRAMEWORK = {
    # Use Django's standard `django.contrib.auth` permissions,
    # or allow read-only access for unauthenticated users.
    "DEFAULT_PERMISSION_CLASSES": ["rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly"],
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    # Pagination settings
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 10,
}

# Documentation settings for Swagger and ReDoc UI (drf-spectacular)
SPECTACULAR_SETTINGS = {
    "TITLE": "Shop Admin API",
    "DESCRIPTION": "API documentation for Shop Admin",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    "COMPONENT_SPLIT_REQUEST": True,
    "SERVE_PERMISSIONS": ["rest_framework.permissions.AllowAny"],
    "SWAGGER_UI_SETTINGS": {
        "deepLinking": True,
        "persistAuthorization": True,
    },
    "REDOC_UI_SETTINGS": {
        "pathInMiddlePanel": True,
        "hideDownloadButton": True,
    },
}

# Django Map Widgets configuration
# https://django-map-widgets.readthedocs.io/
MAP_WIDGETS = {
    "Leaflet": {
        "PointField": {
            "interactive": {
                "mapOptions": {
                    "zoom": 13,
                    "center": [52.52, 13.405],  # Berlin center
                    "scrollWheelZoom": True,
                },
                "tileLayer": {
                    "urlTemplate": "https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",
                    "options": {
                        "maxZoom": 19,
                        "attribution": '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a>',
                    },
                },
                "markerFitZoom": 15,
            },
        },
    },
}
