// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: workers/cart/workflow/model/cart/v1/cart.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/emptypb"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CartItem is the cart item message.
type WorkerCartItem struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Good ID
	GoodId string `protobuf:"bytes,1,opt,name=good_id,json=goodId,proto3" json:"good_id,omitempty"`
	// Quantity
	Quantity      int32 `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerCartItem) Reset() {
	*x = WorkerCartItem{}
	mi := &file_workers_cart_workflow_model_cart_v1_cart_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerCartItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerCartItem) ProtoMessage() {}

func (x *WorkerCartItem) ProtoReflect() protoreflect.Message {
	mi := &file_workers_cart_workflow_model_cart_v1_cart_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerCartItem.ProtoReflect.Descriptor instead.
func (*WorkerCartItem) Descriptor() ([]byte, []int) {
	return file_workers_cart_workflow_model_cart_v1_cart_proto_rawDescGZIP(), []int{0}
}

func (x *WorkerCartItem) GetGoodId() string {
	if x != nil {
		return x.GoodId
	}
	return ""
}

func (x *WorkerCartItem) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

var File_workers_cart_workflow_model_cart_v1_cart_proto protoreflect.FileDescriptor

const file_workers_cart_workflow_model_cart_v1_cart_proto_rawDesc = "" +
	"\n" +
	".workers/cart/workflow/model/cart/v1/cart.proto\x12#workers.cart.workflow.model.cart.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"E\n" +
	"\x0eWorkerCartItem\x12\x17\n" +
	"\agood_id\x18\x01 \x01(\tR\x06goodId\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x05R\bquantityB\xb7\x02\n" +
	"'com.workers.cart.workflow.model.cart.v1B\tCartProtoP\x01ZNgithub.com/shortlink-org/shop/oms/internal/workers/cart/workflow/model/cart/v1\xa2\x02\x05WCWMC\xaa\x02#Workers.Cart.Workflow.Model.Cart.V1\xca\x02#Workers\\Cart\\Workflow\\Model\\Cart\\V1\xe2\x02/Workers\\Cart\\Workflow\\Model\\Cart\\V1\\GPBMetadata\xea\x02(Workers::Cart::Workflow::Model::Cart::V1b\x06proto3"

var (
	file_workers_cart_workflow_model_cart_v1_cart_proto_rawDescOnce sync.Once
	file_workers_cart_workflow_model_cart_v1_cart_proto_rawDescData []byte
)

func file_workers_cart_workflow_model_cart_v1_cart_proto_rawDescGZIP() []byte {
	file_workers_cart_workflow_model_cart_v1_cart_proto_rawDescOnce.Do(func() {
		file_workers_cart_workflow_model_cart_v1_cart_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_workers_cart_workflow_model_cart_v1_cart_proto_rawDesc), len(file_workers_cart_workflow_model_cart_v1_cart_proto_rawDesc)))
	})
	return file_workers_cart_workflow_model_cart_v1_cart_proto_rawDescData
}

var file_workers_cart_workflow_model_cart_v1_cart_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_workers_cart_workflow_model_cart_v1_cart_proto_goTypes = []any{
	(*WorkerCartItem)(nil), // 0: workers.cart.workflow.model.cart.v1.WorkerCartItem
}
var file_workers_cart_workflow_model_cart_v1_cart_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_workers_cart_workflow_model_cart_v1_cart_proto_init() }
func file_workers_cart_workflow_model_cart_v1_cart_proto_init() {
	if File_workers_cart_workflow_model_cart_v1_cart_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_workers_cart_workflow_model_cart_v1_cart_proto_rawDesc), len(file_workers_cart_workflow_model_cart_v1_cart_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_workers_cart_workflow_model_cart_v1_cart_proto_goTypes,
		DependencyIndexes: file_workers_cart_workflow_model_cart_v1_cart_proto_depIdxs,
		MessageInfos:      file_workers_cart_workflow_model_cart_v1_cart_proto_msgTypes,
	}.Build()
	File_workers_cart_workflow_model_cart_v1_cart_proto = out.File
	file_workers_cart_workflow_model_cart_v1_cart_proto_goTypes = nil
	file_workers_cart_workflow_model_cart_v1_cart_proto_depIdxs = nil
}
