{{- if .Values.authorizationPolicy.enabled }}
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: {{ include "helpers.fullname" . }}-require-jwt
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "helpers.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "shortlink-common.matchLabels" . | nindent 6 }}
  action: ALLOW
  rules:
    # Allow health checks (kubelet) and metrics (Prometheus) without authorization
    - to:
        - operation:
            paths: ["/grpc.health.v1.Health/*"]
    - to:
        - operation:
            ports: ["9090"]
    # Allow all gRPC requests on port 50051
    # Security is enforced by NetworkPolicy (only shortlink-shop, istio-ingress, temporal namespaces allowed)
    - to:
        - operation:
            ports: ["50051"]
    # Allow requests with valid JWT (for external calls through ingress with JWT)
    - from:
        - source:
            requestPrincipals: ["*"]
{{- end }}
