{{- if .Values.requestAuthentication.enabled }}
apiVersion: security.istio.io/v1
kind: RequestAuthentication
metadata:
  name: {{ include "helpers.fullname" . }}
  labels:
    {{- include "helpers.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "shortlink-common.matchLabels" . | nindent 6 }}
  jwtRules:
    - issuer: {{ .Values.requestAuthentication.issuer | quote }}
      jwksUri: {{ .Values.requestAuthentication.jwksUri | quote }}
      {{- if .Values.requestAuthentication.forwardOriginalToken }}
      forwardOriginalToken: {{ .Values.requestAuthentication.forwardOriginalToken }}
      {{- end }}
{{- end }}
