// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package service

type Address struct {
	Street     *string  `json:"street,omitempty"`
	City       *string  `json:"city,omitempty"`
	PostalCode *string  `json:"postalCode,omitempty"`
	Country    *string  `json:"country,omitempty"`
	Latitude   *float64 `json:"latitude,omitempty"`
	Longitude  *float64 `json:"longitude,omitempty"`
}

type DeliveryCourier struct {
	CourierID       *string           `json:"courierId,omitempty"`
	Name            *string           `json:"name,omitempty"`
	Phone           *string           `json:"phone,omitempty"`
	TransportType   *string           `json:"transportType,omitempty"`
	Status          *string           `json:"status,omitempty"`
	CurrentLocation *DeliveryLocation `json:"currentLocation,omitempty"`
	LastActiveAt    *string           `json:"lastActiveAt,omitempty"`
}

type DeliveryLocation struct {
	Latitude  *float64 `json:"latitude,omitempty"`
	Longitude *float64 `json:"longitude,omitempty"`
}

type DeliveryTracking struct {
	OrderID                   *string          `json:"orderId,omitempty"`
	PackageID                 *string          `json:"packageId,omitempty"`
	Status                    *string          `json:"status,omitempty"`
	Courier                   *DeliveryCourier `json:"courier,omitempty"`
	EstimatedMinutesRemaining *int             `json:"estimatedMinutesRemaining,omitempty"`
	DistanceKmRemaining       *float64         `json:"distanceKmRemaining,omitempty"`
	EstimatedArrivalAt        *string          `json:"estimatedArrivalAt,omitempty"`
	AssignedAt                *string          `json:"assignedAt,omitempty"`
	DeliveredAt               *string          `json:"deliveredAt,omitempty"`
}

type Query struct {
}

type RandomAddressResponse struct {
	Address *Address `json:"address,omitempty"`
}

type Subscription struct {
}
