package service

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.88

import (
	"context"
	"io"
)

// RandomAddress is the resolver for the randomAddress field.
func (r *queryResolver) RandomAddress(ctx context.Context) (*RandomAddressResponse, error) {
	resp, err := r.Service.getRandomAddress(ctx, operationHeaders(ctx))
	if err != nil {
		return nil, err
	}

	return randomAddressToGraph(resp), nil
}

// DeliveryTracking is the resolver for the deliveryTracking field.
func (r *queryResolver) DeliveryTracking(ctx context.Context, orderID string) (*DeliveryTracking, error) {
	resp, err := r.Service.getOrderTracking(ctx, operationHeaders(ctx), orderID)
	if err != nil {
		return nil, err
	}

	return deliveryTrackingToGraph(resp), nil
}

// DeliveryTrackingUpdated is the resolver for the deliveryTrackingUpdated field.
func (r *subscriptionResolver) DeliveryTrackingUpdated(ctx context.Context, orderID string) (<-chan *DeliveryTracking, error) {
	updates := make(chan *DeliveryTracking, 1)
	headers := operationHeaders(ctx)
	stream, err := r.Service.subscribeOrderTracking(ctx, headers, orderID)
	if err != nil {
		return nil, err
	}

	go func() {
		defer close(updates)

		for {
			snapshot, err := stream.Recv()
			if err != nil {
				if err == io.EOF || ctx.Err() != nil {
					return
				}

				r.Service.logger.Warn("delivery tracking subscription stream failed", "order_id", orderID, "error", err)
				return
			}

			select {
			case updates <- deliveryTrackingToGraph(snapshot):
			case <-ctx.Done():
				return
			}
		}
	}()

	return updates, nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Subscription returns SubscriptionResolver implementation.
func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
