// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package oms_di

import (
	"context"
	"github.com/authzed/authzed-go/v1"
	"github.com/google/wire"
	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/redis/rueidis"
	"github.com/shortlink-org/go-sdk/auth/permission"
	"github.com/shortlink-org/go-sdk/config"
	"github.com/shortlink-org/go-sdk/context"
	"github.com/shortlink-org/go-sdk/db"
	"github.com/shortlink-org/go-sdk/flags"
	"github.com/shortlink-org/go-sdk/grpc"
	"github.com/shortlink-org/go-sdk/logger"
	"github.com/shortlink-org/go-sdk/observability/metrics"
	"github.com/shortlink-org/go-sdk/observability/profiling"
	"github.com/shortlink-org/go-sdk/observability/tracing"
	"github.com/shortlink-org/go-sdk/temporal"
	"github.com/shortlink-org/shop/oms/internal/boundary/ports"
	"github.com/shortlink-org/shop/oms/internal/infrastructure/index/redis"
	postgres2 "github.com/shortlink-org/shop/oms/internal/infrastructure/repository/postgres/cart"
	postgres3 "github.com/shortlink-org/shop/oms/internal/infrastructure/repository/postgres/order"
	"github.com/shortlink-org/shop/oms/internal/infrastructure/rpc/cart/v1"
	v1_2 "github.com/shortlink-org/shop/oms/internal/infrastructure/rpc/order/v1"
	"github.com/shortlink-org/shop/oms/internal/infrastructure/rpc/run"
	"github.com/shortlink-org/shop/oms/internal/usecases/cart"
	"github.com/shortlink-org/shop/oms/internal/usecases/checkout"
	"github.com/shortlink-org/shop/oms/internal/usecases/order"
	"github.com/shortlink-org/shop/oms/pkg/uow/postgres"
	"go.opentelemetry.io/otel/sdk/metric"
	"go.opentelemetry.io/otel/trace"
	"go.temporal.io/sdk/client"
)

// Injectors from wire.go:

func InitializeOMSService() (*OMSService, func(), error) {
	context, cleanup, err := ctx.New()
	if err != nil {
		return nil, nil, err
	}
	config, err := newGoSDKConfig()
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	logger, cleanup2, err := newGoSDKLogger(context, config)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	tracerProvider, cleanup3, err := newGoSDKTracer(context, logger, config)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	monitoring, cleanup4, err := newGoSDKMonitoring(context, logger, tracerProvider, config)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	pprofEndpoint, err := newGoSDKProfiling(context, logger, tracerProvider, config)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	client, err := permission.New(logger, tracerProvider, monitoring, config)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	meterProvider := monitoring.Metrics
	db, err := newDatabase(context, logger, tracerProvider, meterProvider, config)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	uoW, err := newUnitOfWork(db)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	store, err := newCartRepository(context, db)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	postgresStore, err := newOrderRepository(context, db)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	server, err := newGRPCServer(context, logger, tracerProvider, monitoring, config)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	rueidisClient, cleanup5, err := newRedisClient(config)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	cartGoodsIndex := newCartGoodsIndex(rueidisClient)
	uc, err := cart.New(logger, client, uoW, store, cartGoodsIndex)
	if err != nil {
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	cartRPC, err := v1.New(server, logger, uc)
	if err != nil {
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	response, err := NewRunRPCServer(server, cartRPC)
	if err != nil {
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	clientClient, err := temporal.New(logger, config, tracerProvider, monitoring)
	if err != nil {
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	orderUC, err := order.New(logger, client, uoW, postgresStore, clientClient)
	if err != nil {
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	orderRPC, err := v1_2.New(server, logger, orderUC)
	if err != nil {
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	checkoutUC := checkout.New(logger, uoW, store, postgresStore)
	omsService, err := NewOMSService(logger, config, monitoring, tracerProvider, pprofEndpoint, client, db, uoW, store, postgresStore, response, cartRPC, orderRPC, uc, orderUC, checkoutUC, clientClient)
	if err != nil {
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	return omsService, func() {
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}

// wire.go:

type OMSService struct {
	// Common
	Log    logger.Logger
	Config *config.Config

	// Observability
	Tracer        trace.TracerProvider
	Monitoring    *metrics.Monitoring
	PprofEndpoint profiling.PprofEndpoint

	// Security
	authPermission *authzed.Client

	// Database
	DB db.DB

	// UnitOfWork
	UoW ports.UnitOfWork

	// Repositories
	CartRepo  ports.CartRepository
	OrderRepo ports.OrderRepository

	// Delivery
	run            *run.Response
	cartRPCServer  *v1.CartRPC
	orderRPCServer *v1_2.OrderRPC

	// Applications
	CartService     *cart.UC
	OrderService    *order.UC
	CheckoutService *checkout.UC

	// Temporal
	temporalClient client.Client
}

// OMSService ==========================================================================================================
// CustomDefaultSet - DefaultSet with go-sdk packages (config, context, flags, profiling)
var CustomDefaultSet = wire.NewSet(ctx.New, flags.New, newGoSDKProfiling, permission.New)

var OMSSet = wire.NewSet(

	CustomDefaultSet,
	newGRPCServer,

	newGoSDKConfig,
	newGoSDKLogger,

	newGoSDKTracer,
	newGoSDKMonitoring,

	newDatabase, wire.FieldsOf(new(*metrics.Monitoring), "Metrics"), newRedisClient,

	newUnitOfWork, wire.Bind(new(ports.UnitOfWork), new(*postgres.UoW)), newCartRepository,
	newOrderRepository, wire.Bind(new(ports.CartRepository), new(*postgres2.Store)), wire.Bind(new(ports.OrderRepository), new(*postgres3.Store)), newCartGoodsIndex, wire.Bind(new(ports.CartGoodsIndex), new(*redis.CartGoodsIndex)), v1.New, v1_2.New, NewRunRPCServer, cart.New, order.New, checkout.New, temporal.New, NewOMSService,
)

// newGRPCServer creates a gRPC server using go-sdk/grpc
func newGRPCServer(ctx2 context.Context, log logger.Logger, tracer trace.TracerProvider, monitoring *metrics.Monitoring, cfg *config.Config) (*grpc.Server, error) {
	return grpc.InitServer(ctx2, log, tracer, monitoring.Prometheus, nil, cfg)
}

// NewRunRPCServer starts the gRPC server
func NewRunRPCServer(runRPCServer *grpc.Server, _ *v1.CartRPC) (*run.Response, error) {
	return run.Run(runRPCServer)
}

// newGoSDKConfig creates a go-sdk config instance
func newGoSDKConfig() (*config.Config, error) {
	return config.New()
}

// newGoSDKLogger creates a go-sdk logger instance for observability
func newGoSDKLogger(ctx2 context.Context, cfg *config.Config) (logger.Logger, func(), error) {
	return logger.NewDefault(ctx2, cfg)
}

// newGoSDKTracer creates a tracer using go-sdk observability
func newGoSDKTracer(ctx2 context.Context, log logger.Logger, cfg *config.Config) (trace.TracerProvider, func(), error) {
	return tracing.New(ctx2, log, cfg)
}

// newGoSDKMonitoring creates monitoring using go-sdk observability
func newGoSDKMonitoring(ctx2 context.Context, log logger.Logger, tracer trace.TracerProvider, cfg *config.Config) (*metrics.Monitoring, func(), error) {
	return metrics.New(ctx2, log, tracer, cfg)
}

// newGoSDKProfiling creates profiling endpoint using go-sdk observability
func newGoSDKProfiling(ctx2 context.Context, log logger.Logger, tracer trace.TracerProvider, cfg *config.Config) (profiling.PprofEndpoint, error) {
	return profiling.New(ctx2, log, tracer, cfg)
}

// newDatabase creates a database connection using go-sdk/db
func newDatabase(ctx2 context.Context, log logger.Logger, tracer trace.TracerProvider, meterProvider *metric.MeterProvider, cfg *config.Config) (db.DB, error) {
	return db.New(ctx2, log, tracer, meterProvider, cfg)
}

// newUnitOfWork creates a PostgreSQL UnitOfWork
func newUnitOfWork(store db.DB) (*postgres.UoW, error) {
	pool, ok := store.GetConn().(*pgxpool.Pool)
	if !ok {
		return nil, db.ErrGetConnection
	}
	return postgres.New(pool), nil
}

// newCartRepository creates a PostgreSQL cart repository
func newCartRepository(ctx2 context.Context, store db.DB) (*postgres2.Store, error) {
	return postgres2.New(ctx2, store)
}

// newOrderRepository creates a PostgreSQL order repository
func newOrderRepository(ctx2 context.Context, store db.DB) (*postgres3.Store, error) {
	return postgres3.New(ctx2, store)
}

// newRedisClient creates a Redis client using rueidis
func newRedisClient(cfg *config.Config) (rueidis.Client, func(), error) {

	redisURI := cfg.GetString("STORE_REDIS_URI")
	if redisURI == "" {
		redisURI = "localhost:6379"
	}
	client2, err := rueidis.NewClient(rueidis.ClientOption{
		InitAddress: []string{redisURI},
	})
	if err != nil {
		return nil, nil, err
	}

	cleanup := func() {
		client2.
			Close()
	}

	return client2, cleanup, nil
}

// newCartGoodsIndex creates a Redis-backed cart goods index
func newCartGoodsIndex(client2 rueidis.Client) *redis.CartGoodsIndex {
	return redis.New(client2)
}

func NewOMSService(

	log logger.Logger, config2 *config.Config,

	monitoring *metrics.Monitoring,
	tracer trace.TracerProvider,
	pprofHTTP profiling.PprofEndpoint,

	authPermission *authzed.Client,

	database db.DB,

	unitOfWork ports.UnitOfWork,

	cartRepository ports.CartRepository,
	orderRepository ports.OrderRepository, run2 *run.Response,
	cartRPCServer *v1.CartRPC,
	orderRPCServer *v1_2.OrderRPC,

	cartService *cart.UC,
	orderService *order.UC,
	checkoutService *checkout.UC,

	temporalClient client.Client,
) (*OMSService, error) {
	return &OMSService{

		Log:    log,
		Config: config2,

		Tracer:        tracer,
		Monitoring:    monitoring,
		PprofEndpoint: pprofHTTP,

		DB: database,

		UoW: unitOfWork,

		CartRepo:  cartRepository,
		OrderRepo: orderRepository,

		run:            run2,
		cartRPCServer:  cartRPCServer,
		orderRPCServer: orderRPCServer,

		CartService:     cartService,
		OrderService:    orderService,
		CheckoutService: checkoutService,

		temporalClient: temporalClient,
	}, nil
}
