// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package oms_di

import (
	"github.com/authzed/authzed-go/v1"
	"github.com/google/wire"
	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/redis/rueidis"
	"github.com/shortlink-org/go-sdk/auth/permission"
	"github.com/shortlink-org/go-sdk/config"
	"github.com/shortlink-org/go-sdk/cqrs/bus"
	"github.com/shortlink-org/go-sdk/db"
	"github.com/shortlink-org/go-sdk/flags"
	"github.com/shortlink-org/go-sdk/flight_trace"
	"github.com/shortlink-org/go-sdk/grpc"
	"github.com/shortlink-org/go-sdk/logger"
	"github.com/shortlink-org/go-sdk/observability/metrics"
	"github.com/shortlink-org/go-sdk/observability/profiling"
	"github.com/shortlink-org/go-sdk/observability/tracing"
	"github.com/shortlink-org/go-sdk/temporal"
	"github.com/shortlink-org/shop/oms/internal/domain/ports"
	"github.com/shortlink-org/shop/oms/internal/infrastructure/kafka"
	"github.com/shortlink-org/shop/oms/internal/infrastructure/repository/postgres/cart"
	postgres2 "github.com/shortlink-org/shop/oms/internal/infrastructure/repository/postgres/order"
	"github.com/shortlink-org/shop/oms/internal/infrastructure/repository/redis/cart_goods_index"
	"github.com/shortlink-org/shop/oms/internal/infrastructure/repository/redis/leaderboard"
	"github.com/shortlink-org/shop/oms/internal/infrastructure/rpc/cart/v1"
	v1_2 "github.com/shortlink-org/shop/oms/internal/infrastructure/rpc/order/v1"
	"github.com/shortlink-org/shop/oms/internal/infrastructure/rpc/run"
	"github.com/shortlink-org/shop/oms/internal/usecases/cart/command/add_items"
	"github.com/shortlink-org/shop/oms/internal/usecases/cart/command/remove_items"
	"github.com/shortlink-org/shop/oms/internal/usecases/cart/command/reset"
	"github.com/shortlink-org/shop/oms/internal/usecases/cart/query/get"
	get3 "github.com/shortlink-org/shop/oms/internal/usecases/leaderboard/query/get"
	"github.com/shortlink-org/shop/oms/internal/usecases/order/command/cancel"
	"github.com/shortlink-org/shop/oms/internal/usecases/order/command/create"
	"github.com/shortlink-org/shop/oms/internal/usecases/order/command/create_order_from_cart"
	"github.com/shortlink-org/shop/oms/internal/usecases/order/command/request_delivery"
	"github.com/shortlink-org/shop/oms/internal/usecases/order/command/update_delivery_info"
	get2 "github.com/shortlink-org/shop/oms/internal/usecases/order/query/get"
	"github.com/shortlink-org/shop/oms/internal/usecases/order/query/list"
	"github.com/shortlink-org/shop/oms/internal/workers/cart/cart_worker"
	"github.com/shortlink-org/shop/oms/internal/workers/order/activities"
	"github.com/shortlink-org/shop/oms/internal/workers/order/order_worker"
	postgres3 "github.com/shortlink-org/shop/oms/pkg/uow/postgres"
	"go.opentelemetry.io/otel/trace"
	"go.temporal.io/sdk/client"
)

// Injectors from wire.go:

func InitializeOMSService() (*OMSService, func(), error) {
	context, cleanup, err := newSDKContext()
	if err != nil {
		return nil, nil, err
	}
	config, err := provideOMSConfig()
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	loggerLogger, cleanup2, err := logger.NewDefault(context, config)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	tracerProvider, cleanup3, err := tracing.New(context, loggerLogger, config)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	monitoring, cleanup4, err := metrics.New(context, loggerLogger, tracerProvider, config)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	pprofEndpoint, err := profiling.New(context, loggerLogger, tracerProvider, config)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	client, err := permission.New(loggerLogger, tracerProvider, monitoring, config)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	meterProvider := monitoring.Metrics
	v := newDBOptions()
	dbDB, err := db.New(context, loggerLogger, tracerProvider, meterProvider, config, v...)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	uoW, err := newUnitOfWork(dbDB)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	store, err := postgres.New(context, dbDB)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	postgresStore, err := postgres2.New(context, dbDB)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	rueidisClient, cleanup5, err := newRedisClient(config)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	leaderboardStore := leaderboard.New(rueidisClient)
	eventBus, cleanup6, err := newEventBus(context, config, loggerLogger, dbDB, monitoring)
	if err != nil {
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	eventPublisher := bus.NewEventPublisher(eventBus)
	deliveryClient, cleanup7, err := NewDeliveryClient(config, loggerLogger)
	if err != nil {
		cleanup6()
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	deliveryConsumer, cleanup8, err := NewDeliveryConsumer(context, config, loggerLogger, uoW, postgresStore, postgresStore, eventPublisher)
	if err != nil {
		cleanup7()
		cleanup6()
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	leaderboardConsumer, cleanup9, err := NewLeaderboardConsumer(context, config, loggerLogger, uoW, postgresStore, leaderboardStore)
	if err != nil {
		cleanup8()
		cleanup7()
		cleanup6()
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	pricerClient, cleanup10, err := NewPricerClient(config, loggerLogger)
	if err != nil {
		cleanup9()
		cleanup8()
		cleanup7()
		cleanup6()
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	registry := monitoring.Prometheus
	recorder, err := flight_trace.New(context, config)
	if err != nil {
		cleanup10()
		cleanup9()
		cleanup8()
		cleanup7()
		cleanup6()
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	server, err := grpc.InitServer(context, loggerLogger, tracerProvider, registry, recorder, config)
	if err != nil {
		cleanup10()
		cleanup9()
		cleanup8()
		cleanup7()
		cleanup6()
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	handler, err := add_items.NewHandler(loggerLogger, uoW, store, eventPublisher)
	if err != nil {
		cleanup10()
		cleanup9()
		cleanup8()
		cleanup7()
		cleanup6()
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	remove_itemsHandler, err := remove_items.NewHandler(loggerLogger, uoW, store, eventPublisher)
	if err != nil {
		cleanup10()
		cleanup9()
		cleanup8()
		cleanup7()
		cleanup6()
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	resetHandler, err := reset.NewHandler(loggerLogger, uoW, store, eventPublisher)
	if err != nil {
		cleanup10()
		cleanup9()
		cleanup8()
		cleanup7()
		cleanup6()
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	getHandler, err := get.NewHandler(uoW, store)
	if err != nil {
		cleanup10()
		cleanup9()
		cleanup8()
		cleanup7()
		cleanup6()
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	cartRPC, err := v1.New(server, loggerLogger, handler, remove_itemsHandler, resetHandler, getHandler)
	if err != nil {
		cleanup10()
		cleanup9()
		cleanup8()
		cleanup7()
		cleanup6()
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	response, err := NewRunRPCServer(server, cartRPC)
	if err != nil {
		cleanup10()
		cleanup9()
		cleanup8()
		cleanup7()
		cleanup6()
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	createHandler, err := create.NewHandler(loggerLogger, uoW, postgresStore, eventPublisher)
	if err != nil {
		cleanup10()
		cleanup9()
		cleanup8()
		cleanup7()
		cleanup6()
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	cancelHandler, err := cancel.NewHandler(loggerLogger, uoW, postgresStore, eventPublisher)
	if err != nil {
		cleanup10()
		cleanup9()
		cleanup8()
		cleanup7()
		cleanup6()
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	update_delivery_infoHandler, err := update_delivery_info.NewHandler(loggerLogger, uoW, postgresStore, eventPublisher)
	if err != nil {
		cleanup10()
		cleanup9()
		cleanup8()
		cleanup7()
		cleanup6()
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	create_order_from_cartHandler, err := create_order_from_cart.NewHandler(loggerLogger, uoW, store, postgresStore, eventPublisher, pricerClient)
	if err != nil {
		cleanup10()
		cleanup9()
		cleanup8()
		cleanup7()
		cleanup6()
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	handler2, err := get2.NewHandler(uoW, postgresStore)
	if err != nil {
		cleanup10()
		cleanup9()
		cleanup8()
		cleanup7()
		cleanup6()
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	listHandler, err := list.NewHandler(uoW, postgresStore)
	if err != nil {
		cleanup10()
		cleanup9()
		cleanup8()
		cleanup7()
		cleanup6()
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	handler3, err := get3.NewHandler(leaderboardStore)
	if err != nil {
		cleanup10()
		cleanup9()
		cleanup8()
		cleanup7()
		cleanup6()
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	orderRPC, err := v1_2.New(server, loggerLogger, createHandler, cancelHandler, update_delivery_infoHandler, create_order_from_cartHandler, handler2, listHandler, handler3)
	if err != nil {
		cleanup10()
		cleanup9()
		cleanup8()
		cleanup7()
		cleanup6()
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	clientClient, err := temporal.New(loggerLogger, config, tracerProvider, monitoring)
	if err != nil {
		cleanup10()
		cleanup9()
		cleanup8()
		cleanup7()
		cleanup6()
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	cartWorker, err := cart_worker.New(context, clientClient, loggerLogger)
	if err != nil {
		cleanup10()
		cleanup9()
		cleanup8()
		cleanup7()
		cleanup6()
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	request_deliveryHandler, err := request_delivery.NewHandler(loggerLogger, uoW, postgresStore, eventPublisher)
	if err != nil {
		cleanup10()
		cleanup9()
		cleanup8()
		cleanup7()
		cleanup6()
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	activitiesActivities := activities.NewWithHandlers(cancelHandler, handler2, request_deliveryHandler, deliveryClient)
	orderWorker, err := order_worker.NewWithActivities(context, clientClient, loggerLogger, activitiesActivities)
	if err != nil {
		cleanup10()
		cleanup9()
		cleanup8()
		cleanup7()
		cleanup6()
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	omsService, err := NewOMSService(loggerLogger, config, monitoring, tracerProvider, pprofEndpoint, client, dbDB, uoW, store, postgresStore, leaderboardStore, eventPublisher, deliveryClient, deliveryConsumer, leaderboardConsumer, pricerClient, response, cartRPC, orderRPC, clientClient, cartWorker, orderWorker)
	if err != nil {
		cleanup10()
		cleanup9()
		cleanup8()
		cleanup7()
		cleanup6()
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	return omsService, func() {
		cleanup10()
		cleanup9()
		cleanup8()
		cleanup7()
		cleanup6()
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}

// wire.go:

type OMSService struct {
	// Common
	Log    logger.Logger
	Config *config.Config

	// Observability
	Tracer        trace.TracerProvider
	Monitoring    *metrics.Monitoring
	PprofEndpoint profiling.PprofEndpoint

	// Security
	authPermission *authzed.Client

	// Database
	DB db.DB

	// UnitOfWork
	UoW ports.UnitOfWork

	// Repositories
	CartRepo        ports.CartRepository
	OrderRepo       ports.OrderRepository
	LeaderboardRepo ports.LeaderboardRepository

	// Delivery
	run            *run.Response
	cartRPCServer  *v1.CartRPC
	orderRPCServer *v1_2.OrderRPC

	// Event Infrastructure (go-sdk/cqrs EventBus + tx-aware outbox)
	EventPublisher ports.EventPublisher

	// Delivery Integration
	DeliveryClient      ports.DeliveryClient
	DeliveryConsumer    *kafka.DeliveryConsumer
	LeaderboardConsumer *kafka.LeaderboardConsumer

	// Pricer Integration
	PricerClient ports.PricerClient

	// Temporal
	temporalClient client.Client
	cartWorker     cart_worker.CartWorker
	orderWorker    order_worker.OrderWorker
}

// OMSService ==========================================================================================================
// CustomDefaultSet - DefaultSet with go-sdk packages (config, context, flags, profiling)
var CustomDefaultSet = wire.NewSet(
	newSDKContext, flags.New, profiling.New, permission.New,
)

var OMSSet = wire.NewSet(

	CustomDefaultSet, flight_trace.New, grpc.InitServer, provideOMSConfig, logger.NewDefault, tracing.New, metrics.New, db.New, newDBOptions, wire.FieldsOf(new(*metrics.Monitoring), "Metrics", "Prometheus"), newRedisClient,

	newUnitOfWork, wire.Bind(new(ports.UnitOfWork), new(*postgres3.UoW)), postgres.New, postgres2.New, wire.Bind(new(ports.CartRepository), new(*postgres.Store)), wire.Bind(new(ports.OrderRepository), new(*postgres2.Store)), wire.Bind(new(ports.DeliveryInboxRepository), new(*postgres2.Store)), cart_goods_index.New, wire.Bind(new(ports.CartGoodsIndex), new(*cart_goods_index.Store)), leaderboard.New, wire.Bind(new(ports.LeaderboardRepository), new(*leaderboard.Store)), newEventBus, bus.NewEventPublisher, wire.Bind(new(ports.EventPublisher), new(*bus.EventPublisher)), NewDeliveryClient,
	NewDeliveryConsumer,
	NewLeaderboardConsumer,

	NewPricerClient, add_items.NewHandler, remove_items.NewHandler, reset.NewHandler, get.NewHandler, create.NewHandler, cancel.NewHandler, request_delivery.NewHandler, update_delivery_info.NewHandler, get2.NewHandler, list.NewHandler, get3.NewHandler, create_order_from_cart.NewHandler, v1.New, v1_2.New, NewRunRPCServer, temporal.New, cart_worker.New, activities.NewWithHandlers, order_worker.NewWithActivities, NewOMSService,
)

// NewRunRPCServer starts the gRPC server
func NewRunRPCServer(runRPCServer *grpc.Server, _ *v1.CartRPC) (*run.Response, error) {
	return run.Run(runRPCServer)
}

// newUnitOfWork creates a PostgreSQL UnitOfWork
func newUnitOfWork(store db.DB) (*postgres3.UoW, error) {
	pool, ok := store.GetConn().(*pgxpool.Pool)
	if !ok {
		return nil, db.ErrGetConnection
	}
	return postgres3.New(pool), nil
}

// newRedisClient creates a Redis client using rueidis
func newRedisClient(cfg *config.Config) (rueidis.Client, func(), error) {

	redisURI := cfg.GetString("STORE_REDIS_URI")
	if redisURI == "" {
		redisURI = "localhost:6379"
	}
	client2, err := rueidis.NewClient(rueidis.ClientOption{
		InitAddress: []string{redisURI},
	})
	if err != nil {
		return nil, nil, err
	}

	cleanup := func() {
		client2.
			Close()
	}

	return client2, cleanup, nil
}

func newDBOptions() []db.Option {
	return nil
}

func NewOMSService(

	log logger.Logger, config2 *config.Config,

	monitoring *metrics.Monitoring,
	tracer trace.TracerProvider,
	pprofHTTP profiling.PprofEndpoint,

	authPermission *authzed.Client,

	database db.DB,

	unitOfWork ports.UnitOfWork,

	cartRepository ports.CartRepository,
	orderRepository ports.OrderRepository,
	leaderboardRepository ports.LeaderboardRepository,

	eventPublisher ports.EventPublisher,

	deliveryClient ports.DeliveryClient,
	deliveryConsumer *kafka.DeliveryConsumer,
	leaderboardConsumer *kafka.LeaderboardConsumer,

	pricerClient ports.PricerClient, run2 *run.Response,
	cartRPCServer *v1.CartRPC,
	orderRPCServer *v1_2.OrderRPC,

	temporalClient client.Client,
	cartWorker cart_worker.CartWorker,
	orderWorker order_worker.OrderWorker,
) (*OMSService, error) {
	return &OMSService{

		Log:    log,
		Config: config2,

		Tracer:        tracer,
		Monitoring:    monitoring,
		PprofEndpoint: pprofHTTP,

		DB: database,

		UoW: unitOfWork,

		CartRepo:        cartRepository,
		OrderRepo:       orderRepository,
		LeaderboardRepo: leaderboardRepository,

		EventPublisher: eventPublisher,

		DeliveryClient:      deliveryClient,
		DeliveryConsumer:    deliveryConsumer,
		LeaderboardConsumer: leaderboardConsumer,

		PricerClient: pricerClient,

		run:            run2,
		cartRPCServer:  cartRPCServer,
		orderRPCServer: orderRPCServer,

		temporalClient: temporalClient,
		cartWorker:     cartWorker,
		orderWorker:    orderWorker,
	}, nil
}
