// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package oms_di

import (
	"github.com/authzed/authzed-go/v1"
	"github.com/google/wire"
	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/redis/rueidis"
	"github.com/shortlink-org/go-sdk/auth/permission"
	"github.com/shortlink-org/go-sdk/config"
	"github.com/shortlink-org/go-sdk/context"
	"github.com/shortlink-org/go-sdk/db"
	"github.com/shortlink-org/go-sdk/flags"
	"github.com/shortlink-org/go-sdk/flight_trace"
	"github.com/shortlink-org/go-sdk/grpc"
	"github.com/shortlink-org/go-sdk/logger"
	"github.com/shortlink-org/go-sdk/observability/metrics"
	"github.com/shortlink-org/go-sdk/observability/profiling"
	"github.com/shortlink-org/go-sdk/observability/tracing"
	"github.com/shortlink-org/go-sdk/temporal"
	"github.com/shortlink-org/shop/oms/internal/domain/ports"
	"github.com/shortlink-org/shop/oms/internal/infrastructure/events"
	"github.com/shortlink-org/shop/oms/internal/infrastructure/repository/postgres/cart"
	postgres2 "github.com/shortlink-org/shop/oms/internal/infrastructure/repository/postgres/order"
	"github.com/shortlink-org/shop/oms/internal/infrastructure/repository/redis/cart_goods_index"
	"github.com/shortlink-org/shop/oms/internal/infrastructure/rpc/cart/v1"
	v1_2 "github.com/shortlink-org/shop/oms/internal/infrastructure/rpc/order/v1"
	"github.com/shortlink-org/shop/oms/internal/infrastructure/rpc/run"
	temporal2 "github.com/shortlink-org/shop/oms/internal/infrastructure/temporal"
	"github.com/shortlink-org/shop/oms/internal/usecases/cart/command/add_items"
	"github.com/shortlink-org/shop/oms/internal/usecases/cart/command/remove_items"
	"github.com/shortlink-org/shop/oms/internal/usecases/cart/command/reset"
	"github.com/shortlink-org/shop/oms/internal/usecases/cart/query/get"
	"github.com/shortlink-org/shop/oms/internal/usecases/checkout/command/create_order_from_cart"
	"github.com/shortlink-org/shop/oms/internal/usecases/order/command/cancel"
	"github.com/shortlink-org/shop/oms/internal/usecases/order/command/create"
	"github.com/shortlink-org/shop/oms/internal/usecases/order/command/update_delivery_info"
	get2 "github.com/shortlink-org/shop/oms/internal/usecases/order/query/get"
	"github.com/shortlink-org/shop/oms/internal/usecases/order/query/list"
	"github.com/shortlink-org/shop/oms/internal/workers/cart/cart_worker"
	"github.com/shortlink-org/shop/oms/internal/workers/order/order_worker"
	postgres3 "github.com/shortlink-org/shop/oms/pkg/uow/postgres"
	"go.opentelemetry.io/otel/trace"
	"go.temporal.io/sdk/client"
)

// Injectors from wire.go:

func InitializeOMSService() (*OMSService, func(), error) {
	context, cleanup, err := ctx.New()
	if err != nil {
		return nil, nil, err
	}
	configConfig, err := config.New()
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	loggerLogger, cleanup2, err := logger.NewDefault(context, configConfig)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	tracerProvider, cleanup3, err := tracing.New(context, loggerLogger, configConfig)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	monitoring, cleanup4, err := metrics.New(context, loggerLogger, tracerProvider, configConfig)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	pprofEndpoint, err := profiling.New(context, loggerLogger, tracerProvider, configConfig)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	client, err := permission.New(loggerLogger, tracerProvider, monitoring, configConfig)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	meterProvider := monitoring.Metrics
	dbDB, err := db.New(context, loggerLogger, tracerProvider, meterProvider, configConfig)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	uoW, err := newUnitOfWork(dbDB)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	store, err := postgres.New(context, dbDB)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	postgresStore, err := postgres2.New(context, dbDB)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	inMemoryPublisher := events.NewInMemoryPublisher()
	registry := monitoring.Prometheus
	recorder, err := flight_trace.New(context, configConfig)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	server, err := grpc.InitServer(context, loggerLogger, tracerProvider, registry, recorder, configConfig)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	rueidisClient, cleanup5, err := newRedisClient(configConfig)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	cart_goods_indexStore := cart_goods_index.New(rueidisClient)
	handler := add_items.NewHandler(loggerLogger, uoW, store, cart_goods_indexStore)
	remove_itemsHandler := remove_items.NewHandler(loggerLogger, uoW, store, cart_goods_indexStore)
	resetHandler := reset.NewHandler(loggerLogger, uoW, store, cart_goods_indexStore)
	getHandler := get.NewHandler(uoW, store)
	cartRPC, err := v1.New(server, loggerLogger, handler, remove_itemsHandler, resetHandler, getHandler)
	if err != nil {
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	response, err := NewRunRPCServer(server, cartRPC)
	if err != nil {
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	createHandler := create.NewHandler(loggerLogger, uoW, postgresStore, inMemoryPublisher)
	cancelHandler := cancel.NewHandler(loggerLogger, uoW, postgresStore, inMemoryPublisher)
	update_delivery_infoHandler := update_delivery_info.NewHandler(loggerLogger, uoW, postgresStore, inMemoryPublisher)
	create_order_from_cartHandler := create_order_from_cart.NewHandler(loggerLogger, uoW, store, postgresStore, inMemoryPublisher)
	handler2 := get2.NewHandler(uoW, postgresStore)
	listHandler := list.NewHandler(uoW, postgresStore)
	orderRPC, err := v1_2.New(server, loggerLogger, createHandler, cancelHandler, update_delivery_infoHandler, create_order_from_cartHandler, handler2, listHandler)
	if err != nil {
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	clientClient, err := temporal.New(loggerLogger, configConfig, tracerProvider, monitoring)
	if err != nil {
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	orderEventSubscriber := newOrderEventSubscriber(loggerLogger, clientClient, inMemoryPublisher)
	cartWorker, err := cart_worker.New(context, clientClient, loggerLogger)
	if err != nil {
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	orderWorker, err := order_worker.New(context, clientClient, loggerLogger)
	if err != nil {
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	omsService, err := NewOMSService(loggerLogger, configConfig, monitoring, tracerProvider, pprofEndpoint, client, dbDB, uoW, store, postgresStore, inMemoryPublisher, response, cartRPC, orderRPC, clientClient, orderEventSubscriber, cartWorker, orderWorker)
	if err != nil {
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	return omsService, func() {
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}

// wire.go:

type OMSService struct {
	// Common
	Log    logger.Logger
	Config *config.Config

	// Observability
	Tracer        trace.TracerProvider
	Monitoring    *metrics.Monitoring
	PprofEndpoint profiling.PprofEndpoint

	// Security
	authPermission *authzed.Client

	// Database
	DB db.DB

	// UnitOfWork
	UoW ports.UnitOfWork

	// Repositories
	CartRepo  ports.CartRepository
	OrderRepo ports.OrderRepository

	// Delivery
	run            *run.Response
	cartRPCServer  *v1.CartRPC
	orderRPCServer *v1_2.OrderRPC

	// Event Infrastructure
	EventPublisher *events.InMemoryPublisher

	// Temporal
	temporalClient client.Client
	cartWorker     cart_worker.CartWorker
	orderWorker    order_worker.OrderWorker
}

// OMSService ==========================================================================================================
// CustomDefaultSet - DefaultSet with go-sdk packages (config, context, flags, profiling)
var CustomDefaultSet = wire.NewSet(ctx.New, flags.New, profiling.New, permission.New)

var OMSSet = wire.NewSet(

	CustomDefaultSet, flight_trace.New, grpc.InitServer, config.New, logger.NewDefault, tracing.New, metrics.New, db.New, wire.FieldsOf(new(*metrics.Monitoring), "Metrics", "Prometheus"), newRedisClient,

	newUnitOfWork, wire.Bind(new(ports.UnitOfWork), new(*postgres3.UoW)), postgres.New, postgres2.New, wire.Bind(new(ports.CartRepository), new(*postgres.Store)), wire.Bind(new(ports.OrderRepository), new(*postgres2.Store)), cart_goods_index.New, wire.Bind(new(ports.CartGoodsIndex), new(*cart_goods_index.Store)), events.NewInMemoryPublisher, wire.Bind(new(ports.EventPublisher), new(*events.InMemoryPublisher)), add_items.NewHandler, remove_items.NewHandler, reset.NewHandler, get.NewHandler, create.NewHandler, cancel.NewHandler, update_delivery_info.NewHandler, get2.NewHandler, list.NewHandler, create_order_from_cart.NewHandler, v1.New, v1_2.New, NewRunRPCServer, temporal.New, newOrderEventSubscriber, cart_worker.New, order_worker.New, NewOMSService,
)

// NewRunRPCServer starts the gRPC server
func NewRunRPCServer(runRPCServer *grpc.Server, _ *v1.CartRPC) (*run.Response, error) {
	return run.Run(runRPCServer)
}

// newUnitOfWork creates a PostgreSQL UnitOfWork
func newUnitOfWork(store db.DB) (*postgres3.UoW, error) {
	pool, ok := store.GetConn().(*pgxpool.Pool)
	if !ok {
		return nil, db.ErrGetConnection
	}
	return postgres3.New(pool), nil
}

// newRedisClient creates a Redis client using rueidis
func newRedisClient(cfg *config.Config) (rueidis.Client, func(), error) {

	redisURI := cfg.GetString("STORE_REDIS_URI")
	if redisURI == "" {
		redisURI = "localhost:6379"
	}
	client2, err := rueidis.NewClient(rueidis.ClientOption{
		InitAddress: []string{redisURI},
	})
	if err != nil {
		return nil, nil, err
	}

	cleanup := func() {
		client2.
			Close()
	}

	return client2, cleanup, nil
}

// newOrderEventSubscriber creates and registers the order event subscriber
func newOrderEventSubscriber(log logger.Logger, temporalClient client.Client, publisher *events.InMemoryPublisher) *temporal2.OrderEventSubscriber {
	subscriber := temporal2.NewOrderEventSubscriber(log, temporalClient)
	subscriber.Register(publisher)
	return subscriber
}

func NewOMSService(

	log logger.Logger, config2 *config.Config,

	monitoring *metrics.Monitoring,
	tracer trace.TracerProvider,
	pprofHTTP profiling.PprofEndpoint,

	authPermission *authzed.Client,

	database db.DB,

	unitOfWork ports.UnitOfWork,

	cartRepository ports.CartRepository,
	orderRepository ports.OrderRepository,

	eventPublisher *events.InMemoryPublisher, run2 *run.Response,
	cartRPCServer *v1.CartRPC,
	orderRPCServer *v1_2.OrderRPC,

	temporalClient client.Client,
	_ *temporal2.OrderEventSubscriber,
	cartWorker cart_worker.CartWorker,
	orderWorker order_worker.OrderWorker,
) (*OMSService, error) {
	return &OMSService{

		Log:    log,
		Config: config2,

		Tracer:        tracer,
		Monitoring:    monitoring,
		PprofEndpoint: pprofHTTP,

		DB: database,

		UoW: unitOfWork,

		CartRepo:  cartRepository,
		OrderRepo: orderRepository,

		EventPublisher: eventPublisher,

		run:            run2,
		cartRPCServer:  cartRPCServer,
		orderRPCServer: orderRPCServer,

		temporalClient: temporalClient,
		cartWorker:     cartWorker,
		orderWorker:    orderWorker,
	}, nil
}
