SELF_DIR := $(dir $(lastword $(MAKEFILE_LIST)))

# INCLUDE ==============================================================================================================
include $(SELF_DIR)ops/Makefile/common.mk
include $(SELF_DIR)ops/Makefile/docker.mk
include $(SELF_DIR)ops/Makefile/dev.mk
