// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package courier_di

import (
	"github.com/google/wire"
	"github.com/shortlink-org/go-sdk/config"
	"github.com/shortlink-org/go-sdk/context"
	"github.com/shortlink-org/go-sdk/flags"
	"github.com/shortlink-org/go-sdk/logger"
	"github.com/shortlink-org/go-sdk/observability/metrics"
	"github.com/shortlink-org/go-sdk/observability/profiling"
	"github.com/shortlink-org/go-sdk/observability/tracing"
	"github.com/shortlink-org/shortlink/boundaries/shop/courier-emulation/internal/di/pkg"
	"github.com/shortlink-org/shortlink/boundaries/shop/courier-emulation/internal/domain/services"
	"github.com/shortlink-org/shortlink/boundaries/shop/courier-emulation/internal/infrastructure/kafka"
	"go.opentelemetry.io/otel/trace"
)

// Injectors from wire.go:

func InitializeCourierEmulationService() (*CourierEmulationService, func(), error) {
	context, cleanup, err := ctx.New()
	if err != nil {
		return nil, nil, err
	}
	configConfig, err := config.New()
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	loggerLogger, cleanup2, err := logger.NewDefault(context, configConfig)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	tracerProvider, cleanup3, err := tracing.New(context, loggerLogger, configConfig)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	monitoring, cleanup4, err := metrics.New(context, loggerLogger, tracerProvider, configConfig)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	pprofEndpoint, err := profiling.New(context, loggerLogger, tracerProvider, configConfig)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	routeGenerator, err := pkg_di.NewOSRMClient(configConfig)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	locationPublisher, cleanup5, err := pkg_di.NewLocationPublisher(configConfig, loggerLogger)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	courierSimulator := pkg_di.NewCourierSimulator(configConfig, routeGenerator, locationPublisher)
	courierEmulationService, cleanup6, err := NewCourierEmulationService(loggerLogger, configConfig, monitoring, tracerProvider, pprofEndpoint, routeGenerator, courierSimulator, locationPublisher)
	if err != nil {
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	return courierEmulationService, func() {
		cleanup6()
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}

// wire.go:

type CourierEmulationService struct {
	// Common
	Log    logger.Logger
	Config *config.Config

	// Observability
	Tracer        trace.TracerProvider
	Monitoring    *metrics.Monitoring
	PprofEndpoint profiling.PprofEndpoint

	// Domain services
	RouteGenerator   *services.RouteGenerator
	CourierSimulator *services.CourierSimulator

	// Infrastructure
	LocationPublisher *kafka.LocationPublisher
}

// DefaultSet ==========================================================================================================
var DefaultSet = wire.NewSet(ctx.New, flags.New, config.New, logger.NewDefault, tracing.New, metrics.New, profiling.New)

// CourierEmulationSet =================================================================================================
var CourierEmulationSet = wire.NewSet(

	DefaultSet, pkg_di.NewOSRMClient, pkg_di.NewCourierSimulator, pkg_di.NewLocationPublisher, NewCourierEmulationService,
)

func NewCourierEmulationService(

	log logger.Logger,
	cfg *config.Config,

	monitoring *metrics.Monitoring,
	tracer trace.TracerProvider,
	pprofHTTP profiling.PprofEndpoint,

	routeGen *services.RouteGenerator,
	simulator *services.CourierSimulator,

	publisher *kafka.LocationPublisher,
) (*CourierEmulationService, func(), error) {
	cleanup := func() {
		log.Info("Shutting down courier simulation...")

		simulator.Stop()

	}

	return &CourierEmulationService{

		Log:    log,
		Config: cfg,

		Tracer:        tracer,
		Monitoring:    monitoring,
		PprofEndpoint: pprofHTTP,

		RouteGenerator:   routeGen,
		CourierSimulator: simulator,

		LocationPublisher: publisher,
	}, cleanup, nil
}
