// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package courier_di

import (
	"github.com/google/wire"
	"github.com/shortlink-org/go-sdk/config"
	"github.com/shortlink-org/go-sdk/context"
	"github.com/shortlink-org/go-sdk/flags"
	"github.com/shortlink-org/go-sdk/logger"
	"github.com/shortlink-org/go-sdk/observability/metrics"
	"github.com/shortlink-org/go-sdk/observability/profiling"
	"github.com/shortlink-org/go-sdk/observability/tracing"
	"github.com/shortlink-org/shortlink/boundaries/shop/courier-emulation/internal/domain/services"
	"github.com/shortlink-org/shortlink/boundaries/shop/courier-emulation/internal/infrastructure/kafka"
	"go.opentelemetry.io/otel/trace"
)

// Injectors from wire.go:

func InitializeCourierEmulationService() (*CourierEmulationService, func(), error) {
	context, cleanup, err := ctx.New()
	if err != nil {
		return nil, nil, err
	}
	configConfig, err := config.New()
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	loggerLogger, cleanup2, err := logger.NewDefault(context, configConfig)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	tracerProvider, cleanup3, err := tracing.New(context, loggerLogger, configConfig)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	monitoring, cleanup4, err := metrics.New(context, loggerLogger, tracerProvider, configConfig)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	pprofEndpoint, err := profiling.New(context, loggerLogger, tracerProvider, configConfig)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	routeGenerator := newRouteGenerator(configConfig)
	locationPublisher, err := newLocationPublisher(configConfig, loggerLogger)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	courierSimulator := newCourierSimulator(configConfig, routeGenerator, locationPublisher)
	courierEmulationService, cleanup5, err := NewCourierEmulationService(loggerLogger, configConfig, monitoring, tracerProvider, pprofEndpoint, routeGenerator, courierSimulator, locationPublisher)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	return courierEmulationService, func() {
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}

// wire.go:

type CourierEmulationService struct {
	// Common
	Log    logger.Logger
	Config *config.Config

	// Observability
	Tracer        trace.TracerProvider
	Monitoring    *metrics.Monitoring
	PprofEndpoint profiling.PprofEndpoint

	// Domain services
	RouteGenerator   *services.RouteGenerator
	CourierSimulator *services.CourierSimulator

	// Infrastructure
	LocationPublisher *kafka.LocationPublisher
}

// DefaultSet ==========================================================================================================
var DefaultSet = wire.NewSet(ctx.New, flags.New, config.New, logger.NewDefault, tracing.New, metrics.New, profiling.New)

// CourierEmulationSet =================================================================================================
var CourierEmulationSet = wire.NewSet(

	DefaultSet,

	newRouteGenerator,
	newCourierSimulator,

	newLocationPublisher,

	NewCourierEmulationService,
)

// newRouteGenerator creates the route generator service
func newRouteGenerator(cfg *config.Config) *services.RouteGenerator {
	osrmURL := cfg.GetString("OSRM_URL")
	if osrmURL == "" {
		osrmURL = "http://localhost:5000"
	}

	timeout := cfg.GetDuration("OSRM_TIMEOUT")
	if timeout == 0 {
		timeout = services.DefaultRouteGeneratorConfig().Timeout
	}

	return services.NewRouteGenerator(services.RouteGeneratorConfig{
		OSRMBaseURL: osrmURL,
		Timeout:     timeout,
	})
}

// newLocationPublisher creates the Kafka location publisher
func newLocationPublisher(cfg *config.Config, log logger.Logger) (*kafka.LocationPublisher, error) {
	brokers := cfg.GetStringSlice("KAFKA_BROKERS")
	if len(brokers) == 0 {
		brokers = []string{"localhost:9092"}
	}

	publisher, err := kafka.NewLocationPublisher(kafka.PublisherConfig{
		Brokers: brokers,
	}, nil)

	if err != nil {
		log.Warn("Failed to create Kafka publisher, running without Kafka")
		return nil, nil
	}

	return publisher, nil
}

// newCourierSimulator creates the courier simulator
func newCourierSimulator(cfg *config.Config, routeGen *services.RouteGenerator, publisher *kafka.LocationPublisher) *services.CourierSimulator {
	defaultCfg := services.DefaultCourierSimulatorConfig()

	updateInterval := cfg.GetDuration("SIMULATION_UPDATE_INTERVAL")
	if updateInterval == 0 {
		updateInterval = defaultCfg.UpdateInterval
	}

	speedKmH := cfg.GetFloat64("SIMULATION_SPEED_KMH")
	if speedKmH == 0 {
		speedKmH = defaultCfg.SpeedKmH
	}

	timeMultiplier := cfg.GetFloat64("SIMULATION_TIME_MULTIPLIER")
	if timeMultiplier == 0 {
		timeMultiplier = defaultCfg.TimeMultiplier
	}

	return services.NewCourierSimulator(services.CourierSimulatorConfig{
		UpdateInterval: updateInterval,
		SpeedKmH:       speedKmH,
		TimeMultiplier: timeMultiplier,
	}, routeGen,
		publisher,
	)
}

func NewCourierEmulationService(

	log logger.Logger,
	cfg *config.Config,

	monitoring *metrics.Monitoring,
	tracer trace.TracerProvider,
	pprofHTTP profiling.PprofEndpoint,

	routeGen *services.RouteGenerator,
	simulator *services.CourierSimulator,

	publisher *kafka.LocationPublisher,
) (*CourierEmulationService, func(), error) {
	cleanup := func() {
		log.Info("Shutting down courier simulation...")

		simulator.Stop()

		if publisher != nil {
			if err := publisher.Close(); err != nil {
				log.Error(err.Error())
			}
		}
	}

	return &CourierEmulationService{

		Log:    log,
		Config: cfg,

		Tracer:        tracer,
		Monitoring:    monitoring,
		PprofEndpoint: pprofHTTP,

		RouteGenerator:   routeGen,
		CourierSimulator: simulator,

		LocationPublisher: publisher,
	}, cleanup, nil
}
