// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"context"
	"fmt"
	"github.com/google/wire"
	"github.com/shortlink-org/go-sdk/config"
	"github.com/shortlink-org/go-sdk/context"
	"github.com/shortlink-org/go-sdk/flags"
	"github.com/shortlink-org/go-sdk/grpc"
	"github.com/shortlink-org/go-sdk/logger"
	"github.com/shortlink-org/go-sdk/observability/metrics"
	"github.com/shortlink-org/go-sdk/observability/profiling"
	"github.com/shortlink-org/go-sdk/observability/tracing"
	"github.com/shortlink-org/shop/pricer/internal/di/pkg"
	"github.com/shortlink-org/shop/pricer/internal/domain/pricing"
	"github.com/shortlink-org/shop/pricer/internal/infrastructure/cli"
	"github.com/shortlink-org/shop/pricer/internal/infrastructure/policy_evaluator"
	"github.com/shortlink-org/shop/pricer/internal/infrastructure/rpc/cart/v1"
	"github.com/shortlink-org/shop/pricer/internal/infrastructure/rpc/run"
	"github.com/shortlink-org/shop/pricer/internal/usecases/cart/command/calculate_total"
	"github.com/spf13/viper"
	"go.opentelemetry.io/otel/trace"
)

// Injectors from wire.go:

func InitializePricerService() (*PricerService, func(), error) {
	context, cleanup, err := ctx.New()
	if err != nil {
		return nil, nil, err
	}
	config, err := newGoSDKConfig()
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	logger, cleanup2, err := newGoSDKLogger(context, config)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	tracerProvider, cleanup3, err := newGoSDKTracer(context, logger, config)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	monitoring, cleanup4, err := newGoSDKMonitoring(context, logger, tracerProvider, config)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	pprofEndpoint, err := newGoSDKProfiling(context, logger, tracerProvider, config)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	pkg_diConfig, err := pkg_di.ReadConfig()
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	discountPolicy, err := newDiscountPolicy(context, logger, pkg_diConfig)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	taxPolicy, err := newTaxPolicy(context, logger, pkg_diConfig)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	v, err := newPolicyNames(pkg_diConfig)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	handler, err := calculate_total.NewHandler(logger, discountPolicy, taxPolicy, v)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	server, err := newGRPCServerWithHandler(context, logger, tracerProvider, monitoring, config, handler)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	response, err := NewRunRPCServer(server)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	cliHandler := newCLIHandler(handler, pkg_diConfig)
	pricerService, err := NewPricerService(logger, config, monitoring, tracerProvider, pprofEndpoint, response, handler, cliHandler)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	return pricerService, func() {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}

// wire.go:

type PricerService struct {
	// Common
	Log    logger.Logger
	Config *config.Config

	// Observability
	Tracer        trace.TracerProvider
	Monitoring    *metrics.Monitoring
	PprofEndpoint profiling.PprofEndpoint

	// Delivery
	run *run.Response

	// Use cases
	CalculateTotalHandler *calculate_total.Handler

	// CLI
	CLIHandler *cli.CLIHandler
}

// PricerService =======================================================================================================
// CustomDefaultSet - DefaultSet with go-sdk packages (config, context, flags, profiling)
var CustomDefaultSet = wire.NewSet(ctx.New, flags.New, newGoSDKProfiling)

var PricerSet = wire.NewSet(

	CustomDefaultSet, pkg_di.ReadConfig, newGoSDKConfig,
	newGoSDKLogger,

	newGoSDKTracer,
	newGoSDKMonitoring,

	newGRPCServerWithHandler,

	newDiscountPolicy,
	newTaxPolicy,
	newPolicyNames,

	NewRunRPCServer, calculate_total.NewHandler, newCLIHandler,

	NewPricerService,
)

// newGoSDKConfig creates a go-sdk config instance
func newGoSDKConfig() (*config.Config, error) {
	return config.New()
}

// newGoSDKLogger creates a go-sdk logger instance for observability
func newGoSDKLogger(ctx2 context.Context, cfg *config.Config) (logger.Logger, func(), error) {
	return logger.NewDefault(ctx2, cfg)
}

// newGoSDKTracer creates a tracer using go-sdk observability
func newGoSDKTracer(ctx2 context.Context, log logger.Logger, cfg *config.Config) (trace.TracerProvider, func(), error) {
	return tracing.New(ctx2, log, cfg)
}

// newGoSDKMonitoring creates monitoring using go-sdk observability
func newGoSDKMonitoring(ctx2 context.Context, log logger.Logger, tracer trace.TracerProvider, cfg *config.Config) (*metrics.Monitoring, func(), error) {
	return metrics.New(ctx2, log, tracer, cfg)
}

// newGoSDKProfiling creates profiling endpoint using go-sdk observability
func newGoSDKProfiling(ctx2 context.Context, log logger.Logger, tracer trace.TracerProvider, cfg *config.Config) (profiling.PprofEndpoint, error) {
	return profiling.New(ctx2, log, tracer, cfg)
}

// newGRPCServerWithHandler creates gRPC server and registers CartService handler
func newGRPCServerWithHandler(ctx2 context.Context, log logger.Logger, tracer trace.TracerProvider, monitoring *metrics.Monitoring, cfg *config.Config, calculateTotalHandler *calculate_total.Handler) (*grpc.Server, error) {
	promRegistry := monitoring.Prometheus
	server, err := grpc.InitServer(ctx2, log, tracer, promRegistry, nil, cfg)
	if err != nil {
		return nil, err
	}
	if server != nil {
		handler := v1.NewCartHandler(calculateTotalHandler)
		v1.RegisterCartServiceServer(server.Server, handler)
	}
	return server, nil
}

func NewRunRPCServer(runRPCServer *grpc.Server) (*run.Response, error) {
	return run.Run(runRPCServer)
}

// newDiscountPolicy creates a new discount policy
func newDiscountPolicy(ctx2 context.Context, log logger.Logger, cfg *pkg_di.Config) (*pricing.DiscountPolicy, error) {
	discountPolicyPath := viper.GetString("policies.discounts")
	discountQuery := viper.GetString("queries.discounts")

	evaluator, err := policy_evaluator.NewOPAEvaluator(log, discountPolicyPath, discountQuery)
	if err != nil {
		return nil, fmt.Errorf("failed to initialize discount policy evaluator: %w", err)
	}

	return &pricing.DiscountPolicy{Evaluator: evaluator}, nil
}

// newTaxPolicy creates a new tax policy
func newTaxPolicy(ctx2 context.Context, log logger.Logger, cfg *pkg_di.Config) (*pricing.TaxPolicy, error) {
	taxPolicyPath := viper.GetString("policies.taxes")
	taxQuery := viper.GetString("queries.taxes")

	evaluator, err := policy_evaluator.NewOPAEvaluator(log, taxPolicyPath, taxQuery)
	if err != nil {
		return nil, fmt.Errorf("failed to initialize tax policy evaluator: %w", err)
	}

	return &pricing.TaxPolicy{Evaluator: evaluator}, nil
}

// newPolicyNames retrieves policy names
func newPolicyNames(cfg *pkg_di.Config) ([]string, error) {
	discountPolicyPath := viper.GetString("policies.discounts")
	taxPolicyPath := viper.GetString("policies.taxes")

	return policy_evaluator.GetPolicyNames(discountPolicyPath, taxPolicyPath)
}

// newCLIHandler creates a new CLIHandler (does not run processing - use Run() explicitly for CLI mode)
func newCLIHandler(calculateTotalHandler *calculate_total.Handler, cfg *pkg_di.Config) *cli.CLIHandler {
	outputDir := viper.GetString("output_dir")
	return cli.NewCLIHandler(calculateTotalHandler, outputDir)
}

func NewPricerService(

	log logger.Logger, config2 *config.Config,

	monitoring *metrics.Monitoring,
	tracer trace.TracerProvider,
	pprofHTTP profiling.PprofEndpoint, run2 *run.Response,

	calculateTotalHandler *calculate_total.Handler,

	cliHandler *cli.CLIHandler,
) (*PricerService, error) {
	return &PricerService{

		Log:    log,
		Config: config2,

		Tracer:        tracer,
		Monitoring:    monitoring,
		PprofEndpoint: pprofHTTP,

		run: run2,

		CalculateTotalHandler: calculateTotalHandler,

		CLIHandler: cliHandler,
	}, nil
}
