// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: infrastructure/rpc/cart/v1/cart_rpc.proto

package v1

import (
	v1 "github.com/shortlink-org/shortlink/boundaries/shop/oms/internal/infrastructure/rpc/cart/v1/model/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	_ "google.golang.org/protobuf/types/known/fieldmaskpb"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_infrastructure_rpc_cart_v1_cart_rpc_proto protoreflect.FileDescriptor

const file_infrastructure_rpc_cart_v1_cart_rpc_proto_rawDesc = "" +
	"\n" +
	")infrastructure/rpc/cart/v1/cart_rpc.proto\x12\x1ainfrastructure.rpc.cart.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a google/protobuf/field_mask.proto\x1a/infrastructure/rpc/cart/v1/model/v1/model.proto2\xf1\x02\n" +
	"\vCartService\x12N\n" +
	"\x03Add\x12/.infrastructure.rpc.cart.v1.model.v1.AddRequest\x1a\x16.google.protobuf.Empty\x12T\n" +
	"\x06Remove\x122.infrastructure.rpc.cart.v1.model.v1.RemoveRequest\x1a\x16.google.protobuf.Empty\x12h\n" +
	"\x03Get\x12/.infrastructure.rpc.cart.v1.model.v1.GetRequest\x1a0.infrastructure.rpc.cart.v1.model.v1.GetResponse\x12R\n" +
	"\x05Reset\x121.infrastructure.rpc.cart.v1.model.v1.ResetRequest\x1a\x16.google.protobuf.EmptyB\x95\x02\n" +
	"\x1ecom.infrastructure.rpc.cart.v1B\fCartRpcProtoP\x01ZZgithub.com/shortlink-org/shortlink/boundaries/shop/oms/internal/infrastructure/rpc/cart/v1\xa2\x02\x03IRC\xaa\x02\x1aInfrastructure.Rpc.Cart.V1\xca\x02\x1aInfrastructure\\Rpc\\Cart\\V1\xe2\x02&Infrastructure\\Rpc\\Cart\\V1\\GPBMetadata\xea\x02\x1dInfrastructure::Rpc::Cart::V1b\x06proto3"

var file_infrastructure_rpc_cart_v1_cart_rpc_proto_goTypes = []any{
	(*v1.AddRequest)(nil),    // 0: infrastructure.rpc.cart.v1.model.v1.AddRequest
	(*v1.RemoveRequest)(nil), // 1: infrastructure.rpc.cart.v1.model.v1.RemoveRequest
	(*v1.GetRequest)(nil),    // 2: infrastructure.rpc.cart.v1.model.v1.GetRequest
	(*v1.ResetRequest)(nil),  // 3: infrastructure.rpc.cart.v1.model.v1.ResetRequest
	(*emptypb.Empty)(nil),    // 4: google.protobuf.Empty
	(*v1.GetResponse)(nil),   // 5: infrastructure.rpc.cart.v1.model.v1.GetResponse
}
var file_infrastructure_rpc_cart_v1_cart_rpc_proto_depIdxs = []int32{
	0, // 0: infrastructure.rpc.cart.v1.CartService.Add:input_type -> infrastructure.rpc.cart.v1.model.v1.AddRequest
	1, // 1: infrastructure.rpc.cart.v1.CartService.Remove:input_type -> infrastructure.rpc.cart.v1.model.v1.RemoveRequest
	2, // 2: infrastructure.rpc.cart.v1.CartService.Get:input_type -> infrastructure.rpc.cart.v1.model.v1.GetRequest
	3, // 3: infrastructure.rpc.cart.v1.CartService.Reset:input_type -> infrastructure.rpc.cart.v1.model.v1.ResetRequest
	4, // 4: infrastructure.rpc.cart.v1.CartService.Add:output_type -> google.protobuf.Empty
	4, // 5: infrastructure.rpc.cart.v1.CartService.Remove:output_type -> google.protobuf.Empty
	5, // 6: infrastructure.rpc.cart.v1.CartService.Get:output_type -> infrastructure.rpc.cart.v1.model.v1.GetResponse
	4, // 7: infrastructure.rpc.cart.v1.CartService.Reset:output_type -> google.protobuf.Empty
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_infrastructure_rpc_cart_v1_cart_rpc_proto_init() }
func file_infrastructure_rpc_cart_v1_cart_rpc_proto_init() {
	if File_infrastructure_rpc_cart_v1_cart_rpc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_infrastructure_rpc_cart_v1_cart_rpc_proto_rawDesc), len(file_infrastructure_rpc_cart_v1_cart_rpc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_infrastructure_rpc_cart_v1_cart_rpc_proto_goTypes,
		DependencyIndexes: file_infrastructure_rpc_cart_v1_cart_rpc_proto_depIdxs,
	}.Build()
	File_infrastructure_rpc_cart_v1_cart_rpc_proto = out.File
	file_infrastructure_rpc_cart_v1_cart_rpc_proto_goTypes = nil
	file_infrastructure_rpc_cart_v1_cart_rpc_proto_depIdxs = nil
}
