version: 2
plugins:
- name: golang
  wasm:
    url: https://downloads.sqlc.dev/plugin/sqlc-gen-go_1.3.0.wasm
    sha256: e8206081686f95b461daf91a307e108a761526c6768d6f3eca9781b0726b7ec8
sql:
  - engine: postgresql
    queries: query.sql
    schema: ../migrations
    codegen:
      - plugin: golang
        out: crud
        options:
          package: crud
          emit_interface: true
          sql_package: pgx/v5
          overrides:
            - db_type: uuid
              go_type:
                import: github.com/google/uuid
                type: UUID
            - db_type: pg_catalog.numeric
              go_type:
                import: github.com/shopspring/decimal
                type: Decimal
