// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: infrastructure/rpc/cart/v1/policy.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CartItem represents an item in the shopping cart
type CartItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"` // UUID as a string
	Quantity      int32                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Price         string                 `protobuf:"bytes,3,opt,name=price,proto3" json:"price,omitempty"` // Decimal as a string to preserve precision
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CartItem) Reset() {
	*x = CartItem{}
	mi := &file_infrastructure_rpc_cart_v1_policy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CartItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CartItem) ProtoMessage() {}

func (x *CartItem) ProtoReflect() protoreflect.Message {
	mi := &file_infrastructure_rpc_cart_v1_policy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CartItem.ProtoReflect.Descriptor instead.
func (*CartItem) Descriptor() ([]byte, []int) {
	return file_infrastructure_rpc_cart_v1_policy_proto_rawDescGZIP(), []int{0}
}

func (x *CartItem) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *CartItem) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *CartItem) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

// Cart represents a customer's shopping cart
type Cart struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*CartItem            `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	CustomerId    string                 `protobuf:"bytes,2,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"` // UUID as a string
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cart) Reset() {
	*x = Cart{}
	mi := &file_infrastructure_rpc_cart_v1_policy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cart) ProtoMessage() {}

func (x *Cart) ProtoReflect() protoreflect.Message {
	mi := &file_infrastructure_rpc_cart_v1_policy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cart.ProtoReflect.Descriptor instead.
func (*Cart) Descriptor() ([]byte, []int) {
	return file_infrastructure_rpc_cart_v1_policy_proto_rawDescGZIP(), []int{1}
}

func (x *Cart) GetItems() []*CartItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *Cart) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

// CartTotal represents the calculated totals for the cart
type CartTotal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalTax      string                 `protobuf:"bytes,1,opt,name=total_tax,json=totalTax,proto3" json:"total_tax,omitempty"`                // Decimal as a string
	TotalDiscount string                 `protobuf:"bytes,2,opt,name=total_discount,json=totalDiscount,proto3" json:"total_discount,omitempty"` // Decimal as a string
	FinalPrice    string                 `protobuf:"bytes,3,opt,name=final_price,json=finalPrice,proto3" json:"final_price,omitempty"`          // Decimal as a string
	Policies      []string               `protobuf:"bytes,4,rep,name=policies,proto3" json:"policies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CartTotal) Reset() {
	*x = CartTotal{}
	mi := &file_infrastructure_rpc_cart_v1_policy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CartTotal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CartTotal) ProtoMessage() {}

func (x *CartTotal) ProtoReflect() protoreflect.Message {
	mi := &file_infrastructure_rpc_cart_v1_policy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CartTotal.ProtoReflect.Descriptor instead.
func (*CartTotal) Descriptor() ([]byte, []int) {
	return file_infrastructure_rpc_cart_v1_policy_proto_rawDescGZIP(), []int{2}
}

func (x *CartTotal) GetTotalTax() string {
	if x != nil {
		return x.TotalTax
	}
	return ""
}

func (x *CartTotal) GetTotalDiscount() string {
	if x != nil {
		return x.TotalDiscount
	}
	return ""
}

func (x *CartTotal) GetFinalPrice() string {
	if x != nil {
		return x.FinalPrice
	}
	return ""
}

func (x *CartTotal) GetPolicies() []string {
	if x != nil {
		return x.Policies
	}
	return nil
}

// CalculateTotalRequest is the request message for calculating cart totals
type CalculateTotalRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Cart           *Cart                  `protobuf:"bytes,1,opt,name=cart,proto3" json:"cart,omitempty"`
	DiscountParams map[string]string      `protobuf:"bytes,2,rep,name=discount_params,json=discountParams,proto3" json:"discount_params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Using string for simplicity
	TaxParams      map[string]string      `protobuf:"bytes,3,rep,name=tax_params,json=taxParams,proto3" json:"tax_params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`                // Using string for simplicity
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CalculateTotalRequest) Reset() {
	*x = CalculateTotalRequest{}
	mi := &file_infrastructure_rpc_cart_v1_policy_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculateTotalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateTotalRequest) ProtoMessage() {}

func (x *CalculateTotalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_infrastructure_rpc_cart_v1_policy_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateTotalRequest.ProtoReflect.Descriptor instead.
func (*CalculateTotalRequest) Descriptor() ([]byte, []int) {
	return file_infrastructure_rpc_cart_v1_policy_proto_rawDescGZIP(), []int{3}
}

func (x *CalculateTotalRequest) GetCart() *Cart {
	if x != nil {
		return x.Cart
	}
	return nil
}

func (x *CalculateTotalRequest) GetDiscountParams() map[string]string {
	if x != nil {
		return x.DiscountParams
	}
	return nil
}

func (x *CalculateTotalRequest) GetTaxParams() map[string]string {
	if x != nil {
		return x.TaxParams
	}
	return nil
}

// CalculateTotalResponse is the response message after calculating totals
type CalculateTotalResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         *CartTotal             `protobuf:"bytes,1,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalculateTotalResponse) Reset() {
	*x = CalculateTotalResponse{}
	mi := &file_infrastructure_rpc_cart_v1_policy_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculateTotalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateTotalResponse) ProtoMessage() {}

func (x *CalculateTotalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_infrastructure_rpc_cart_v1_policy_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateTotalResponse.ProtoReflect.Descriptor instead.
func (*CalculateTotalResponse) Descriptor() ([]byte, []int) {
	return file_infrastructure_rpc_cart_v1_policy_proto_rawDescGZIP(), []int{4}
}

func (x *CalculateTotalResponse) GetTotal() *CartTotal {
	if x != nil {
		return x.Total
	}
	return nil
}

var File_infrastructure_rpc_cart_v1_policy_proto protoreflect.FileDescriptor

const file_infrastructure_rpc_cart_v1_policy_proto_rawDesc = "" +
	"\n" +
	"'infrastructure/rpc/cart/v1/policy.proto\x12\x04cart\"[\n" +
	"\bCartItem\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x05R\bquantity\x12\x14\n" +
	"\x05price\x18\x03 \x01(\tR\x05price\"M\n" +
	"\x04Cart\x12$\n" +
	"\x05items\x18\x01 \x03(\v2\x0e.cart.CartItemR\x05items\x12\x1f\n" +
	"\vcustomer_id\x18\x02 \x01(\tR\n" +
	"customerId\"\x8c\x01\n" +
	"\tCartTotal\x12\x1b\n" +
	"\ttotal_tax\x18\x01 \x01(\tR\btotalTax\x12%\n" +
	"\x0etotal_discount\x18\x02 \x01(\tR\rtotalDiscount\x12\x1f\n" +
	"\vfinal_price\x18\x03 \x01(\tR\n" +
	"finalPrice\x12\x1a\n" +
	"\bpolicies\x18\x04 \x03(\tR\bpolicies\"\xdd\x02\n" +
	"\x15CalculateTotalRequest\x12\x1e\n" +
	"\x04cart\x18\x01 \x01(\v2\n" +
	".cart.CartR\x04cart\x12X\n" +
	"\x0fdiscount_params\x18\x02 \x03(\v2/.cart.CalculateTotalRequest.DiscountParamsEntryR\x0ediscountParams\x12I\n" +
	"\n" +
	"tax_params\x18\x03 \x03(\v2*.cart.CalculateTotalRequest.TaxParamsEntryR\ttaxParams\x1aA\n" +
	"\x13DiscountParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a<\n" +
	"\x0eTaxParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"?\n" +
	"\x16CalculateTotalResponse\x12%\n" +
	"\x05total\x18\x01 \x01(\v2\x0f.cart.CartTotalR\x05total2Z\n" +
	"\vCartService\x12K\n" +
	"\x0eCalculateTotal\x12\x1b.cart.CalculateTotalRequest\x1a\x1c.cart.CalculateTotalResponseB\x91\x01\n" +
	"\bcom.cartB\vPolicyProtoP\x01ZHgithub.com/shortlink-org/shop/pricer/internal/infrastructure/rpc/cart/v1\xa2\x02\x03CXX\xaa\x02\x04Cart\xca\x02\x04Cart\xe2\x02\x10Cart\\GPBMetadata\xea\x02\x04Cartb\x06proto3"

var (
	file_infrastructure_rpc_cart_v1_policy_proto_rawDescOnce sync.Once
	file_infrastructure_rpc_cart_v1_policy_proto_rawDescData []byte
)

func file_infrastructure_rpc_cart_v1_policy_proto_rawDescGZIP() []byte {
	file_infrastructure_rpc_cart_v1_policy_proto_rawDescOnce.Do(func() {
		file_infrastructure_rpc_cart_v1_policy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_infrastructure_rpc_cart_v1_policy_proto_rawDesc), len(file_infrastructure_rpc_cart_v1_policy_proto_rawDesc)))
	})
	return file_infrastructure_rpc_cart_v1_policy_proto_rawDescData
}

var file_infrastructure_rpc_cart_v1_policy_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_infrastructure_rpc_cart_v1_policy_proto_goTypes = []any{
	(*CartItem)(nil),               // 0: cart.CartItem
	(*Cart)(nil),                   // 1: cart.Cart
	(*CartTotal)(nil),              // 2: cart.CartTotal
	(*CalculateTotalRequest)(nil),  // 3: cart.CalculateTotalRequest
	(*CalculateTotalResponse)(nil), // 4: cart.CalculateTotalResponse
	nil,                            // 5: cart.CalculateTotalRequest.DiscountParamsEntry
	nil,                            // 6: cart.CalculateTotalRequest.TaxParamsEntry
}
var file_infrastructure_rpc_cart_v1_policy_proto_depIdxs = []int32{
	0, // 0: cart.Cart.items:type_name -> cart.CartItem
	1, // 1: cart.CalculateTotalRequest.cart:type_name -> cart.Cart
	5, // 2: cart.CalculateTotalRequest.discount_params:type_name -> cart.CalculateTotalRequest.DiscountParamsEntry
	6, // 3: cart.CalculateTotalRequest.tax_params:type_name -> cart.CalculateTotalRequest.TaxParamsEntry
	2, // 4: cart.CalculateTotalResponse.total:type_name -> cart.CartTotal
	3, // 5: cart.CartService.CalculateTotal:input_type -> cart.CalculateTotalRequest
	4, // 6: cart.CartService.CalculateTotal:output_type -> cart.CalculateTotalResponse
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_infrastructure_rpc_cart_v1_policy_proto_init() }
func file_infrastructure_rpc_cart_v1_policy_proto_init() {
	if File_infrastructure_rpc_cart_v1_policy_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_infrastructure_rpc_cart_v1_policy_proto_rawDesc), len(file_infrastructure_rpc_cart_v1_policy_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_infrastructure_rpc_cart_v1_policy_proto_goTypes,
		DependencyIndexes: file_infrastructure_rpc_cart_v1_policy_proto_depIdxs,
		MessageInfos:      file_infrastructure_rpc_cart_v1_policy_proto_msgTypes,
	}.Build()
	File_infrastructure_rpc_cart_v1_policy_proto = out.File
	file_infrastructure_rpc_cart_v1_policy_proto_goTypes = nil
	file_infrastructure_rpc_cart_v1_policy_proto_depIdxs = nil
}
