// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: domain/order/v1/commands/v1/commands.proto

package v1

import (
	common "github.com/shortlink-org/shop/oms/internal/domain/order/v1/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CreateOrderCommand - Command to create a new order
type CreateOrderCommand struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Order ID
	OrderId string `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	// Customer ID
	CustomerId string `protobuf:"bytes,2,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	// Order items
	Items         []*common.OrderItem `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderCommand) Reset() {
	*x = CreateOrderCommand{}
	mi := &file_domain_order_v1_commands_v1_commands_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderCommand) ProtoMessage() {}

func (x *CreateOrderCommand) ProtoReflect() protoreflect.Message {
	mi := &file_domain_order_v1_commands_v1_commands_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderCommand.ProtoReflect.Descriptor instead.
func (*CreateOrderCommand) Descriptor() ([]byte, []int) {
	return file_domain_order_v1_commands_v1_commands_proto_rawDescGZIP(), []int{0}
}

func (x *CreateOrderCommand) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *CreateOrderCommand) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *CreateOrderCommand) GetItems() []*common.OrderItem {
	if x != nil {
		return x.Items
	}
	return nil
}

// CancelOrderCommand - Command to cancel an order
type CancelOrderCommand struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Order ID
	OrderId string `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	// Cancellation reason (optional)
	Reason        string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelOrderCommand) Reset() {
	*x = CancelOrderCommand{}
	mi := &file_domain_order_v1_commands_v1_commands_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOrderCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOrderCommand) ProtoMessage() {}

func (x *CancelOrderCommand) ProtoReflect() protoreflect.Message {
	mi := &file_domain_order_v1_commands_v1_commands_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOrderCommand.ProtoReflect.Descriptor instead.
func (*CancelOrderCommand) Descriptor() ([]byte, []int) {
	return file_domain_order_v1_commands_v1_commands_proto_rawDescGZIP(), []int{1}
}

func (x *CancelOrderCommand) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *CancelOrderCommand) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// CompleteOrderCommand - Command to complete an order
type CompleteOrderCommand struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Order ID
	OrderId       string `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteOrderCommand) Reset() {
	*x = CompleteOrderCommand{}
	mi := &file_domain_order_v1_commands_v1_commands_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteOrderCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteOrderCommand) ProtoMessage() {}

func (x *CompleteOrderCommand) ProtoReflect() protoreflect.Message {
	mi := &file_domain_order_v1_commands_v1_commands_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteOrderCommand.ProtoReflect.Descriptor instead.
func (*CompleteOrderCommand) Descriptor() ([]byte, []int) {
	return file_domain_order_v1_commands_v1_commands_proto_rawDescGZIP(), []int{2}
}

func (x *CompleteOrderCommand) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

// UpdateOrderCommand - Command to update order items
type UpdateOrderCommand struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Order ID
	OrderId string `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	// Updated order items
	Items         []*common.OrderItem `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateOrderCommand) Reset() {
	*x = UpdateOrderCommand{}
	mi := &file_domain_order_v1_commands_v1_commands_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOrderCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOrderCommand) ProtoMessage() {}

func (x *UpdateOrderCommand) ProtoReflect() protoreflect.Message {
	mi := &file_domain_order_v1_commands_v1_commands_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOrderCommand.ProtoReflect.Descriptor instead.
func (*UpdateOrderCommand) Descriptor() ([]byte, []int) {
	return file_domain_order_v1_commands_v1_commands_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateOrderCommand) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *UpdateOrderCommand) GetItems() []*common.OrderItem {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_domain_order_v1_commands_v1_commands_proto protoreflect.FileDescriptor

const file_domain_order_v1_commands_v1_commands_proto_rawDesc = "" +
	"\n" +
	"*domain/order/v1/commands/v1/commands.proto\x12\x18domain.order.commands.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a#domain/order/v1/common/common.proto\"\x89\x01\n" +
	"\x12CreateOrderCommand\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x1f\n" +
	"\vcustomer_id\x18\x02 \x01(\tR\n" +
	"customerId\x127\n" +
	"\x05items\x18\x03 \x03(\v2!.domain.order.common.v1.OrderItemR\x05items\"G\n" +
	"\x12CancelOrderCommand\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"1\n" +
	"\x14CompleteOrderCommand\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\"h\n" +
	"\x12UpdateOrderCommand\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x127\n" +
	"\x05items\x18\x02 \x03(\v2!.domain.order.common.v1.OrderItemR\x05itemsB\xf8\x01\n" +
	"\x1ccom.domain.order.commands.v1B\rCommandsProtoP\x01ZFgithub.com/shortlink-org/shop/oms/internal/domain/order/v1/commands/v1\xa2\x02\x03DOC\xaa\x02\x18Domain.Order.Commands.V1\xca\x02\x18Domain\\Order\\Commands\\V1\xe2\x02$Domain\\Order\\Commands\\V1\\GPBMetadata\xea\x02\x1bDomain::Order::Commands::V1b\x06proto3"

var (
	file_domain_order_v1_commands_v1_commands_proto_rawDescOnce sync.Once
	file_domain_order_v1_commands_v1_commands_proto_rawDescData []byte
)

func file_domain_order_v1_commands_v1_commands_proto_rawDescGZIP() []byte {
	file_domain_order_v1_commands_v1_commands_proto_rawDescOnce.Do(func() {
		file_domain_order_v1_commands_v1_commands_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_domain_order_v1_commands_v1_commands_proto_rawDesc), len(file_domain_order_v1_commands_v1_commands_proto_rawDesc)))
	})
	return file_domain_order_v1_commands_v1_commands_proto_rawDescData
}

var file_domain_order_v1_commands_v1_commands_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_domain_order_v1_commands_v1_commands_proto_goTypes = []any{
	(*CreateOrderCommand)(nil),   // 0: domain.order.commands.v1.CreateOrderCommand
	(*CancelOrderCommand)(nil),   // 1: domain.order.commands.v1.CancelOrderCommand
	(*CompleteOrderCommand)(nil), // 2: domain.order.commands.v1.CompleteOrderCommand
	(*UpdateOrderCommand)(nil),   // 3: domain.order.commands.v1.UpdateOrderCommand
	(*common.OrderItem)(nil),     // 4: domain.order.common.v1.OrderItem
}
var file_domain_order_v1_commands_v1_commands_proto_depIdxs = []int32{
	4, // 0: domain.order.commands.v1.CreateOrderCommand.items:type_name -> domain.order.common.v1.OrderItem
	4, // 1: domain.order.commands.v1.UpdateOrderCommand.items:type_name -> domain.order.common.v1.OrderItem
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_domain_order_v1_commands_v1_commands_proto_init() }
func file_domain_order_v1_commands_v1_commands_proto_init() {
	if File_domain_order_v1_commands_v1_commands_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_domain_order_v1_commands_v1_commands_proto_rawDesc), len(file_domain_order_v1_commands_v1_commands_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_domain_order_v1_commands_v1_commands_proto_goTypes,
		DependencyIndexes: file_domain_order_v1_commands_v1_commands_proto_depIdxs,
		MessageInfos:      file_domain_order_v1_commands_v1_commands_proto_msgTypes,
	}.Build()
	File_domain_order_v1_commands_v1_commands_proto = out.File
	file_domain_order_v1_commands_v1_commands_proto_goTypes = nil
	file_domain_order_v1_commands_v1_commands_proto_depIdxs = nil
}
